### ISSUE TITLE
Numverify scan: You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]

### ISSUE THREAD

**Issue by Ajay-056** [sundowndev/phoneinfoga#1013]
Numverify scan: You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]

**Comment by Ajay-056** [comment]
In GUI Mode asking for API Access Key

**Comment by sundowndev** [comment]
Numverify scan requires an API key, [read documentation](https://sundowndev.github.io/phoneinfoga/scanners/#numverify).

**Comment by munikatoch** [comment]
How to pass this API key? I got my key from numverify but I can't  find how to pass this API key.

**Comment by pmead7399** [comment]
Ditto the last post. I made an account on Numverify and got an API key but I have no idea how to implement it. Can anyone help?

Thanks.

**Comment by moworld** [comment]
I  had this same problem. I think the documentation assumes linux. On Windows, for me, I just added and environment variable called NUMVERIFY_API_KEY with the value as my API key. Reload the terminal, then run the command again. Worked for me. Hope it helps.
