### ISSUE TITLE
Could not install it correctly on python 3 in windows 10

### ISSUE THREAD

**Issue by mriceflame1** [sundowndev/PhoneInfoga#102]
C:\Users\farha>pip install git+https://github.com/sundowndev/PhoneInfoga.git
Collecting git+https://github.com/sundowndev/PhoneInfoga.git
  Cloning https://github.com/sundowndev/PhoneInfoga.git to c:\users\farha\appdata\local\temp\pip-req-build-p5rhn7s_
  Running command git clone -q https://github.com/sundowndev/PhoneInfoga.git 'C:\Users\farha\AppData\Local\Temp\pip-req-build-p5rhn7s_'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\farha\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\farha\\AppData\\Local\\Temp\\pip-req-build-p5rhn7s_\\setup.py'"'"'; __file__='"'"'C:\\Users\\farha\\AppData\\Local\\Temp\\pip-req-build-p5rhn7s_\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\farha\AppData\Local\Temp\pip-req-build-p5rhn7s_\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\farha\appdata\local\programs\python\python37\lib\tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\farha\\AppData\\Local\\Temp\\pip-req-build-p5rhn7s_\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sundowndev** [comment]
You did not followed the install instructions.
