### ISSUE TITLE
error

### ISSUE THREAD

**Issue by peyman13671368** [sundowndev/phoneinfoga#1048]
You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie
please help me

**Comment by peyman13671368** [comment]
You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie

**Comment by sundowndev** [comment]
You are using version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
