### ISSUE TITLE
python3 phoneinfoga.py -n 919810xxxx or any command same issue arising

### ISSUE THREAD

**Issue by Kevintroll** [sundowndev/PhoneInfoga#105]
root@kali:~/PhoneInfoga# python3 phoneinfoga.py -n 919810xxxxxx
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev

[!] ---- Fetching informations for 919810xxxxxx ---- [!]
[*] Running local scan...
[+] International format: +91 9810xxxxxx
[+] Local format: 9810xxxxxx
[+] Country found: India (+91)
[+] City/Area: India
[+] Carrier: Airtel
[+] Timezone: Asia/Calcutta
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+91) 0981xxxxxxx
[+] Country: India (Republic of) (IN)
[+] Location: Delhi
[+] Carrier: Bharti Airtel Ltd
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[i] Generating scan URL on 411.com...
[i] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/91-98105-93038
Would you like to use an additional format for this number ? (y/N) y
[i] We recommand: +91 98105 93038 or 98105 93038
Custom format: +91 98105 93038
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by sundowndev** [comment]
You did not installed geckodriver (at least properly).

**Comment by Kevintroll** [comment]
Thanks I will Install and Let you update.
