### ISSUE TITLE
Numverifiy API key isn't working?

### ISSUE THREAD

**Issue by winter-1337** [sundowndev/phoneinfoga#1056]
When I run the GUI it shows me: `Numverify scan: You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]`

So I went in the terminal a did `access_key=xxxxxxxxxx`, reloaded everything and it still gave me this error, so I checked the documents and also tried the `NUMVERIFY_API_KEY=xxxxxxxxxx`, reloaded, and nothing.

I'm running Kali Linux.

**Comment by kriss-u** [comment]
@winter-1337 

It looks like the numverify services accepted API keys in GET query parameters. Now, this is shifted to a customer header "apikey".

This line here:

https://github.com/sundowndev/phoneinfoga/blob/503e24c364bed6381857fa5de8c4430f2dd2d235/lib/remote/suppliers/numverify.go#L66

**Comment by sundowndev** [comment]
Thanks for pointing that out @kriss-u, I'll push a patch for this when I get time.

**Comment by FireTonnor** [comment]
is still does not work i am trying to install it and run it but  it will not run

**Comment by kriss-u** [comment]
@sundowndev I have done the fix but I couldn't find any way to push it to a branch. Isn't there any contribution guide? 

Do I need to create a fork and then send a PR?

**Comment by kriss-u** [comment]
@FireTonnor This issue will be resolved by #1072 if the maintainer approves it after testing.

**Comment by sundowndev** [comment]
Should be fixed in [v2.4.4](https://github.com/sundowndev/phoneinfoga/releases/tag/v2.4.4).
