### ISSUE TITLE
Kali Nethunter

### ISSUE THREAD

**Issue by mrx7014** [sundowndev/phoneinfoga#1059]
This tool is not working in kali nethunter why,please support it :)

**Comment by sundowndev** [comment]
What architecture is that? Have you tested the [linux-armv6 binary](https://github.com/sundowndev/phoneinfoga/releases/download/v2.8.2/phoneinfoga_Linux_armv6.tar.gz) ?

**Comment by mrx7014** [comment]
Thanks Bro Problem was Solved.

**Comment by jimmyphyo-sys** [comment]
I can' t help me plz

**Comment by xenoZ0x** [comment]
> I can' t help me plz

what's the problem with you ?
