### ISSUE TITLE
Weird Behaviour with international number

### ISSUE THREAD

**Issue by shadowownz0** [sundowndev/PhoneInfoga#106]
**Describe the bug**
After installing the latest gecko and moved it to /usr/local/bin, when searching for an international number, firefox just opens a single tab and flips through the entire search sites in 1 go, always replacing the previous one instead of opening a new tab for each. i do see the parameters like "site:quinumero.info "XXX XXX XXX XXX" OR "+XXX XXX XXX XXX" " on the google search bar.

**To Reproduce**
Just used the python3 phoneinfoga.py -n (COUNTRY INDICATIVE)(NUMBER)

**Expected behavior**
I guess Firefox should have opened multiple tabs with the respective search site information instead of just google and switching the search bar info.

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: 
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.3
Codename:	kali-rolling
Arch: 32 bit

 - Python exact version (run `python --version`)
Python 2.7.16+

**Additional context**
Firefox geckodriver 0.24.0

**Comment by sundowndev** [comment]
No. PhoneInfoga opens Firefox to search through Google search but in order to display results in the terminal, not in the browser. The browser is only here to solve captcha when needed. Opening only one tab is the intended behavior.
