### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by GLXS00** [sundowndev/PhoneInfoga#107]
Keep getting errors and this doesn't seem to be working right. Trying to do a simple search with Phoneinfoga. Can someone tell me what I am doing wrong? [Image](https://imgur.com/a/2OWWouM)

**Comment by shadowownz0** [comment]
Did you cp the config file?

**Comment by sundowndev** [comment]
You have to create the config file:
```shell
cp config.example.py config.py
```

**Comment by sumsh** [comment]
Hey @sundowndev , I am quite new to here. But why don't create a function to create config.py if no config file is currently available?

**Comment by sundowndev** [comment]
@sumsh This step is mentioned in the docs.

**Comment by sundowndev** [comment]
Duplicate of #70
