### ISSUE TITLE
Verify (Checksum) Bug! (NEEDS FIX)

### ISSUE THREAD

**Issue by G00Dway** [sundowndev/phoneinfoga#1080]
heya, i just got an error while installing the program, the error was:
```
"PhoneInfoga_Linux_x86_64.tar.gz.1’ saved [6188970/6188970]

Verifying checksum...
sha256sum: 'standard input': no file was verified"
```
no, i mean, yes its error but i am trying to install it like 5th day today, so please i wish this will be fixed in some days!
and yes i fixed it manually, i mean i just extracted the `.tar.xz` file then copyed the `phoneinfoga` to the `/usr/bin` folder, i dont know it will work or not but i didnt runned it (i mean for scan)

Info
------
System: ```GNU/Linux (Kali Linux)```

**Comment by sundowndev** [comment]
Thanks for the report, it should be fixed now.
