### ISSUE TITLE
Numverify not working in Docker

### ISSUE THREAD

**Issue by second2falcon** [sundowndev/phoneinfoga#1082]
**Describe the bug**
I was trying to scan phone numbers on my instance of phoneinfoga hosted with docker. All were shown as falls eventho I enterd my api key as env variable.

**To Reproduce**
Tried to scan via the web interface

**Expected behavior**
Show country of origin and other info

**Desktop (please complete the following information):**
 - OS: Windows 10 (Container created via docker pull and env variable edited via portainer)
 - PhoneInfoga exact version the container from ~4 hours ago (can't run the command because of docker)
 - Go exact version: 1.17.8 (specified in env var)

**Comment by sundowndev** [comment]
What command did you use to create the container ?

**Comment by second2falcon** [comment]
First 
`docker pull sundowndev/phoneinfoga:latest`
and then
`docker run -it -p 5000:5000 sundowndev/phoneinfoga:latest serve -p 5000`
after that I stopped the container in portainer and edited, recreated with the api key added.

**Comment by orkowizard** [comment]
I'm using docker-compose and having the same issues. docker-compose.yml:

`version: '3.7'

services:
    phoneinfoga:
      container_name: phoneinfoga
      restart: on-failure
      image: sundowndev/phoneinfoga:latest
      command: serve
      ports:
        - "5200:5000"
      environment:
        - NUMVERIFY_API_KEY=xxxx`

**Comment by PaPaTheGMan** [comment]
I'm also using Docker Compose and receiving "Numverify scan: Invalid authentication credentials" when using a direct copy of "Your API Access Key" from my Account Dashboard on the numverify portal.

**Comment by PaPaTheGMan** [comment]
No, I wasn't.  I didn't see that change in the documentation.  I've signed up for apilayer and updated my NUMVERIFY_API_KEY but am still getting the error.  Has the docker environment variable name changed as well?

**Comment by sundowndev** [comment]
@PaPaTheGMan Not it has not. What Docker command are you running ?

**Comment by second2falcon** [comment]
> @PaPaTheGMan Not it has not. What Docker command are you running ?

I actually just used NUMVERIFY's API, but gonna try apilayer's now.

**Comment by second2falcon** [comment]
Update: Problem solved. Instead of using numverify.com use APIlayer.com for the API key. 
When you go to their marketplace, go down and use a "Number Verification API". Enter that into however you set phoneinfoga up (so if via portainer, you can edit the env for it there; etc)

**Comment by PaPaTheGMan** [comment]
As I said above, I did switch over to APIlayer.com, but I still get "Numverify scan: Invalid authentication credentials".  Here's my docker compose:
version: '3.7'
services:
    phoneinfoga:
      container_name: phoneinfoga
      restart: on-failure
      image: sundowndev/phoneinfoga
      command:
        - "serve"
      ports:
        - "5100:5000"
      environment:
        - NUMVERIFY_API_KEY="new key from APIlayer"

**Comment by second2falcon** [comment]
Remove the " (quotation marks). Sometimes they brake environment variables.

**Comment by second2falcon** [comment]
@sundowndev an idea why I can't reverse proxy it to outside my network? (For security I have enabled an access list in Nginx)

**Comment by PaPaTheGMan** [comment]
Thanks so much, removing the quotation's did the trick.
