### ISSUE TITLE
[!] Numverify.com is not available

### ISSUE THREAD

**Issue by telenhackse** [sundowndev/phoneinfoga#1107]
Hi, I'm from Chile. When I scan a number, it shows me "[!] Numverify.com is not available." How do I fix it?
example:
[*] Running local scan...
[+] International format: +56 9 99999999
[+] Local format: 56999999999
[+] Country found: Chile (+56)
[+] City/Area: Chile
[+] Carrier:
[+] Timezone: America/Santiago
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[!] Numverify.com is not available
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
i need to fix it!!

**Comment by Pierack** [comment]
Me pasa lo mismo.  Lei por ahi es que con el api actual de numverify ya no se puede.  No se si alguien pueda responder  eso.

**Comment by sundowndev** [comment]
You are trying to use version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/getting-started/install/) to install version 2.
