### ISSUE TITLE
No --osint flags in phoneinfoga?

### ISSUE THREAD

**Issue by dominover** [sundowndev/phoneinfoga#1110]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by dominover** [comment]
I'm not sure I've installed phoneinfoga correctly which would be why I'm getting an issue.
My search results just bring up a bunch of Google Dorks with not information about whether there was a result or not.
I also noticed that there is no --osint flag now when I type in phoneinfoga help?
Does this mean I've installed it correctly? I'm using it through Kali Linux virtual machine on Windows 10.

**Comment by sundowndev** [comment]
Hi, you've probably followed a tutorial about version 1 of this software, which is outdated. [See documentation for version 2](https://sundowndev.github.io/phoneinfoga/).

> My search results just bring up a bunch of Google Dorks with not information about whether there was a result or not.

Yes this is expected. The tool doesn't scrape Google result anymore, it just generate a bunch of dork request for you to use. We don't want to deal with Google captcha anymore.

**Comment by dominover** [comment]
> Hi, you've probably followed a tutorial about version 1 of this software, which is outdated. [See documentation for version 2](https://sundowndev.github.io/phoneinfoga/).
> 
> > My search results just bring up a bunch of Google Dorks with not information about whether there was a result or not.
> 
> Yes this is expected. The tool doesn't scrape Google results anymore, it just generate a bunch of dork requests for you to use. We don't want to deal with Google captcha anymore.

Thanks for your reply.  I figured that may have been the case.  The other issue is that some of the online demonstrations using the previous versions utilize a flagg --osint .  This appears to be missing now.  Was that intentional?

**Comment by sundowndev** [comment]
This feature is now enabled by default in the googlesearch scanner. Google dorks include a local format of the phone number, based on the country code. So you don't have to use --osint anymore.

**Comment by dominover** [comment]
> This feature is now enabled by default in the googlesearch scanner. Google dorks include a local format of the phone number, based on the country code. So you don't have to use --osint anymore.

 That solves it then. 
Thanks very much for the help. Truly appreciated!

**Comment by sundowndev** [comment]
@dominover  To follow up on this, `googlecse` scanner was introduced which allow searching on Google automatically ([see docs](https://sundowndev.github.io/phoneinfoga/getting-started/scanners/#googlecse)). Note it works only in CLI for now as the web client is now in feature freeze until the new client comes out.

**Comment by White-devil5890** [comment]
Sir can i use this website? because I'm learning  .
