### ISSUE TITLE
Numverify scan not showing any info (for Spanish mobile numbers)

### ISSUE THREAD

**Issue by aagirre92** [sundowndev/phoneinfoga#1118]
**Describe the bug**
Tool does not show any information in the Numverify scan field

**To Reproduce**
I've run the tool both via web server and bash

**Expected behavior**
It's expected that some information about phone carrier pops up in this Numverify scan field

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - PhoneInfoga exact version: 2.6.0

**Comment by aagirre92** [comment]
I have just added the API key for Numverify and it works (I think that was the issue)

**Comment by sundowndev** [comment]
Eventually fixed by https://github.com/sundowndev/phoneinfoga/pull/1125

**Comment by sundowndev** [comment]
@aagirre92 thanks for the feedback, closing.
