### ISSUE TITLE
Error installing phoneinfoga: No module named 'lib.args'

### ISSUE THREAD

**Issue by loeffea886** [sundowndev/phoneinfoga#1128]
kali@kali:~/PhoneInfoga$ python3 phoneinfoga.py -v
Traceback (most recent call last):
  File "/home/kali/PhoneInfoga/phoneinfoga.py", line 12, in <module>
    from lib.args import args,parser
ModuleNotFoundError: No module named 'lib.args'

**Comment by sundowndev** [comment]
Hi, this project does not use Python anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/getting-started/install/).
