### ISSUE TITLE
No external access behind reverse proxy with authentication?

### ISSUE THREAD

**Issue by second2falcon** [sundowndev/phoneinfoga#1133]
**Describe the bug**
I am trying to access my PhoneInfoga (it is behind a login and a reverse proxy) instance remotely and I continue to get a bad gateway 502 error.

**To Reproduce**
Run phoneinfoga in docker and direct it to an external domain using nginx proxy manager and an access list

**Expected behavior**
Webinterface comming up

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Server OS: Debian 11 (running Docker and Portainer)
 - PhoneInfoga exact version: latest Docker container
 - Go exact version: Portainer reports version 1.17.8

**Additional context**
Using NGINX proxy manager and access list to securely access instance but getting 502 bad gateway errors. No other site showing 502 bad gateway (except one where remote access is turned off when not in use).

**Comment by sundowndev** [comment]
Hi, what's Docker command used ? Did you inspect the logs of the phoneinfoga and nginx containers ?

**Comment by second2falcon** [comment]
> Hi, what's Docker command used ? Did you inspect the logs of the phoneinfoga and nginx containers ?

I used this docker-compose:

version: '3.7'

services:
    phoneinfoga:
      container_name: phoneinfoga
      restart: unless-stopped
      image: sundowndev/phoneinfoga:latest
      command:
        - "serve"
      ports:
        - "3924:5000"
      environment:
        - NUMVERIFY_API_KEY=***

I just redid the NGINX entry and now I it works. Nothing was ever logged when I tried. Probably some bug in NGINX proxy manager.
