### ISSUE TITLE
Support, complementation and addition of an Android operating system is needed for linux-based termux: Linux_armv7l

### ISSUE THREAD

**Issue by Darkrevengehack** [sundowndev/phoneinfoga#1135]
**Describe the bug**
Need support and add OS for Android in and for termux: Linux_armv7l

preferably it is better to add that download and installation option in .zip format

I hope you can do this friend, it is something that I ask you, and other people also ask you and have asked you friend.

**Comment by sundowndev** [comment]
Support added for armv7: https://github.com/sundowndev/phoneinfoga/releases/tag/v2.9.0
