### ISSUE TITLE
Phoneinfoga For termux 

### ISSUE THREAD

**Issue by balookhan67** [sundowndev/phoneinfoga#1149]
How to use it in termux?

**Comment by balookhan67** [comment]
I tried with this link
$ git clone https://github.com/Wes974/Phone Infoga

But it got banned now. Is there any way to use it again on termux please

**Comment by sundowndev** [comment]
See https://github.com/sundowndev/phoneinfoga/issues/573

**Comment by balookhan67** [comment]
But he has already phoneinfoga installed in his termux 
Can you send me its installation link
please

**Comment by sundowndev** [comment]
> Phoneinfoga is't a part of official repo yet so you have to install it via compiling from source or visit [Release page](https://github.com/sundowndev/PhoneInfoga/releases)

**Comment by johy99** [comment]
How to work phoneinfoga in termux ???

**Comment by johy99** [comment]
Please someone help me for this !!
