### ISSUE TITLE
Api 

### ISSUE THREAD

**Issue by VarunBanka** [sundowndev/phoneinfoga#1167]
Do you have a API? If yes, where's it's documents?

**Comment by sundowndev** [comment]
See [API documentation](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/sundowndev/phoneinfoga/master/web/docs/swagger.yaml). Please deploy your own instance, do not use the demo's api.

**Comment by VarunBanka** [comment]
Okay, thanks
