### ISSUE TITLE
setting up googlecse scanner

### ISSUE THREAD

**Issue by ilyadar** [sundowndev/phoneinfoga#1174]
I enabled the custom search API, created a new API token, created a new search engine, and that's it. As far as I could go. What should be my next step?

**Comment by sundowndev** [comment]
As per the documentation, you should then fill up environment variables with your API key and CX ID:
```bash
# Example
GOOGLECSE_CX=foo GOOGLE_API_KEY=bar phoneinfoga scan -n +1241325xxxx
```
Alternatively, you can also [use a configuration file](https://sundowndev.github.io/phoneinfoga/getting-started/scanners/#configuration) to set those variables.

**Comment by ilyadar** [comment]
appreciate it
