### ISSUE TITLE
How to remove this entire tool at once from my laptop without any traces?

### ISSUE THREAD

**Issue by Sathishkantamsetti** [sundowndev/PhoneInfoga#118]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - Python exact version (run `python --version`)

**Additional context**

**Comment by sundowndev** [comment]
It depends on how you installed it. If you cloned the repository, just delete the phoneinfoga folder. Note that dependencies will still be installed tho.
