### ISSUE TITLE
How do i create 'cp config.example.py config.py' file?

### ISSUE THREAD

**Issue by zeronine-exe** [sundowndev/phoneinfoga#1187]
@sundowndev please help mate, i'm new at these

PS C:\Users\sheik> git clone http://github.com/sundowndev/PhoneInfoga
fatal: destination path 'PhoneInfoga' already exists and is not an empty directory.
PS C:\Users\sheik> cd Phoneinfoga
PS C:\Users\sheik\Phoneinfoga> pip freeze > requirments.txt
PS C:\Users\sheik\Phoneinfoga> python3 -m pip install -r requirments.txt
Requirement already satisfied: certifi==2022.12.7 in c:\users\sheik\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirments.txt (line 1)) (2022.12.7)
Requirement already satisfied: charset-normalizer==2.1.1 in c:\users\sheik\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirments.txt (line 2)) (2.1.1)
Requirement already satisfied: docopt==0.6.2 in c:\users\sheik\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirments.txt (line 3)) (0.6.2)
Requirement already satisfied: idna==3.4 in c:\users\sheik\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirments.txt (line 4)) (3.4)
Requirement already satisfied: pipreqs==0.4.11 in c:\users\sheik\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirments.txt (line 5)) (0.4.11)
Requirement already satisfied: requests==2.28.1 in c:\users\sheik\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirments.txt (line 6)) (2.28.1)
Requirement already satisfied: urllib3==1.26.13 in c:\users\sheik\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirments.txt (line 7)) (1.26.13)
Requirement already satisfied: yarg==0.1.9 in c:\users\sheik\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirments.txt (line 8)) (0.1.9)
PS C:\Users\sheik\Phoneinfoga>  python3 phoneinfoga.py -v
C:\Users\sheik\AppData\Local\Microsoft\WindowsApps\python3.exe: can't open file 'C:\\Users\\sheik\\Phoneinfoga\\phoneinfoga.py': [Errno 2] No such file or directory
PS C:\Users\sheik\Phoneinfoga>

**Comment by 53jk1** [comment]
Read first what the differences between programming languages are

**Comment by sundowndev** [comment]
You are trying to install version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.

**Comment by alazreq** [comment]
لا يمكن لـ Cp تحديد config.example.py: لا يوجد مثل هذا الملف أو المخرج #65 - GitHub‏
