### ISSUE TITLE
google cse error

### ISSUE THREAD

**Issue by b33fsup3m3** [sundowndev/phoneinfoga#1189]
console output:
 [GIN] 2023/01/12 - 00:09:05 | 500 |     530.499ms |       127.0.0.1 | POST     "/api/v2/scanners/googlecse/run
 
 web error:
 googleapi: Error 400: Request contains an invalid argument., badRequest
 
 i use it with a config.env for the api keys like this:
 
 # .env.local
NUMVERIFY_API_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxx"
GOOGLECSE_CX="https://cse.google.com/cse?cx=xxxxxxxxxxxxxxx"
GOOGLE_API_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

and that is the command i used

phoneinfoga serve --env-file=phoneinfoga.env

(with numverify it works fine but it is too less output)

**Comment by sundowndev** [comment]
The `GOOGLECSE_CX` value must be the CX only, not the full URL. e.g. `GOOGLECSE_CX="xxxxxxxxxxxxxxx"`

**Comment by b33fsup3m3** [comment]
Thanks
