### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by Walker-Anger** [sundowndev/PhoneInfoga#120]
**I ran into an issue where after completing install steps for Linux I would get the error,** 

`ModuleNotFoundError:`` No module named ``'selenium'`

**The whole message was:**

Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/PhoneInfoga/lib/googlesearch.py", line 17, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**I'm new to Linux and am trying to learn, any help is appreciated.**

**Comment by sundowndev** [comment]
Did you install requirements ?

**Comment by Walker-Anger** [comment]
don't know why I did not think about that, thank you.

**Comment by progamandoconro** [comment]
I also got an error running the Dockerfile. I remediated webddriver error
googling it but then I got a new one and could not use the program.

**Comment by sundowndev** [comment]
@progamandoconro Please open another issue and describe the problem (with errors).

**Comment by progamandoconro** [comment]
How do I open issues (first timer)? I am re running the Dockerfile and can
print the errors and share.

**Comment by progamandoconro** [comment]
@sundowndev/PhoneInfoga
<reply@reply.github.com>. I am
getting this error when running the Dockerfile ' ModuleNotFoundError: No
module named 'lib.args '. I tried with RUN pip install lib and also with
RUN pip install lib.args and nothing.

**Comment by progamandoconro** [comment]
Hello Sundowndev/Phoneinfoga, thank you for you program.

I am getting this error while running the Dockerfile

File
"/usr/local/lib/pyenv/versions/3.6.9/lib/python3.6/site-packages/selenium/webdriver/common/service.py",
line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver'
executable needs to be in PATH.

I cloned your repository and built the Dockerfile. Am I in the right path.
Thank you.

**Comment by sundowndev** [comment]
@progamandoconro It's because you need to use docker-compose in order to launch geckodriver. Geckodriver is not installed in the Dockerfile, but the tool standalone.

See https://sundowndev.github.io/PhoneInfoga/install/#using-docker
>WARNING: This image only contain the python tool and not the Selenium hub which is useful to query Google. In order to use Selenium driver, you must use the docker-compose configuration, as described below.
