### ISSUE TITLE
CLI installation fails on macOS (Darwin_arm64) if wget is not installed.

### ISSUE THREAD

**Issue by eikopf** [sundowndev/phoneinfoga#1202]
This looks like a relatively simple bug, it probably just needs a specific error message (or to try brew install wget).

**Comment by carolcake** [comment]
it's the same for x64 for mac as well

**Comment by zabukeinc** [comment]
I found solution on this case (for my usage), Try download release and select your OS type. Extract it, and then ./phoneinfoga -h. On my device, it's work.

**Comment by sundowndev** [comment]
Should be fixed now.
