### ISSUE TITLE
Your website is not working in windows or kali linux

### ISSUE THREAD

**Issue by ARYANTHEHACKER23** [sundowndev/phoneinfoga#1211]
c1. Download latest release in the current directory

     $ curl -sSL [https://raw.githubusercontent.com/sun /master/support/scripts/install | bash

   2. Install phoneinfoga

     $ sudo install ./phoneinfoga /usr/local/bin/phoneinfoga

3.Test to ensure the version you installed is up-to-date

      $ ./phoneinfoga version

1st command is not working in my kali or windows 10

**Comment by sundowndev** [comment]
Look at [the documentation](https://sundowndev.github.io/phoneinfoga/getting-started/install/#binary-installation-recommended), it's not the right commands.
