### ISSUE TITLE
Won't Install on macOS - 

### ISSUE THREAD

**Issue by Poochalowski** [sundowndev/phoneinfoga#1219]
When trying to install via terminal (on macOS - Ventura), error message keeps popping up: “phoneinfoga” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware. phoneinfoga version [v2.10.2]

Any solution to this?

**Comment by sundowndev** [comment]
We must setup a homebrew package in order to solve this. In the meantime, [you can add an exception](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac).

**Comment by DrrDino** [comment]
> When trying to install via terminal (on macOS - Ventura), error message keeps popping up: “phoneinfoga” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware. phoneinfoga version [v2.10.2]
> 
> Any solution to this?

This software is old enough and doesn’t work,I was trying to get my girlfriends phone number hacked and also get into her Facebook and Snapchat thanks to the best hacker who helped me did that reach him on telegram : https://t.me/Blackhathacker111

**Comment by sundowndev** [comment]
Phoneinfoga is now available on [homebrew](https://sundowndev.github.io/phoneinfoga/getting-started/install/#homebrew).
