### ISSUE TITLE
Add phoneinfoga to homebrew 

### ISSUE THREAD

**Issue by sundowndev** [sundowndev/phoneinfoga#1220]
*related to https://github.com/sundowndev/phoneinfoga/issues/1219*

> Since macOS only allows users to install apps from Apple-verified developers, the system will prevent you from installing a program if the developer hasn’t been registered with Apple.

MacOS users may have a security warning message saying that the program is not trustworthy:

> “phoneinfoga” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.

The solution is to release phoneinfoga on homebrew.

**Comment by Anlcanszoglu** [comment]
Yardım ios apple
