### ISSUE TITLE
Error when i try to look up a phone number

### ISSUE THREAD

**Issue by Erzxh** [sundowndev/PhoneInfoga#123]
[!] ---- Fetching informations for (phone number) ---- [!]
[*] Running local scan...
[!] Error: an error occured parsing (phone number). Skipping.

i am using windows kali linux

**Comment by sundowndev** [comment]
- What is the country code of the number ?
- Which command did you run ?

**Comment by Erzxh** [comment]
• The country code was +1 it was from the US
• The command i tan was “python3 phoneinfoga.py -n (phone number)”

**Comment by sundowndev** [comment]
Please provide the first part of the number. The exact input you used, censor the last 3 digits.
Example : `python3 phoneinfoga.py -n "+1 512-444-000"`.

**Comment by Erzxh** [comment]
python3 phoneinfoga.py -n “512-545-0000” i didn’t put the the country
number and i didn’t put any dashes or spaces between the numbers maybe
that’s why?

**Comment by sundowndev** [comment]
@Erzxh Yes, you have to put the country code in order for the tool to understand what country is it from. Simply add +1 at the beginning.

**Comment by Erzxh** [comment]
so we need to add the dashes. For example, this dash “-“?

**Comment by progamandoconro** [comment]
I got an error about being black listed by google. I am guessing needed to
edit de example.config file right? Thank you

**Comment by Erzxh** [comment]
there is a way to fix it i would recommend to watch “Null Byte” video
called “gathering information on a phone number”  because he tells you how
to fix it somewhere in the video.

**Comment by progamandoconro** [comment]
I love that video, I will check it again, sure I miss that at the moment.
Thank you.

**Comment by Erzxh** [comment]
no problem!

**Comment by sundowndev** [comment]
>so we need to add the dashes. For example, this dash “-“?

@Erzxh You don't need to put dashes but the country code is necessary.
Example : `+1512444000` is fine.

**Comment by Essandoh83** [comment]
Tried everything but still not working
Is there any tool that I have to install
