### ISSUE TITLE
The returned urls in Googlesearch social_media do not return any documents.

### ISSUE THREAD

**Issue by arielandrade** [sundowndev/phoneinfoga#1244]
**Describe the bug**
The returned urls in Googlesearch social_media do not return any documents.

**To Reproduce**
Execute ./phoneinfoga scan -n "541134975525"
or Argentina 011 15-3497-5525 by UI

**Expected behavior**
Google returns some documents when opening the social_media returned urls.
For instance:

https://www.google.com/search?q=site%3Afacebook.com+intext%3A%225491134975525%22+%7C+intext%3A%22%2B5491134975525%22+%7C+intext%3A%22091534975525%22

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/14306274/227027838-f5044a05-03ac-4d7a-90bf-0cb7dacb7848.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - PhoneInfoga exact version: 2.10.3-8b21e35

**Additional context**
Maybe the returned querystring is no longer supported by google??

**Comment by sundowndev** [comment]
Read [docs](https://sundowndev.github.io/phoneinfoga/getting-started/scanners/#googlesearch):

> This scanner does only one thing: generating several Google search links from a given phone number. You then have to manually open them in your browser to see results. So the tool may generate links that do not return any result. This is a design choice we made to avoid technical limitation around [Google scraping](https://en.wikipedia.org/wiki/Search_engine_scraping).
