### ISSUE TITLE
curl --request GET Find Information On Phone Numbers Phoneinfoga

### ISSUE THREAD

**Issue by lB2B** [sundowndev/phoneinfoga#1246]
whenever we're doing find information On Phone Numbers in Phoneinfoga and  type in the following (kali linux):
curl --request GET 'https://api.apilayer.com/number_verification/validate?number=14158586273' \ --header 'apikey: syzxxxxxxxxxxxxxxxxxxxx'

we get this message, {"message":"No API key found in request"}curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL

**Comment by sundowndev** [comment]
You're requesting the apilayer service, not phoneinfoga. Closing since it's off-topic.
