### ISSUE TITLE
Google Links not working

### ISSUE THREAD

**Issue by FusionPI** [sundowndev/phoneinfoga#1264]
I have seen other posts with issues opening links once a report is being run. I have now run into that exact problem

Your search -site:smslive.co intext:"12155899240" OR intext:"2155899240" - did not match any documents.

Now, I have 40 more of these on the same inquiry and I find it odd that not a single link is valid? 

What is the workaround, I feel the old system actually has produced usable intel, this one all I ever receive is the error above.

Please advise how I can get this correct?

**Comment by sundowndev** [comment]
> This scanner does only one thing: generating several Google search links from a given phone number. You then have to manually open them in your browser to see results. So the tool may generate links that do not return any result. This is a design choice we made to avoid technical limitation around [Google scraping](https://en.wikipedia.org/wiki/Search_engine_scraping).

> You can however, use this scanner through the REST API in addition with another tool to fetch the result automatically. If you wish to retrieve results automatically, see [Googlecse scanner](https://sundowndev.github.io/phoneinfoga/getting-started/scanners/#googlecse) instead.

See [docs](https://sundowndev.github.io/phoneinfoga/getting-started/scanners/#googlesearch).
