### ISSUE TITLE
Display problem?

### ISSUE THREAD

**Issue by VariableCreator** [sundowndev/phoneinfoga#1265]
When running a phoneinfoga scan with "phoneinfoga scan -n "number" " i get a weird output with stuff like "←[0m←[37m" before the results

![issue](https://user-images.githubusercontent.com/132523748/236336702-0b46ccce-dc78-40fd-86b8-f70be7a10998.png)

 - Windows 10
 - PhoneInfoga 2.10.4-803b64a

**Comment by sundowndev** [comment]
Hi, this has been fixed in [v2.10.5](https://github.com/sundowndev/phoneinfoga/releases/tag/v2.10.5). Would you mind give it a try?

**Comment by VariableCreator** [comment]
fixed with v2.10.5
