### ISSUE TITLE
I am using Termux and i am getting this error

### ISSUE THREAD

**Issue by Kenkenikefourt** [sundowndev/phoneinfoga#1278]
when i search for a number in phoneinfoga in termux i am getting this error.I am using redmi note 11 pro

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PhoneInfoga/./phoneinfoga.py", line 687, in <module>
    main()
  File "/data/data/com.termux/files/home/PhoneInfoga/./phoneinfoga.py", line 643, in main
    requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS

**Comment by sundowndev** [comment]
You are trying to use version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.

**Comment by ik3699890-code** [comment]
AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS
