### ISSUE TITLE
PhoneInfoga Error 

### ISSUE THREAD

**Issue by AnonCypher** [sundowndev/phoneinfoga#1281]
This script wasn't properly built, I have Python 11 and it still gives out errors when I try to run the script.
I tried another PhoneInfoga python script and it worked perfectly.

I've tried sudo ./phoneinfoga.py instead of python, python2 or python3 and still nothing.

**Comment by sundowndev** [comment]
You didn't install the project properly. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/).
