### ISSUE TITLE
stuck in setup

### ISSUE THREAD

**Issue by tubinho58** [sundowndev/phoneinfoga#1293]
I was stuck at this stage during the installation, when I searched, there should be a requirements.txt file, but I have no idea what to do, can you help me?
![Untitled](https://github.com/sundowndev/phoneinfoga/assets/137498128/3845ab2b-cafb-4d6a-91b2-aad454229f2f)

**Comment by sundowndev** [comment]
You are trying to install version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
