### ISSUE TITLE
What to do if the same comes up in PhoneInfoga

### ISSUE THREAD

**Issue by Abhinav108k** [sundowndev/phoneinfoga#1323]
![IMG_20230816_174954.jpg](https://github.com/sundowndev/phoneinfoga/assets/134203891/1ccc0af2-be61-41eb-ab15-0ac5e963c77e)

**Comment by sundowndev** [comment]
You're using version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
