### ISSUE TITLE
Error parsing (phonenumber)

### ISSUE THREAD

**Issue by RCCRAFT1** [sundowndev/PhoneInfoga#134]
There was an error looking up a phone number.
The log is below

[!] ---- Fetching informations for 8004940891 ---- [!]
[*] Running local scan...
[!] Error: an error occured parsing 8004940891. Skipping.

**Comment by sundowndev** [comment]
1. What is the country code of the number ?
2. Which command did you run ?

Please provide the first part of the number. The exact input you used, censor the last 3 digits.
Example : `python3 phoneinfoga.py -n "+1 512-444-000"`.

**Comment by RCCRAFT1** [comment]
I used the command you listed. I used a local number but but I did the whole phone number

**Comment by RCCRAFT1** [comment]
Any phone number I put in it gives me errors about parsing it

**Comment by sundowndev** [comment]
Please answer to my questions.

**Comment by RCCRAFT1** [comment]
The county code is +1
I used `python3 phoneinfoga.py -n (the whole phone number)`

**Comment by sundowndev** [comment]
Closing following this new issue https://github.com/sundowndev/PhoneInfoga/issues/135
