### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Mastershaik** [sundowndev/phoneinfoga#1340]
![Screenshot_2023-09-14-17-36-15-016_com termux](https://github.com/sundowndev/phoneinfoga/assets/145020789/24faef93-05b2-4af0-9c94-eea026db90b7)
Plz help me

**Comment by Mastershaik** [comment]
PhoneInfoga not working

**Comment by Mdfarhan143** [comment]
First download python then fix it




usse bhi nahi ho ga toh link ko cheak karna

**Comment by sundowndev** [comment]
You are trying to install version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
