### ISSUE TITLE
Traceback (most recent call last):   File "/data/data/com.termux/files/home/PhoneInfoga/./phoneinfoga.py", line 687, in <module>     main()   File "/data/data/com.termux/files/home/PhoneInfoga/./phoneinfoga.py", line 643, in main     requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'

### ISSUE THREAD

**Issue by Aman8888888** [sundowndev/phoneinfoga#1347]
**Describe the bug**
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PhoneInfoga/./phoneinfoga.py", line 687, in <module>
    main()
  File "/data/data/com.termux/files/home/PhoneInfoga/./phoneinfoga.py", line 643, in main
    requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'

**To Reproduce**
./phoneinfoga.py -n +917509228xxx

**Expected behavior**
I expected to happen phone number I entered to give me detailed information of the number.

**Screenshots (optional)**
yes i have attached screenshot.

**Desktop (please complete the following information):**
 - OS: Android 12
![Screenshot_20230929_103224](https://github.com/sundowndev/phoneinfoga/assets/146410955/d0f3dd64-9a62-4bee-ac4c-02079995e4c9)

 - PhoneInfoga version: v2.10.8

**Comment by sundowndev** [comment]
Related to version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.

**Comment by Aman8888888** [comment]
> Related to version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.

can you please give me archive link for android which i can just copy paste in termux
