### ISSUE TITLE
Docker pull latest gets old version. 

### ISSUE THREAD

**Issue by mayphilc** [sundowndev/phoneinfoga#1354]
Docker pull sundowndev/phoneinfoga:latest pulls the old v2.10.7 not 2.10.8

**Comment by sundowndev** [comment]
Upgrading node in v2.10.8 introduced a bug in Docker build which I didn't manage to solve for now. Still working on it.

**Comment by sundowndev** [comment]
Fixed in [v2.11.0](https://github.com/sundowndev/phoneinfoga/releases/tag/v2.11.0)

**Comment by Binidu01** [comment]
api is not defined
