### ISSUE TITLE
requirements.txt is missing.  

### ISSUE THREAD

**Issue by glitchbot12** [sundowndev/phoneinfoga#1386]
I'm running a wsl version of Ubuntu and I can't find the required 'requirements.txt' file in the supposed folder. It used to be there when I installed it on an older version but now it's gone from both installation methods. 

`CODEOWNERS          Dockerfile  Makefile   bin    cmd   examples  go.sum  logs     mkdocs.yml  support  web
CODE_OF_CONDUCT.md  LICENSE     README.md  build  docs  go.mod    lib     main.go  mocks       test`

I remember the file being there but is there a new way to install it now?

**Comment by sundowndev** [comment]
You are trying to install version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
