### ISSUE TITLE
downloading error - bash: /proc/self/fd/13: No such file or directory

### ISSUE THREAD

**Issue by RunRenegade** [sundowndev/phoneinfoga#1388]
**Bug / Issue**
When attempting to download the software on a Linux machine I am being given the following error; bash: /proc/self/fd/13: No such file or directory

**To Reproduce**
I simply run; `sudo bash <( curl -sSL https://raw.githubusercontent.com/sundowndev/phoneinfoga/master/support/scripts/install )`

**Expected behavior**
I believe this should give me the install file to then install globally.

**Screenshots (optional)**
Image below shows the two commands ran, did the first without `sudo`.
![Capture1](https://github.com/sundowndev/phoneinfoga/assets/6189906/c6b0c00b-dadb-42c7-93e7-8434b9713ab8)

**Desktop (please complete the following information):**
 - OS: Kali linux, release 2023.4
 - PhoneInfoga exact version - not possible

**Additional context**
Thanks in advance

**Comment by sundowndev** [comment]
Use it like this instead: `curl -sSL https://raw.githubusercontent.com/sundowndev/phoneinfoga/master/support/scripts/install | bash`

**Comment by RunRenegade** [comment]
This works now, thanks a lot.

**Comment by RunRenegade** [comment]
Closed

**Comment by craze9** [comment]
> Use it like this instead: `curl -sSL https://raw.githubusercontent.com/sundowndev/phoneinfoga/master/support/scripts/install | bash`

It’s still doesn’t work
