### ISSUE TITLE
Last step problem

### ISSUE THREAD

**Issue by sdndjejdk** [sundowndev/phoneinfoga#1391]
python3 PhoneInfoga.py -n +923123456789
python3: can't open file '/data/data/com.termux/files/home/PhoneInfoga/PhoneInfoga.py': [Errno 2] No such file or directory
This error is not going 
Plz give solution

**Comment by sundowndev** [comment]
You are trying to use version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
