### ISSUE TITLE
¿How can i fix this error?

### ISSUE THREAD

**Issue by NityamUpadhyay** [sundowndev/phoneinfoga#1392]
¿How can i fix this error?

[*] Running Numverify.com scan...
[!] Numverify.com is not available
[!] Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

_Originally posted by @NeOkC in https://github.com/sundowndev/phoneinfoga/issues/24#issuecomment-967789624_

**Comment by sundowndev** [comment]
You are trying to install version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
