### ISSUE TITLE
workaround .env file

### ISSUE THREAD

**Issue by g4ze** [sundowndev/phoneinfoga#1393]
We at https://github.com/intelowlproject/IntelOwl/pull/2107#discussion_r1482716371 are trying to implement an analyzer of `phoneinfoga` . For this, we deem it unsuitable for our framework to put in api the API keys in the .env file. Instead, it could be feasible if we can pass the api key with the request to the endpoint itself and not have it picked from the .env file.

**Comment by sundowndev** [comment]
Hi @g4ze, this could be solved by the introduction of scanner options which is basically adding support for optional parameters for existing scanners. This could be quickly implemented without breaking change and used through the API like this:

```
curl -X 'POST' \
  'http://localhost:5000/api/v2/scanners/numverify/run' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"number": "33679368229", "options": {"api_key": "secret"}}'
```

If it's not specified, the environment variable is used. Could you confirm that this would solve your case?
Thanks

**Comment by g4ze** [comment]
Thanks for the attention! So you basically you mean that we'd need change https://github.com/sundowndev/phoneinfoga/cmd/scan.go
a bit, in a way to have `ScanCmdOptions` struct include another variable? I'm not too fluent with golang but maybe i can try to raise a PR and add the functionality if you like.

**Comment by sundowndev** [comment]
No I'm talking about the REST API only, not the command line. If I understand correctly, you plan to integrate phoneinfoga in your project by using the REST API, is that right?

For this we'll need to change the scanner interface [here](https://github.com/sundowndev/phoneinfoga/blob/master/lib/remote/scanner.go#L18-L19) to accept those options. If this can wait a week or so I can take care of the changes.

**Comment by g4ze** [comment]
my bad. yes, you understood our problem well. We can wait a week or so. Please keep us updated for the same.

**Comment by sundowndev** [comment]
@g4ze I just released [v2.11.0](https://github.com/sundowndev/phoneinfoga/releases/tag/v2.11.0) which contain this new feature. Please give it a try and send us feedback. Read docs [here](https://sundowndev.github.io/phoneinfoga/getting-started/scanners/#scanner-options).

**Comment by g4ze** [comment]
works as requested, thankyou very much

**Comment by sundowndev** [comment]
Cool! After reviewing your PR, I suggest that you use a fixed docker tag, instead of using the `latest` tag ([here](https://github.com/intelowlproject/IntelOwl/blob/develop/integrations/phoneinfoga/compose.yml#L7)) because it could lead to breaking change when we release v3 for example. You can use the `v2` tag as well.

Anyway, I can close this one.

**Comment by g4ze** [comment]
hmm, makes sense. Thankyou for the suggestion :3 !

**Comment by brandenmullin2-maker** [comment]
> Hi [@g4ze](https://github.com/g4ze), this could be solved by the introduction of scanner options which is basically adding support for optional parameters for existing scanners. This could be quickly implemented without breaking change and used through the API like this:
> 
> ```
> curl -X 'POST' \
>   'http://localhost:5000/api/v2/scanners/numverify/run' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: application/json' \
>   -d '{"number": "4705997369", "options": {"api_key": "secret"}}'
> ```
> 
> If it's not specified, the environment variable is used. Could you confirm that this would solve your case? Thanks
