### ISSUE TITLE
Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.

### ISSUE THREAD

**Issue by Mark8811188** [sundowndev/phoneinfoga#1395]
Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library?

[ i] Searching for documents... (Limit=10)

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a

parser Library?

[i] Reputation footprints [i] Searching for reputation report on whosenumber.info....

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a

parser Library?

[ 1] Searching for phone fraud footprints...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library?

[i] Searching for reputation report on findwhocallsme.com.

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a

parser Library?

[i] Searching for reputation report on yellowpages.ca...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library?

[i] Searching for reputation report on phonenumbers.ie...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library?

[i] Searching for reputation report on who-calledme.com...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.

Couldn't find a tree builder with the features you requested: html5lib. Do you need to install

parser Library? [I] Searching for reputation report on usphonesearch.net...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.

Couldn't find a tree builder with the features you requested: html5lib. Do you need to install

parser Library? for reputation report on whocalled.us....

[i] Searching

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install

parser Library?

[i] Searching for reputation report on quinumero.info...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library?

[i ] Searching for reputation report on uk.popularphotolook.com...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a

parser Library?

[ i] Generating URL on scamcallfighters.com...

[-] http://www.scamcallfighters.com/search-phone-380658160005.html

Would you like to search for temporary number providers footprints ? (Y/n) n

[i]Social media footprints

[ i] Searching for footprints on facebook.com...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.

Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser library?

[i] Searching for footprints on twitter.com...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.

Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library? [i] Searching for footprints on Linkedin.com...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library?

[i] Searching for footprints on instagram.com..

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a

parser Library?

[i]Phone books footprints-

[ i] Searching for footprints on numinfo.net...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.

Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a

parser Library? [1] Searching for footprints on sync.me...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.

Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a

parser Library? [i] Searching for footprints on whocallsyou.de...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library? [i] Searching for footprints on pastebin.com...

Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5Lib. Do you need to install a

parser Library? i] Searching for footprints on whycall.me...

[ Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a

parser Library?

[i] Searching for footprints on locatefamily.com... Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga. Couldn't find a tree builder with the features you requested: html5lib. Do you need to install

**Comment by sundowndev** [comment]
You're using version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
