### ISSUE TITLE
where do i put the .env file created for phoneinfoga

### ISSUE THREAD

**Issue by scorpioqueenlove** [sundowndev/PhoneInfoga#1401]
I created the env file for phoneinfoga. where in the folder do i put it so it can work?

**Comment by sundowndev** [comment]
In the current directory, when running the program.

**Comment by scorpioqueenlove** [comment]
> In the current directory, when running the program.

what does that mean. I put it in the directory, ran the program and all I see is 2 scanners

**Comment by sundowndev** [comment]
It would be simplier to help if you could provide the commands used

**Comment by scorpioqueenlove** [comment]
> It would be simplier to help if you could provide the commands used

phoneinfoga scan -n xxxxxxxxxx

**Comment by scorpioqueenlove** [comment]
I also tried this phoneinfoga scan -n +4176418xxxx --env-file=.env.local
and its still not workng
