### ISSUE TITLE
What is the following problem?

### ISSUE THREAD

**Issue by Hashem7181** [sundowndev/PhoneInfoga#1406]
using '/dev/dvb/adapter0/frontend0' and '/dev/dvb/adapter0/demux0'
main:2745: FATAL: failed to open '/dev/dvb/adapter0/frontend0': 2 No such file or directory

**Comment by sundowndev** [comment]
Whatever it is, it's not related to this project.

**Comment by Hashem7181** [comment]
Well what is the solution?

‫في الأربعاء، 20 مارس 2024 في 10:20 م تمت كتابة ما يلي بواسطة ‪Raphaël‬‏ <‪
***@***.***‬‏>:‬

**Comment by Hashem7181** [comment]
what does that mean


‫في الأربعاء، 20 مارس 2024 في 10:20 م تمت كتابة ما يلي بواسطة ‪Raphaël‬‏ <‪
***@***.***‬‏>:‬
