### ISSUE TITLE
Requirements.txt file missing.

### ISSUE THREAD

**Issue by Zookstar** [sundowndev/PhoneInfoga#1414]
So, when I tried installing PhoneInfoga in Kali Linux (VirtualBox), I didn’t know that there isn’t a requirements.txt file. How do I install Phoneinfoga without the requirements.txt file? And why isn’t the requirements.txt file there in the latest Phoneinfoga version?

Thanks.

**Comment by bilawalbiloo74** [comment]
I also having face that issue anybody know the answer of that query?

**Comment by sundowndev** [comment]
[Read The Fancy Manual](https://sundowndev.github.io/phoneinfoga/getting-started/install/)
