### ISSUE TITLE
A critical error 

### ISSUE THREAD

**Issue by ZorvWolf** [sundowndev/PhoneInfoga#1415]
**A Random error **
It's saying Please open a issue in GitHub 

**To Reproduce**
phoneinfoga.py -n ********** --osinst

**Expected behavior**
Nothing 

**Screenshots (optional)**
![Screenshot_20240422-205220_Termux](https://github.com/sundowndev/phoneinfoga/assets/157914555/6a7a383b-ab2d-443b-bde2-1a921d3e6271)

**Desktop (please complete the following information):**
 - OS: Termux Android 
 - PhoneInfoga exact version: v1.0.2
 - Go exact version (if running it with Go) (run `go version`)...

**Additional context**

**Comment by sundowndev** [comment]
You are using version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.

**Comment by ZorvWolf** [comment]
Ye sorry btw it was fixed
