### ISSUE TITLE
Temperory Blacklist

### ISSUE THREAD

**Issue by jisjose98** [sundowndev/PhoneInfoga#143]
You are temporary blacklisted from Google search. Complete the captcha then press ENTER.

**Comment by sundowndev** [comment]
You have to complete the Google captcha using Selenium. A Firefox window should pop up with the captcha page. What's the exact issue here ?

**Comment by jisjose98** [comment]
Actually after a while the recaptcha complete option appears.Then I
verified it  but it asked recaptcha continuously like a loop

**Comment by sundowndev** [comment]
After completing the captcha for a while, do you manage to get the tool working ? Or is the loop never ending ?

**Comment by jisjose98** [comment]
Loop continued about 20times of successful completion later I quited

**Comment by sundowndev** [comment]
Are you using a VPN, Proxy or such thing ? Are you able to search on Google manually ?

>It probably means Google's assigning you to a very low human score, that's the reason sometime you can solve the captcha in one-shot, and sometime having 10 tries before solving it.

See https://github.com/sundowndev/PhoneInfoga/issues/126#issuecomment-531869062

**Comment by Rosanna11235813213455** [comment]
hi. what if there's no pop up Firefox window?

**Comment by jisjose98** [comment]
Sorry i didnt get u

**Comment by sundowndev** [comment]
@Rosanna11235813213455 Please give further informations, what command did you run ? What output do you have in your terminal ?

**Comment by jisjose98** [comment]
Yup i will by last week

**Comment by Rosanna11235813213455** [comment]
> @Rosanna11235813213455 Please give further informations, what command did you run ? What output do you have in your terminal ?

I ran docker-compose version and after message about blocking there was no Firefox with captcha challenge, but manually installed version (with last Firefox and Geckodriver preinstalled according to instruction) works good. So sorry for troubling and thank you for tool :)

**Comment by sundowndev** [comment]
@Rosanna11235813213455 You have to use a VNC client to access Firefox window through Docker. Please read documentation https://sundowndev.github.io/PhoneInfoga/googlesearch/#using-docker.

**Comment by sumo2001** [comment]
After completion of captcha, it is going for a manual search on google replying with no results found and looping with "You are temporarily blacklisted from Google search. Complete the captcha then press ENTER." on terminal

**Comment by bairdj4** [comment]
Yea, I'm also getting a near endless loop of a ton of blacklists and captchas. Kinda makes the tool a PITA to use if I have to identify 50 bicycles, traffic lights and crosswalks.. Any fix for this?

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).

**Comment by arjunsingh0** [comment]
Phoneinfoga gave no more info than country to which the number belongs !!
How do i get call logs ??

**Comment by Harley8281** [comment]
You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie     how to fix this bro.......i tried more than  30 times to complete the captcha but when one captcha completes another will open like a loop please help me :(

**Comment by dharmendrasharma4** [comment]
You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie how to fix this bro.......i tried more than 30 times to complete the captcha but when one captcha completes another will open like a loop please help me :(
