### ISSUE TITLE
NameError: name 'google_api_key' is not defined

### ISSUE THREAD

**Issue by endbehavi0r** [sundowndev/PhoneInfoga#149]
root@end0:/opt/phoneinfoga# python3 phoneinfoga.py -n +447856424610
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev

[!] ---- Fetching informations for 447856424610 ---- [!]
[*] Running local scan...
[+] International format: +44 7856 424610
[+] Local format: 7856424610
[+] Country found: United Kingdom (+44)
[+] City/Area: United Kingdom
[+] Carrier: O2
[+] Timezone: Europe/Guernsey
[+] Timezone: Europe/Isle_of_Man
[+] Timezone: Europe/Jersey
[+] Timezone: Europe/London
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+44) 07856424610
[+] Country: United Kingdom of Great Britain and Northern Ireland (GB)
[+] Location: 
[+] Carrier: Telefonica UK Ltd
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[i] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/44-7856-424610
Would you like to use an additional format for this number ? (y/N) 
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/opt/phoneinfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/opt/phoneinfoga/lib/googlesearch.py", line 28, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

**Comment by sundowndev** [comment]
You have to create the config file. Please read documentation.
