### ISSUE TITLE
Script crashes at tempophone footprint scan

### ISSUE THREAD

**Issue by mifkilla** [sundowndev/PhoneInfoga#15]
ive got script crush. Everything properly installed.
└──╼ $python3 phoneinfoga.py -n +XXXXXXXXXX --osint
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.0.0-rc2
 Coded by Sundowndev

[!] ---- Fetching informations for XXXXXXXXXX ---- [!]
[*] Running local scan...
[+] International format: +XXXXXXXXXX
[+] Local format: XXXXXXXXXX
[+] Country code: +7
[+] Location: Russia
[+] Carrier: 
[+] Area: Russia
[+] Timezone: Asia/Almaty
[+] Timezone: Asia/Anadyr
[+] Timezone: Asia/Aqtobe
[+] Timezone: Asia/Irkutsk
[+] Timezone: Asia/Kamchatka
[+] Timezone: Asia/Krasnoyarsk
[+] Timezone: Asia/Magadan
[+] Timezone: Asia/Novosibirsk
[+] Timezone: Asia/Omsk
[+] Timezone: Asia/Sakhalin
[+] Timezone: Asia/Vladivostok
[+] Timezone: Asia/Yakutsk
[+] Timezone: Asia/Yekaterinburg
[+] Timezone: Europe/Bucharest
[+] Timezone: Europe/Moscow
[+] Timezone: Europe/Samara
[*] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+7) XXXXXXXXXX
[+] Country: Russian Federation (RU)
[+] Location: Moscow and Moscow Oblast
[+] Carrier: PJSC Mobile TeleSystems (MTS)
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[*] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/7-985-256-85-41
[*] Would you like to use an additional format for this number ? (y/N) 
[*] ---- Web pages footprints ----
[*] Searching for footprints on web pages... (limit=5)
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=XXXXXXXXXX | intext:"XXXXXXXXXX" | intext:"+7 XXXXXXXXXX"&amp;gws_rd=ssl

[*] Need help ? Read https://github.com/sundowndev/PhoneInfoga#dealing-with-google-captcha

GOOGLE_ABUSE_EXEMPTION=ID=4acce7af470032e7:TM=1545779707:C=r:IP=xx.xx.xx.xx-:S=APGng0vBztSQorsxbOPfJO48MDlc_hosaQ
[+] Result found: http://89xx.ru/nomer/798525685
[+] Result found: https://kto-abonent.com/79852560000
[+] Result found: http://ktozvonit-985-256.cdlaw.ru/
[+] Result found: https://tel-search.ru/num_ranges/64865%3Fpage%3D738
[+] Result found: http://bazanomera.ru/9852568
[*] Searching for documents... (limit=10)
[*] ---- Reputation footprints ----
[*] Searching for reputation report on whosenumber.info...
[*] Searching for phone fraud footprints...
[*] Generating URL on scamcallfighters.com...
[+] http://www.scamcallfighters.com/search-phone-XXXXXXXXXX.html
[*] Would you like to search for temporary number providers footprints ? (Y/n) 
[*] ---- Temporary number providers footprints ----
[*] Searching for phone number on tempophone.com...
Traceback (most recent call last):
  File "phoneinfoga.py", line 568, in <module>
    scanNumber(args.number)
  File "phoneinfoga.py", line 535, in scanNumber
    osintScan()
  File "phoneinfoga.py", line 488, in osintScan
    data = json.loads(response.content)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sundowndev** [comment]
Seems like a (temporary) non-response from tempophone.com's API. Did you tried again since ?

If yes, can you switch to develop branch and try again ? Thanks
