### ISSUE TITLE
enviroment error

### ISSUE THREAD

**Issue by PatrickG123** [sundowndev/PhoneInfoga#150]
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/requirements-txt/

**Comment by sundowndev** [comment]
What command did you run ? You're not supposed to install a package named "requirements-txt".

**Comment by PatrickG123** [comment]
I cloned it, how am I supposed to start it up.. When I try 'python
phoneinfoga.py', all am getting is import error.

**Comment by sundowndev** [comment]
Read documentation https://sundowndev.github.io/PhoneInfoga/install/.
