### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by chrisWalker11** [sundowndev/PhoneInfoga#151]
___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev

[!] ---- Fetching informations for 1301xxxxxx ---- [!]
[*] Running local scan...
[+] International format: +1 30xxxxxxx
[+] Local format: 301xxxxxxx
[+] Country found: United States (+1)
[+] City/Area: Maryland
[+] Carrier: 
[+] Timezone: America/New_York
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+1) 301xxxxxxx
[+] Country: United States of America (US)
[+] Location: Wshngtnzn2
[+] Carrier: AT&T Mobility LLC
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running custom format reconnaissance...
[i] Footprint reconnaissance for XXXXXXXXX
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/home/chris/Downloads/Builds/TOOLS/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/chris/Downloads/Builds/TOOLS/PhoneInfoga/lib/googlesearch.py", line 28, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined
[chris@MacBook PhoneInfoga]$ python3 phoneinfoga.py -n +1301xxxxxxx -s -footprints
usage: phoneinfoga.py -n <number> [options]
phoneinfoga.py: error: argument -s/--scanner: expected one argument
[chris@MacBook PhoneInfoga]$ python3 phoneinfoga.py -n +1301xxxxxxxx -s -footprint
usage: phoneinfoga.py -n <number> [options]
phoneinfoga.py: error: argument -s/--scanner: expected one argument
[chris@MacBook PhoneInfoga]$ python3 phoneinfoga.py -n +1301xxxxxxxx

**Comment by sundowndev** [comment]
Read documentation https://sundowndev.github.io/PhoneInfoga/install/.
