### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by Milestheotherone** [sundowndev/PhoneInfoga#152]
I got a Traceback Error that says

>File  phoneinfoga.py, line 17 in <module>
  from lib.googlesearch import closeBrowser
File C:\Users\Miles\PhoneInfoga\lib\googlesearch.py line 15
from config import
ModuleNotFoundError: No module named 'config'

**Comment by DiamoondWolf** [comment]
**Take a look here:**
https://sundowndev.github.io/PhoneInfoga/install/

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
