### ISSUE TITLE
Termux module not found error

### ISSUE THREAD

**Issue by darkdebo** [sundowndev/PhoneInfoga#155]
While I try to execute the command I got importerror parse module not found.

**To Reproduce**
python2 phoneinfoga.py
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 11, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse

I expected that it will run correctly.

 - OS: android
 - Python 2.7

**Comment by sundowndev** [comment]
PhoneInfoga was not made to run on Termux.

But in this case, it seems you didn't install the project properly. Did you [read documentation](https://sundowndev.github.io/PhoneInfoga/install/) ?

**Comment by darkdebo** [comment]
Yes previously it run successfully ,I install for it android before but now it can't run.

**Comment by darkdebo** [comment]
Thanks for reply I try it with python3 and it run successfully!thanks for the help.
