### ISSUE TITLE
Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Sahan0710** [sundowndev/PhoneInfoga#156]
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/root/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by sundowndev** [comment]
Hi, thanks for opening an issue! 👋

It seems you didn't installed geckodriver properly. Did you follow the [install instructions](https://sundowndev.github.io/PhoneInfoga/install/#install-the-geckodriver) ?

>This tool uses Firefox. So you now need to download the [geckodriver](https://github.com/mozilla/geckodriver). This driver is necessary to communicate between your installed browser and Selenium (a package used by PhoneInfoga).

You can verify Firefox and geckdriver are installed correctly by typing `which firefox` and `which geckodriver` in your terminal.

Please answer to these questions : 

1. Are you using Docker ? If no, what is your OS ? (`uname -a` for Linux/MacOS users)
2. What command did you run ?
3. Do you have the latest version of Firefox installed ?
4. Do you have the latest version of geckodriver installed ? (try `geckodriver --version`)

*Note that this tool is not tested under any version of Windows and I don't guarantee it will work properly on it.*

**Comment by kopilim96** [comment]
Hi there, I have the same issue as well, 
for the question you asked (as above),

1. I am not using Docker, my os is Kali Linux -->> 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux
2. Command that i run is `python3 phoneinfoga.py -n 60105653762`
3. My Firefox version is 60.6.2esr(64-bit)
4. My geckodriver version -->> geckodriver 0.24.0 ( 2019-01-28)

**Comment by sundowndev** [comment]
@kopilim96 Please don't disclose phone numbers entirely.
- Whats the output of `which firefox` and `which geckodriver` in your terminal ?
- Consider updating to Firefox 70 and Geckodriver 0.26.0
- Do you have any log file created by Selenium/Geckodriver locally ?

**Comment by kopilim96** [comment]
Which firefox --> `usr/bin/firefox`
Which geckodriver --> `usr/bin/geckodriver`

Somehow the log file i am not sure. Where can i look for it ?

**Comment by sundowndev** [comment]
@kopilim96 It should be at the root of the repository. Something like `geckodriver.log`.

**Comment by kopilim96** [comment]
Sorry for been late reply due to traveling oversea.

after i check on my `geckodriver.log` file the log shows that it is unable to run as root
somehow i switch to other user, but i got another issue:

    Traceback (most recent call last):
    File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
    File "/root/Downloads/PhoneInfoga/lib/googlesearch.py", line 17, in <module>
    from selenium import webdriver
    ModuleNotFoundError: No module named 'selenium'

How can I fix that ?

**Comment by kopilim96** [comment]
After i upgrade the `geckodriver` , it is working fine now. 
Somehow while executing, the f*cking non-stop robot check on the web browser feel sick to me. Damn Sh*T

**Comment by sundowndev** [comment]
@kopilim96 Well done. About the re-captcha, you can eventually bypass the block by setting up a rotating proxy. However, I don't provide any guide to achieve that.

**Comment by jepunband** [comment]
@sundowndev 
im using firefox 70 and geckodriver 0.26.0 , same issue..Unable to find a matching set of capabilities

**Comment by azamet90** [comment]
same here gecko drivers is installed but not working

**Comment by Sahan0710** [comment]
I re-installed and it worked! Thanks Guys!

**Comment by azamet90** [comment]
> I re-installed and it worked! Thanks Guys!

pls dont close the topic because i still have the same problem

**Comment by jepunband** [comment]
Tried different ver of firefox binaries and geckodriver...nothing worked. Same problem
