### ISSUE TITLE
no info about social media

### ISSUE THREAD

**Issue by lucifer-top** [sundowndev/PhoneInfoga#160]
the scan does'nt pick up info about the phone  number from social media even though the number is registered in FB and instagram id's

**Comment by sundowndev** [comment]
Does it have footprints ? What do you mean by "the number is registered in FB and instagram id's" ? This tool does not scrape Facebook or Instagram, it only searches through Google results.

**Comment by lucifer-top** [comment]
oh... sorry . my bad. Thank you. Can you please tell me in brief how does one leave a footprint in social media ?

**Comment by sundowndev** [comment]
The phone number has to be indexed on Google, from a Facebook/Instagram post or whatever. It simply has to be written somewhere on a public page.

**Comment by saidjs** [comment]
When I try to clone it tels me I have to sing in how will I do pls

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
