### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION=

### ISSUE THREAD

**Issue by jepunband** [sundowndev/PhoneInfoga#162]
**Describe the bug**
No Captcha Shown on the on visiting the link for "GOOGLE_ABUSE_EXEMPTION="

**To Reproduce**
sudo python3 phoneinfoga.py -n 431610600 --recon

**Expected behavior**
Should see the captcha on browser.

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: Parrot Os
 - Python exact version: 2.7.17 & 3.7.4+
-  PhoneInfoga: 1.6

**Additional context**
[!] ---- Fetching informations for 431610600 ---- [!]
[*] Running local scan...
[+] International format: +43 1 610600
[+] Local format: 1610600
[+] Country found: Austria (+43)
[+] City/Area: Vienna
[+] Carrier: 
[+] Timezone: Europe/Vienna
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+43) 01610600
[+] Country: Austria (AT)
[+] Location: Wien
[+] Carrier: 
[+] Line type: landline
(!) This is most likely a landline, but it can still be a fixed VoIP number.
[*] Running OVH scan...
[*] Running custom format reconnaissance...
Footprint reconnaissance for +4301610600
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=%22%2B4301610600%22&amp;gws_rd=ssl&amp;gl=us
[i] Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=

-----------------------------------------------------------------------------------------------------------------

The reason i'm using an older version of PhoneInfoga is because the current version throws a completely different error : 

[i] Footprint reconnaissance for +4301610600
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/home/modus/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/modus/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

some added info:

$which firefox
/usr/bin/firefox

$which geckodriver
/usr/local/bin/geckodriver

$firefox -v
Mozilla Firefox 69.0

Have both installed. How to solve this ? Thank you.

**Comment by sundowndev** [comment]
Hi, this version of PhoneInfoga contains a bug with Google captcha handling. That's the reason why we moved to the Selenium/Geckodriver solution.

**Comment by jepunband** [comment]
Selenium/geckodriver has errors like stated above.

**Comment by jepunband** [comment]
so i tried to do this ..

from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

capabilities = webdriver.DesiredCapabilities().FIREFOX
capabilities["marionette"] = False
binary = FirefoxBinary(r'/usr/firefox/firefox')
driver = webdriver.Firefox(firefox_binary=binary, capabilities=capabilities)


firefox opens but it gives a different error:

Traceback (most recent call last):
  File "phoneinfoga.py", line 101, in <module>
    main()
  File "phoneinfoga.py", line 77, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 43, in scanNumber
    recon.scan(number)
  File "/home/ally/gits/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/ally/gits/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 191, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 73, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 104, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by sundowndev** [comment]
Do you have any `geckodriver.log` or such file in the directory ?

**Comment by jepunband** [comment]
no

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).

**Comment by sushilkumar-mali** [comment]
Issue GOOGLE_ABUSE_EXEMPTION=

**Comment by debbborah** [comment]
> Hi 👋
> 
> Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).

Hello, I have the same problem, but I have to use a python-based version.
If the google error persists I would rather exchange the search engines, would you think it generally possiblel to make it work with duckduckgo instead of google, or is it a fundamental issue I didn't think about.

**Comment by sundowndev** [comment]
Hi @debbborah, the python version is not supported anymore and thus will not receive any update from me. Feel free to fork and maintain it yourself. You will need to rollback to tag v1.11.

**Comment by NorbertKruz** [comment]
Where i can find solve topi to that problem, please link me
