### ISSUE TITLE
Not sure if I did something wrong?

### ISSUE THREAD

**Issue by MansNeedsANap** [sundowndev/PhoneInfoga#163]
Issue:
Issue continuing the ----> python3 phoneinfoga.py -n (number) command.

Command:
python3 phoneinfoga.py -n (number) command

![image](https://user-images.githubusercontent.com/58650960/70387501-b497c480-1973-11ea-8759-47b5af1b3626.png)

 - OS: ParrotOS
 - Python 3.6.9

**Comment by sundowndev** [comment]
Hi, thanks for opening an issue! 👋

It seems you didn't installed geckodriver properly. Did you follow the [install instructions](https://sundowndev.github.io/PhoneInfoga/install/#install-the-geckodriver) ?

>This tool uses Firefox. So you now need to download the [geckodriver](https://github.com/mozilla/geckodriver). This driver is necessary to communicate between your installed browser and Selenium (a package used by PhoneInfoga).

You can verify Firefox and geckdriver are installed correctly by typing `which firefox` and `which geckodriver` in your terminal.

Please answer to these questions : 

1. Are you using Docker ? If no, what is your OS ? (`uname -a` for Linux/MacOS users)
2. What command did you run ?
3. Do you have the latest version of Firefox installed ?
4. Do you have the latest version of geckodriver installed ? (try `geckodriver --version`)
5. Do you have a `geckodriver.log` or such file in the repository ? Can you paste its content here ?

*Note that this tool is not tested under any version of Windows and I don't guarantee it will work properly on it.*

**Comment by azamet90** [comment]
> Hi, thanks for opening an issue! wave
> 
> It seems you didn't installed geckodriver properly. Did you follow the [install instructions](https://sundowndev.github.io/PhoneInfoga/install/#install-the-geckodriver) ?
> 
> > This tool uses Firefox. So you now need to download the [geckodriver](https://github.com/mozilla/geckodriver). This driver is necessary to communicate between your installed browser and Selenium (a package used by PhoneInfoga).
> 
> You can verify Firefox and geckdriver are installed correctly by typing `which firefox` and `which geckodriver` in your terminal.
> 
> Please answer to these questions :
> 
>     1. Are you using Docker ? If no, what is your OS ? (`uname -a` for Linux/MacOS users)
> 
>     2. What command did you run ?
> 
>     3. Do you have the latest version of Firefox installed ?
> 
>     4. Do you have the latest version of geckodriver installed ? (try `geckodriver --version`)
> 
>     5. Do you have a `geckodriver.log` or such file in the repository ? Can you paste its content here ?
> 
> 
> _Note that this tool is not tested under any version of Windows and I don't guarantee it will work properly on it._

i did do everything what i have to do after because of it still not works i did open issue but marked as duplicate :D

**Comment by MaulanaDK** [comment]
i have the same problem sir

**Comment by azamet90** [comment]
> i have the same problem sir

it needs to be updated

**Comment by sundowndev** [comment]
@MaulanaDK Hi, could you please give me the output of `which geckodriver` and `which firefox` ?
You can try setting up your Firefox paths manually in the config file (you may have to update the tool to get the new `config.example.py` file).

**Comment by MaulanaDK** [comment]
here is bro, can you help me ?
[image: screenshot_phoneinfoga.png]

**Comment by MaulanaDK** [comment]
like this sir ?

**Comment by MaulanaDK** [comment]
i still get eror

**Comment by MaulanaDK** [comment]
sir ?

**Comment by sundowndev** [comment]
Your screenshot is not working @MaulanaDK

**Comment by MaulanaDK** [comment]
![screenshot_phoneinfoga](https://user-images.githubusercontent.com/39475403/71716183-74c6de80-2e46-11ea-9c0e-05f3ce16fc3d.png)

**Comment by MaulanaDK** [comment]
![screenshot_phoneinfoga2](https://user-images.githubusercontent.com/39475403/71716197-7ee8dd00-2e46-11ea-8298-ac11873a75ab.png)

**Comment by MaulanaDK** [comment]
![screenshot_phoneinfoga_2](https://user-images.githubusercontent.com/39475403/71716243-9de76f00-2e46-11ea-9142-39bf2a3d5769.png)

**Comment by MaulanaDK** [comment]
still get eror sir @sundowndev

**Comment by azamet90** [comment]
maltego is working better then this and this tool have errors many tools is using gecko drivers but only this tool is doing problems and it looks like they cannot fix it why you still fighting :D

**Comment by MaulanaDK** [comment]
@azamet90 tq bro

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
