### ISSUE TITLE
not really a bug but the service cost money for scans bummer ..oh well still worth it

### ISSUE THREAD

**Issue by boombaklot** [sundowndev/PhoneInfoga#169]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - Python exact version (run `python --version`)

**Additional context**

**Comment by sundowndev** [comment]
:thinking:
