### ISSUE TITLE
API key not defined?

### ISSUE THREAD

**Issue by Mr-M1** [sundowndev/PhoneInfoga#176]
Believed to have installed correctly however when I run a number, footprints returns 

`NameError: name 'google_api_key' is not defined`
![Screenshot at 2019-12-21 22-57-58](https://user-images.githubusercontent.com/59106505/71316854-64c1fe80-2445-11ea-9b29-b3fee204530b.png)

**Comment by sundowndev** [comment]
You didn't install the project properly. Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/).

**Comment by sundowndev** [comment]
You have to create the config file https://sundowndev.github.io/PhoneInfoga/install/#create-the-config-file

**Comment by krishnavenikv** [comment]
How to clear this
