### ISSUE TITLE
Webside does not show results.

### ISSUE THREAD

**Issue by scarbear06** [sundowndev/PhoneInfoga#191]
Result found: https://www.whitepages.com/phone/
[+] Result found: https://www.truepeoplesearch.com/find
[+] Result found: https://www.truepeoplesearch.com/find/
[+] Result found: https://www.familytreenow.com/records/people/bond/                                                                     
[+] Result found: https://www.searchpeoplefree.com/phone-lookup/                                                                          
[+] Result found: https://www.searchpeoplefree.com/phone-lookup/                                                                          
[+] Result found: https://www.fastpeoplesearch.com/address/135-chilton-hall-apt-b1_elizabeth-nj-07202                                                 
[+] Result found: https://shouji.supfree.net/cat.asp?dog=1830534&page=2
[+] Result found: https://www.peoplelooker.com/people-search/amy-bond/tx/
[+] Result found: https://www.callersmart.com/TX/Ecleto/

all this results comes back with errors.

**Comment by sundowndev** [comment]
Can you explain it in more detail? What does "results with errors" means ?

**Comment by scarbear06** [comment]
site:quinumero.info "512-369-3232" OR "+1 512-369-3232" OR "512-369-3232"
site:whocalled.us inurl:"512-369-3232" OR "512-369-3232"
Your search - site:who-calledme.com "15123693232" OR "512-369-3232" - did not match any documents. Reset search tools
Your search - (ext:doc OR ext:docx OR ext:odt OR ext:pdf OR ext:rtf OR ext:sxw OR ext:psw OR ext:ppt OR ... - did not match any documents. Reset search tools

**Comment by sundowndev** [comment]
No result means there's **no result**. This is not an error, I don't understand what you're trying to point out.

Also please don't disclose phone numbers here.

**Comment by scarbear06** [comment]
i think the site:whocalled.us inurl:.  has to to be fix.  if I use www.whocalled.us it works. 
www.who-calledme.com it works too.

**Comment by igotyou22** [comment]
sir someone did the same  la-deep-web /Phoneinfoga .. and it works very well. I need to try to use at local ph. mostly runs international phones. thanks please close it

**Comment by sundowndev** [comment]
>sir someone did the same la-deep-web /Phoneinfoga .. and it works very well.

@igotyou22 I don't understand a word.

**Comment by sunny531** [comment]
Sir Web pages footprints ar not generating

[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 1700, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 101, in <module>
    main()
  File "phoneinfoga.py", line 77, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 40, in scanNumber
    osintScan(number)
  File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

$

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).

**Comment by scavngr4tech** [comment]
No he's most certainly right it does not work I have searched 12 different numbers and they all come back the same way zero results on everything

**Comment by scavngr4tech** [comment]
I've watched three different how to videos and I keep getting this issue with an API and OHV error
