### ISSUE TITLE
Issue while using python3 phoneinfoga.py -v command

### ISSUE THREAD

**Issue by WhiteSkyAngel** [sundowndev/PhoneInfoga#192]
**Describe the bug**
Can't use phoneinfoga.py (Check screen for the error)

**To Reproduce**
python3 phoneinfoga.py -n 
python3 phoneinfoga.py -v

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/44341346/73486149-d4ac9880-43a4-11ea-8591-2da6e4be19a2.png)
![image](https://user-images.githubusercontent.com/44341346/73486223-fc036580-43a4-11ea-9269-bf56998b1c6c.png)

**Desktop (please complete the following information):**
 - OS: [Screen ]
 - Python exact version (Python 2.7.17)

**Additional context**
That's all

**Comment by Salasranthony** [comment]
Same exact problem. I have all the dependencies installed. Not sure what is wrong.

**Comment by sundowndev** [comment]
You installed dependencies using pip for Python 2.7, then use Python 3 to launch the tool. This can't work. Install dependencies using pip3, you can ensure you use Python3 by using pip that way: `python3 -m pip install -r requirements.txt`

**Comment by Salasranthony** [comment]
@sundowndev Worked! thanks!

**Comment by nlaymane** [comment]
after install  this:
`script python3 -m pip install -r requirements.txt`

and use this script:
 pythone3 phoneinfoga -n of -v ...

gives me that error:
python3 can't open file 'Phoneinfoga.py' errno 2 no such file or directory

I can't find a solution

**Comment by sundowndev** [comment]
@nlaymane Please follow official documentation : https://sundowndev.github.io/PhoneInfoga/install/. Since version 2.x you don't need Python anymore.
