### ISSUE TITLE
Config file error

### ISSUE THREAD

**Issue by jigsaw678** [sundowndev/PhoneInfoga#196]
python3 phoneinfoga.py -n +90xxxxxxxxxx
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.12
 Coded by Sundowndev

[!] The config file does not exist. Please create it.

**Comment by sundowndev** [comment]
>The config file does not exist. Please create it.

I think the error message is explicit enough, right?

**Comment by sundowndev** [comment]
https://sundowndev.github.io/PhoneInfoga/install/#create-the-config-file
