### ISSUE TITLE
I tried to install Phoneinfoga to Python and it says Invalid syntax 

### ISSUE THREAD

**Issue by mindovermatter0000** [sundowndev/PhoneInfoga#197]
**Describe the bug**
-I downloaded the latest version of Python and pip, now i am trying to install Phoneinfoga do it but i keep getting " invalid syntax" when i do.  I have tried it in the command of my pc and the python command

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
