### ISSUE TITLE
Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by gonzo28** [sundowndev/PhoneInfoga#199]
I get this error message when running a phone number search:
`selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process`

which firefox: `/usr/bin/firefox`
which geckodriver: `/usr/bin/geckodriver`

Are you using Docker? No.
`Linux parrot 5.4.0-3parrot1-amd64 #1 SMP Parrot 5.4.13-3parrot2 (2020-02-01) x86_64 GNU/Linux`
What command did you run?
`python3 phoneinfoga.py -n number`
Do you have the latest version of Firefox installed?
`Version 73.0`
Do you have the latest version of geckodriver installed? 
`geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)`

Edit: The error comes after I say no when asked if I want to use an additional format. So the initial scan runs as expected.

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
