### ISSUE TITLE
No OSINT MODE !!!!!!!!!!!

### ISSUE THREAD

**Issue by xfyles** [sundowndev/PhoneInfoga#206]
optional arguments:
  -h, --help            show this help message and exit
  -n number, --number number
                        The phone number to scan (E164 or international
                        format)
  -i input_file, --input input_file
                        Phone number list to scan (one per line)
  -o output_file, --output output_file
                        Output to save scan results
  -s scanner, --scanner scanner
                        The scanner to use
  --recon               Launch custom format reconnaissance
  --no-ansi             Disable colored output
  -v, --version         Show tool version

Why not OSINT MODE?

**Comment by sundowndev** [comment]
Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/).
