### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by sumo2001** [sundowndev/PhoneInfoga#213]
My uname -a goes like this
$uname -a
Linux allmight 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux
 
$./phoneinfoga_Linux_x86_64
bash: ./phoneinfoga_Linux_x86_64: cannot execute binary file: Exec format error

I even tried amd64 but same error please help

**Comment by sundowndev** [comment]
Hi, could you please try building from source ? https://sundowndev.github.io/PhoneInfoga/install/#build-from-source

Note: web client won't work because you need to build assets first.

**Comment by sumo2001** [comment]
**Successfully installed from the source...yeah I was about to comment about the web client**
But for every number, I search it is coming out 
[i] Running OVH API scan...
[+] Found: false
[+] Number range: 
[+] City: 
[+] Zip code: 
[i] Job finished.



I tried more than 10 numbers(+91)

Anyways Great work friend!

**Comment by sundowndev** [comment]
>[+] Found: false

This just means the provided number is now owned by OVH Telecom.

>Anyways Great work friend!

Glad you made it work! Thank you

> //////with some https links and exiting but printing this at the last

These are Google links generated to search phone number footprints through Google Search. You can launch the API and make a script that does scraping on these links. Happy hacking!
