### ISSUE TITLE
cant packr2 build -o phoneinfoga

### ISSUE THREAD

**Issue by therealplayboyboy** [sundowndev/PhoneInfoga#221]
what is packr2? how i get this command?

**Comment by sundowndev** [comment]
You should be able to install it this way:

```
go get -u github.com/gobuffalo/packr/v2/packr2
$GOPATH/bin/packr2 build -o phoneinfoga
```

**Comment by odinaka1** [comment]
These are the problems I encountered, how do I solve them


$ packr2 build -o phoneinfoga
No command packr2 found, did you mean:
 Command packf in package nmh from the unstable-repo repository
 Command par2 in package par2
$ GOPATH/bin/packr2 build -o phoneinfoga
bash: GOPATH/bin/packr2: No such file or directory
$

**Comment by odinaka1** [comment]
Thanks in advance

**Comment by sundowndev** [comment]
Hi, @odinaka1 
- It's `$GOPATH/bin/packr2` not `GOPATH/bin/packr2`
- Why don't you install from the binary ?

**Comment by odinaka1** [comment]
I'm using termux and it isn't working from binary

**Comment by sundowndev** [comment]
Alright, Termux is not actually supported, I plan to add it later.

**Comment by sundowndev** [comment]
Closing this issue since packr2 is not used anymore.
