### ISSUE TITLE
failed to resize tty, using default size

### ISSUE THREAD

**Issue by jepunband** [sundowndev/PhoneInfoga#233]
**Describe the bug**
failed to resize tty, using default size
**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)
docker run --rm -it sundowndev/phoneinfoga version
**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by sundowndev** [comment]
Sorry I don't understand what your problem is, can you give further details? Thanks
