### ISSUE TITLE
could not open requirements file:[Errno2]No such file or directory "requirements.txt"

### ISSUE THREAD

**Issue by An-web** [sundowndev/PhoneInfoga#236]
could not open requirements file:[Errno2]No such file or directory "requirements.txt"

command i ran:
python3 -m pip install -r requirements.txt

**Expected behavior**
requirements.txt should have been installed.

**Desktop (please complete the following information):**
 - OS: Windows 10
using kali linux as windows subsystem

![phoneinfoga_error](https://user-images.githubusercontent.com/62478377/77232335-6925c100-6bc6-11ea-9862-22c1ae278ac5.PNG)

**Comment by sundowndev** [comment]
This project has recently been rewritten in Go. It no longer uses Python. Please documentation and follow new installation instructions. https://sundowndev.github.io/PhoneInfoga/
