### ISSUE TITLE
NumVerify Dial TCP refused (latest version, standalone TAR.GZ) 

### ISSUE THREAD

**Issue by starblade09** [sundowndev/PhoneInfoga#237]
hi. after hours finally figuring out how to get one of the methods to install phoneinfoga properly ,working, i ran into a very complex issue, since this is the standalone version. 

Results will hang after the prompt below

```
 ~
→ ./phoneinfoga scan -n +17277550316
[i] Scanning phone number +17277550316
[i] Running local scan...
[+] Local format: (727) 755-0316
[+] E164 format: +17277550316
[+] International format: 17277550316
[+] Country found: +1 (US)
[+] Carrier:
[i] Running Numverify.com scan...
2020/03/21 18:04:51 [Get http://numverify.com/: dial tcp: lookup numverify.com on [::*]:**: read udp [::*]:*****->[::*]:**: read: connection refused]
```
All i could possibly think of is because no `su` or `tsu` was active when testing the results

>Fast-foward; and yes, it seem after i tested `root` capability just now, that footprints loaded successfully. 

Is there no way to run PhoneInfoga without root? 

Btw, thank you so much thus far, for your miraculous coding and work! You upgraded to Go right as im trying to perfect my own Python skills , butI hope to help someday creators like you. Thanks man

**Comment by sundowndev** [comment]
Hi, first could you tell me what kind of issue did you have when trying to install the tool ? How did you end up installing it ?

>Fast-foward; and yes, it seem after i tested root capability just now, that footprints loaded successfully.

Well, I didn't know non-root users could have issues about that. You shouldn't need to use sudo/root privileges to run the software. After a little investigation it seems to be a bug in Go language.

*Questions:*
- Did you build from source ?
  - If yes, what version of Go did you use ? If it's <1.13, please consider upgrading to 1.14 and try again

>Btw, thank you so much thus far, for your miraculous coding and work!
Thank you so much, I appreciate that!

**Comment by starblade09** [comment]
> >Hi, first could you tell me what kind of issue did you have when trying to install the tool ? How did you end up installing it ?

Hey again. at first I tried building it from source `curl` with the help of `pack2` and `Go` , I was having tremendous issues. When going through the documentation, and other people's issues, it seemed be me being gullible and using the wrong `yarn` as well 😁 , but I kept trying every other single way of installing, even with `docker` ,but no luck.

The easiest way for me to install, was by `zip` download via GitHub web browser, and having to multiplatform , transferring my `zip` into the storage of a `linux/unix` environment. Then after having it uncompressed, the issue did still remain with  Linux /(perhaps Debian and Unix as well) `subuser` , with the hang issue after Numverify fails to scan. 

> > Well, I didn't know non-root users could have issues about that. You shouldn't need to use sudo/root privileges to run the software. After a little investigation it seems to be a bug in Go language.

Perfect. Yeah, because when I used the `python` version back in v1.X of PhoneInfoga, never had issues with non-root or subuser. I'm glad to hear that, thank you

> _Questions:_
> 
> * Did you build from source ?
>   
>   * If yes, what version of Go did you use ? If it's <1.13, please consider upgrading to 1.14 and try again
> * What is your OS/arch ?
> > Termux OS armv71 , but later had to switch to Arch to check if it worked on root.

> > Thank you so much, I appreciate that!
 Anytime ! I hope letting you know helped off with any major updates you'll be doing from here on out.👏🏾

**Comment by sundowndev** [comment]
>Termux OS armv71

What Go version?
I think the issue comes from Termux aswell.

**Comment by starblade09** [comment]
> What Go version?
> I think the issue comes from Termux aswell.
It's currently showing me to be `golang/stable 2:1.14.1 arm` 

This could definitely be Termux, now that I think about it. specifically , with the repo of Golang releases on the distro . It's not unusual running into issues like this for Termux. This being said, I did see that there was some documentation pack of Golang that is seperately downloaded as well.

Did you want me to go ahead and attempt from source again? If we still hit a wall on the issue, I could write out some instructions on what needs to be done to run `PhoneInfoga`

**Comment by sundowndev** [comment]
- Do you have any other Linux distribution that is currently supported to try with ?
- What's the output of `uname -a` on Termux ?
- Can you try downloading the binary following [the documentation instructions](https://sundowndev.github.io/PhoneInfoga/install/#download-the-binary) ? It should be the easiest way to install

**Comment by starblade09** [comment]
```
# uname -a                   
Linux localhost 3.18.71-perf-gb838762-00071-g3aa9cf9 #1 SMP PREEMPT Fri *** / ** ***:**:** CDT 2019 armv7l Android
```
This is the non-root OS  that I default to for Termux.

I do use various other distros, such as arch and alpine, but I'm stripped for memory usage atm. I would be giving that binary a shot, but I don't want to botch the already working PhoneInfoga ,because as I said earlier I somehow got it running now 🤔 I'm sorry I am censoring some details for the model due to security, but here's an arch counterpart for `uname`

```
[root14:49home]$ neofetch
                   -`
                  .o+`
                 `ooo/
                `+oooo:
               `+oooooo:
               -+oooooo+:
             `/:-:++oooo+:
            `/++++/+++++++:
           `/++++++++++++++:
          `/+++ooooooooooooo/`
         ./ooosssso++osssssso+`
        .oossssso-````/ossssss+`
       -osssssso.      :ssssssso.
      :osssssss/        osssso+++.       root@localhost
     /ossssssss/        +ssssooo/-       --------------
   `/ossssso+/:-        -:/+osssso+-     OS: Arch Linux ARM armv7l
  `+sso+:-`                 `.-/+oso:    Kernel: 3.18.71-perf-gb838762-00071-g3aa9cf9
 `++:.                           `-/+/   Uptime: *** days, *** hours, 49 mins
 .`                                 `/   Packages: 483 (pacman)
                                         Shell: bash 5.0.16
                                         Terminal: proot
                                         CPU: *****
                                         Memory: 1247MiB / ****MiB
```
Again ,no issues with Arch even within Termux. This could be a distro issue. Even though Termux uses a Linux environment , it doesn't follow the standard `FHS` for in Linux line-up. For example  /bin, /etc, /usr, /tmp are all in different places than where Linux usually has them.

**Comment by starblade09** [comment]
Not too much of an issue , however. I'll go ahead and close this for now. Thank you again.
