### ISSUE TITLE
Error:there is no scenerios;must have at least one

### ISSUE THREAD

**Issue by An-web** [sundowndev/PhoneInfoga#240]
well I was following Build from Source approach and some error occurred on its 4th step(build web client assets)
**Describe the bug**
Error:there is no scenarios;must have at least one

**To Reproduce**
cd client && yarn && yarn build

**Expected behavior**
web client asser built

**Desktop 
 - OS:  Windows 10
Running kali linux as windows subsystem

**Additional context**
I have installed golang and yarn.Also successfully installed packr2.

![phoneinfoga_error2](https://user-images.githubusercontent.com/62478377/77236046-cb8bbb00-6be0-11ea-8ad6-fdd9c0394675.PNG)

**Comment by sundowndev** [comment]
>You've got the wrong yarn 😄

Please read https://github.com/yarnpkg/yarn/issues/2821

**Comment by An-web** [comment]
well that yarn issue has been resolved.
now when i am running the **packr2 build -o PhoneInfoga** command to inject the assets(as per the installation instructions in Build from Source approach):
I am getting error as-**packr2:command not found** 
SCREENSHOT:
![packr2_error_PhoneInfoga](https://user-images.githubusercontent.com/62478377/77244843-b85c0800-6c3f-11ea-815f-280417e6aa4a.PNG)

**Comment by sundowndev** [comment]
It means you didn't installed packr2 properly. May be $GOPATH is not in your $PATH can you try this please ?

```
$GOPATH/bin/packr2 build -o phoneinfoga
```

**Comment by An-web** [comment]
What do you mean by gopath? Is it just a command or some path?
Anyway I tried that as a command and got the same error. Btw I installed go within the root directory and installed packr2 in the phoneinfoga directory using 
**go get -u github.com/gobuffalo/packr/v2/packr2**  as instructed in the installation guide.
SCREENSHOT:
![packr2_error_PhoneInfoga2](https://user-images.githubusercontent.com/62478377/77254111-09dab600-6c85-11ea-902b-cd9478465640.PNG)
![packr2_error_PhoneInfoga3](https://user-images.githubusercontent.com/62478377/77254115-0cd5a680-6c85-11ea-9412-607a6689bbf1.PNG)

pls help me in details.

**Comment by sundowndev** [comment]
You copied it wrong. It's not `gopath/bin/packr2`, it's `$GOPATH/bin/packr2 build -o phoneinfoga`. Please retry and tell me.

**Comment by An-web** [comment]
Well I retried it as per your instructions and seems like that error is gone..but still it's not working :(
Can you pls clarify :where i have to run that  **$HOME/go/bin/packr2 build -o phoneinfoga**command..is it inside PhoneInfoga or inside PhoneInfoga/client?
I tried both btw.
SCREENSHOT:(inside PhoneInfoga/client)
![packr2_error_PhoneInfoga4](https://user-images.githubusercontent.com/62478377/77256084-faae3500-6c91-11ea-9370-838ccfcb7ccf.PNG)

SCREENSHOT:(inside PhoneInfoga)
![packr2_error_PhoneInfoga5](https://user-images.githubusercontent.com/62478377/77256104-16194000-6c92-11ea-80bd-52fd61dc8f24.PNG)

**Comment by sundowndev** [comment]
PhoneInfoga no longer uses packr2, please try the latest binary.
