### ISSUE TITLE
requirements.txt 

### ISSUE THREAD

**Issue by gscheaffer** [sundowndev/PhoneInfoga#243]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by sundowndev** [comment]
This project has recently been rewritten in Go. It no longer uses Python. Please documentation and follow new installation instructions. https://sundowndev.github.io/PhoneInfoga/install/

If you don't want to use version 2, simply move to v1.11 branch:

```
git checkout v1.11
```
