### ISSUE TITLE
phoneinfoga.py missing?

### ISSUE THREAD

**Issue by agnt2** [sundowndev/PhoneInfoga#248]
**Describe the bug**
I am trying to install PhoneInfoga on kali but the git clone is missing the phoneinfoga.py file.

**To Reproduce**
~/PhoneInfoga$ python3 phoneinfoga.py
python3: can't open file 'phoneinfoga.py': [Errno 2] No such file or directory

**Expected behavior**
To launch the program.

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - PhoneInfoga exact version not found

**Additional context**

**Comment by sundowndev** [comment]
This project has recently been rewritten in Go. It no longer uses Python. Please read documentation and follow new installation instructions: https://sundowndev.github.io/PhoneInfoga/install/

If you still want to use legacy version, simply move to v1.11 branch:

```
git checkout v1.11
```

**Comment by odinaka1** [comment]
I don't think phoneinfoga works on termux, if it does please can I be shown how? I'm having difficulties.

**Comment by sundowndev** [comment]
@odinaka1 Termux is not actually supported. Can you tell me what arch is that so I can consider adding support for it ? (`uname -a`)

**Comment by odinaka1** [comment]
Aarch64, thank you

**Comment by furtunali61** [comment]
Do you supported now for aarc64?

**Comment by furtunali61** [comment]
İm not finded for phoneinfoga.py

**Comment by sundowndev** [comment]
I just released v2.0.6 which supports `aarch64`. Feel free to give it a try with Termux. @odinaka1 @furtunali61

**Comment by furtunali61** [comment]
I will try and get back to you immediately :)

**Comment by adhamfuryz** [comment]
@sundowndev Bro please help 
Me git clone https://sundowndev.github.io/PhoneInfoga/install/
Cloning into 'install'...
fatal: repository 'https://sundowndev.github.io/PhoneInfoga/install/' not found
$ when i type this it tells me that

**Comment by adhamfuryz** [comment]
And i cant find phoneinfoga.py what should I do please help

**Comment by vrcx-tech** [comment]
does phoneinfoga work in the termux app?... i cant launch it🤔☹️

**Comment by sundowndev** [comment]
@vrcx-tech It should work, but it was not made to do so. If it doesn't work consider using a different Linux distro. I'm closing this as the original poster didn't respond.

**Comment by Abhijith2001alpha** [comment]
i downloaded the v 1.11 but while running it showing config.file not found

**Comment by sundowndev** [comment]
@Abhijith2001alpha Please read the documentation in your local `docs/` directory (*install.md* for install instructions). Also note v1.11 is deprecated, you should consider using v2.
