### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by zan14** [sundowndev/PhoneInfoga#249]
hai,

before it, first i thank you so much for this tools it really help me to find someone who try send spam call or message to me.

now i have 2 question :
1. after i install using this command in my linux : 
 
go get -u github.com/sundowndev/PhoneInfoga

did i have to install additional part or something ? i'm sorry i never using golang before only python.

2. i try to test is using this command : 
go run ./PhoneInfoga scan +1241351351(example)

the result is number is not valid, exit status 1 ? what is that mean ? was i wrong when input phone number or something ?

**Comment by sundowndev** [comment]
Hi, why don't you simply download the binary and use it ?
To run the tool with Go, the proper command is

```shell
# inside the PhoneInfoga folder
go run main.go scan "+1241351351"
```

The number you provided doesn't appear to be valid. What's its country code ? +1 ?

**Comment by zan14** [comment]
that was just example phone number i created it.

Okay i will try it thanks

**Comment by zan14** [comment]
Its still 

[i] Scanning phone number 
[!] Number is not valid.                                                                                                                                              
exit status 1

Is there something that i miss ?

**Comment by zan14** [comment]
the country code is +62

**Comment by zan14** [comment]
this is the command :

go run main.go scan 62812-8715-7979

**Comment by sundowndev** [comment]
@zan14 You forgot the `-n` option: `phoneinfoga scan -n "+62 812-8715-7979"`.

**Comment by zan14** [comment]
I download this file and extract it, but in that folder there is no phoneinfoga file
 PhoneInfoga_Linux_x86_64.tar.gz

**Comment by zan14** [comment]
oky thank you i found where is the problem thanks

**Comment by zan14** [comment]
Thank you so much for the help, I appreciate your work thank you

**Comment by sundowndev** [comment]
No problem, glad you made it work 👍
