### ISSUE TITLE
Command List?

### ISSUE THREAD

**Issue by Misko2468** [sundowndev/PhoneInfoga#252]
Hello, was just wondering if their was a command list? I keep getting invalid number so I think it is working as I installed through binary and think I'm using incorrect commands!

Thanks in advance! Look forward to some OSINT!

**Comment by sundowndev** [comment]
Hi, what do you mean command list ? `phoneinfoga --help` ?

**Comment by Misko2468** [comment]
Haha ya sorry It was like 4 in the morning when I posted that, I figured it out after. Sorry about that,
