### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by tanghush** [sundowndev/PhoneInfoga#260]
I cloned the file and i use go language. I dont know why it is like this:

go run main.go phoneinfoga scan -n "+1-202-555-0154"
(hashtag) github.com/gobuffalo/packd
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/file.go:11:7: undefined: File
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/file.go:96:41: undefined: File
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/file.go:101:27: undefined: File
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:14:7: undefined: Addable
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:15:7: undefined: Finder
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:16:7: undefined: Lister
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:110:29: undefined: WalkFunc
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:137:47: undefined: WalkFunc
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/skip_walker.go:13:24: undefined: Walker
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/skip_walker.go:13:58: undefined: WalkFunc
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:16:7: too many errors

I use macOS, terminal app. Go version go1.14.1 darwin/amd64. Is something wrong with the code or the file I installed? thank you (in line 3, (hashtag) = #)

**Comment by sundowndev** [comment]
Hi, did you install dependencies ?

Try these commands:
- `go get -v ./...`
- `go mod download`

**Comment by tanghush** [comment]
I tried those commands. dots in -v ./... is it just dots or anything?

The result of those commands is:

go get -v ./...
github.com/gobuffalo/packd
(hashtag) github.com/gobuffalo/packd
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/file.go:11:7: undefined: File
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/file.go:96:41: undefined: File
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/file.go:101:27: undefined: File
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:14:7: undefined: Addable
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:15:7: undefined: Finder
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:16:7: undefined: Lister
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:110:29: undefined: WalkFunc
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:137:47: undefined: WalkFunc
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/skip_walker.go:13:24: undefined: Walker
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/skip_walker.go:13:58: undefined: WalkFunc
../../../../pkg/mod/github.com/gobuffalo/packd@v1.0.0/memory_box.go:16:7: too many errors

go mod download

Nothing yet happened, same thing popped when i tried to scan numbers. For the "go mod download" command, after I typed and enter, it loaded for a while but nothing popped up

**Comment by sundowndev** [comment]
- What's your OS/arch ?
- Have you considered downloading the binary instead ?

**Comment by tanghush** [comment]
I am willing to use binary. In https://github.com/sundowndev/PhoneInfoga/blob/master/docs/install.md , I follow the "Download the binary" section. There are several assests, which assets should i use? I'm sorry if the answer is obvius, just starting

**Comment by sundowndev** [comment]
From your terminal:

```shell
$ echo "$(uname -s)_$(uname -m)"
Darwin_x86_64
# Download PhoneInfoga_Darwin_x86_64.tar.gz
```
----
You can also download it from the terminal:

```shell
LATEST_VERSION=$(curl -s https://api.github.com/repos/sundowndev/phoneinfoga/releases/latest | grep tag_name | cut -d '"' -f 4)

# Download the archive
curl -sSL "https://github.com/sundowndev/phoneinfoga/releases/download/$LATEST_VERSION/phoneinfoga_$(uname -s)_$(uname -m).tar.gz" -o ./phoneinfoga.tar.gz

# Extract the binary
tar xfv phoneinfoga.tar.gz

# Run the software
./PhoneInfoga --help

# Install it globally
mv ./PhoneInfoga /usr/bin/phoneinfoga
```

**Comment by tanghush** [comment]
I use:

curl -sSL "https://github.com/sundowndev/phoneinfoga/releases/download/$LATEST_VERSION/phoneinfoga_$(uname -s)_$(uname -m).tar.gz" -o ./phoneinfoga.tar.gz

And when I tried to extract:

tar xfv phoneinfoga.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

I cant extract the file i downloaded with curl

**Comment by sundowndev** [comment]
It probably means your arch is not supported, what's the output of `echo "$(uname -s)_$(uname -m)"` ?

**Comment by tanghush** [comment]
Darwin_x86_64

**Comment by tanghush** [comment]
It worked! I deleted the file from curl and I downloaded the darwin_x86_64 asset and successfully extract it. Everything worked just fine after it, following the instructions

Thank you very much for your help
