### ISSUE TITLE
python2 phoneinfoga.py

### ISSUE THREAD

**Issue by eqelibari** [sundowndev/PhoneInfoga#262]
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/home/eqelibari/Downloads/PhoneInfoga-1.11/lib/googlesearch.py", line 11, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse

**Comment by sundowndev** [comment]
@eqelibari v1.11 uses Python3. Make sure you install dependencies before.

Why don't you use version 2 ?

**Comment by eqelibari** [comment]
because https://github.com/sundowndev/PhoneInfoga here i cannot find the requirements.txt file,
so i have to sudo apt-get install python3 ?

**Comment by buuda69** [comment]
i am getting the no colorama module also..and i am using python 2

**Comment by sundowndev** [comment]
@eqelibari  By version 2 I meant PhoneInfoga v2.

**Comment by ChartxBTS** [comment]
Me pasa lo mismo :/

**Comment by sundowndev** [comment]
Closing since this is related to legacy version which is no longer maintained. Consider upgrading to v2.
