### ISSUE TITLE
Error in Tar file

### ISSUE THREAD

**Issue by Covek1** [sundowndev/PhoneInfoga#265]
root@localhost:/home/X/PhoneInfoga# tar --test-label -f phoneinfoga.tar.gz
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by Covek1** [comment]
In installation

**Comment by sundowndev** [comment]
Hi, what's your OS/arch ?

In your terminal: `echo "$(uname -s)_$(uname -m)"`

Did you try downloading the archive from the release page ?

**Comment by ANKESH054** [comment]
> echo "$(uname -s)_$(uname -m)"

error is remain same

**Comment by noismi** [comment]
> Hi, what's your OS/arch ?
> 
> In your terminal: `echo "$(uname -s)_$(uname -m)"`
> 
> Did you try downloading the archive from the release page ?

My OS, is Linux_aarch64
