### ISSUE TITLE
Not found requirements.txt

### ISSUE THREAD

**Issue by ra1311** [sundowndev/PhoneInfoga#268]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by dharmendrasharma4** [comment]
Why There is no such file requirements.txt inside the phoneinfoga directory???? Please answer

**Comment by SirDex2022** [comment]
the phoneinfoga missing directory.. it says empty
