### ISSUE TITLE
No useful info

### ISSUE THREAD

**Issue by M3Ga98** [sundowndev/PhoneInfoga#285]
I keep trying searching for different numbers using the command 'phoninfoga scan -n "number"'.
The only thing that's running right is when searching on Numverify.com
It then keeps searching for footprints and doesn't get anything. Just keeps naming some google-searches NOT FOUND sites.
After taking many tries, the whole running takes about 3-4 seconds.
with always the same output
Thanks

**Comment by Dorian781** [comment]
Same problem(
![example](https://user-images.githubusercontent.com/63537128/79065202-364b8600-7cb7-11ea-84d4-589e883a3725.png)

**Comment by sundowndev** [comment]
It basically means there's no result for your query. Remember OSINT is not about magic.

**Comment by Dorian781** [comment]
I tried all the numbers that I know. Not just one.

**Comment by sundowndev** [comment]
The README says:
>Some features were not included in the v2 MVP such as input/output CLI options. The roadmap of the project changed so we can focus on the web client features such as downloading scan results as CSV, Instagram/Whatsapp lookup, and more.

There's not much scanners for now but it's coming. I've a lot of work these days but I plan to add such features later.
