### ISSUE TITLE
After installation can't find config.example.py

### ISSUE THREAD

**Issue by suryadev1234** [sundowndev/PhoneInfoga#294]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by sundowndev** [comment]
It seems like you followed an outdated tutorial. Please read documentation: https://sundowndev.github.io/PhoneInfoga/install/
