### ISSUE TITLE
Segmentation Fault while running on ubuntu 19.10

### ISSUE THREAD

**Issue by souvikhaldar** [sundowndev/PhoneInfoga#298]
**Describe the bug**
Segmentation fault while running the compiled binary on ubuntu 19 on 64 bit.
**To Reproduce**
Cloned the repo.
Compiled with go 1.14 (go install)
Ran the binary
**Expected behavior**
Normal execution
**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/20991754/79425715-be939900-7fdf-11ea-8b71-05da98b680c5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - PhoneInfoga exact version (run `phoneinfoga version`) Can't run
 - Go exact version (if running it with Go) (run `go version`) 1.14.2

**Comment by sundowndev** [comment]
Hi, did you try downloading binary from the release page ? Your OS should be supported. I've never faced that issue but seems to be related to unauthorized memory access.

**Comment by souvikhaldar** [comment]
> Hi, did you try downloading binary from the release page ? Your OS should be supported. I've never faced that issue but seems to be related to unauthorized memory access.

Yes I tried that too but same error.

**Comment by sundowndev** [comment]
Could you give further information about your OS?
- `uname -a`
- How much RAM do you have?

Thank you

**Comment by souvikhaldar** [comment]
> Could you give further information about your OS?
> 
Linux mustang 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> * `uname -a`
> * How much RAM do you have?
> 
I have 12 (8 + 4) GB DDR4 RAM.

**Comment by souvikhaldar** [comment]
Pulled from latest master still the same issue:
![image](https://user-images.githubusercontent.com/20991754/79542945-33cba080-80aa-11ea-9a0a-1c8ef1af045a.png)

**Comment by sundowndev** [comment]
Could you please rerun the program with `GOTRACEBACK` set to 2 ?

```
go install
GOTRACEBACK=2 phoneinfoga
```

You should then be able to get the crash trace back.

Thank you

**Comment by sundowndev** [comment]
You may also use lldb to debug the program:

```
$ go run -ldflags "-w" main.go
```

Thanks for your help

**Comment by souvikhaldar** [comment]
> go install
> GOTRACEBACK=2 phoneinfoga

![image](https://user-images.githubusercontent.com/20991754/79900502-f493ab80-842b-11ea-965e-47e875aa0b36.png)

**Comment by souvikhaldar** [comment]
> You may also use lldb to debug the program:
> 
> ```
> $ go run -ldflags "-w" main.go
> ```
> 
> Thanks for your help

![image](https://user-images.githubusercontent.com/20991754/79900584-12611080-842c-11ea-8a5c-838af707aedc.png)

PS- I've pulled from `origin`'s `master` beforehand.

**Comment by souvikhaldar** [comment]
go version go1.14.2 linux/amd64

**Comment by sundowndev** [comment]
Yes that's because you need to build assets :

```
go get -v github.com/jessevdk/go-assets-builder
$GOPATH/bin/go-assets-builder client/dist -o api/assets.go -p api
go run -ldflags "-w" main.go
```

**Comment by sundowndev** [comment]
You can skip this by downloading the file from me : https://send.firefox.com/download/523ff6773ba85640/#oasdSHqyUTAIoQ3g7Vlmuw

Just download and put it in api folder.

**Comment by sundowndev** [comment]
Or... you can rollback to v2.0.5 to not deal about go-assets `git checkout v2.0.5`.

**Comment by souvikhaldar** [comment]
> Yes that's because you need to build assets :
> 
> ```
> go get -v github.com/jessevdk/go-assets-builder
> (cd client && yarn && yarn build)
> $GOPATH/bin/go-assets-builder client/dist -o api/assets.go -p api
> go run -ldflags "-w" main.go
> ```
> 
> You can skip this by downloading the file from me (assets.go, 3.1MB) : https://send.firefox.com/download/523ff6773ba85640/#oasdSHqyUTAIoQ3g7Vlmuw
> 
> Just download and put it in api folder. Then run `go run -ldflags "-w" main.go`
> 
> Or... you can rollback to v2.0.5 to not deal about go-assets `git checkout v2.0.5`.

When I'm trying to do yarn build I'm getting this error:  
![image](https://user-images.githubusercontent.com/20991754/80567473-e0930f80-8a12-11ea-9426-e01d6432fc78.png)

**Comment by souvikhaldar** [comment]
Still 
![image](https://user-images.githubusercontent.com/20991754/80567972-be4dc180-8a13-11ea-81be-c8acad407364.png)

**Comment by sundowndev** [comment]
>You've got the wrong yarn 😄 https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365

Please consider rollback to v2.0.5 or download the assets.go file from my link. It'll be much simpler for you to avoid getting more issues.

**Comment by souvikhaldar** [comment]
Checked into the said branch and it compiled.

**Comment by souvikhaldar** [comment]
Running fine
I would suggest you to find a way to provide fix for the latest master branch.

**Comment by sundowndev** [comment]
Couldn't reproduce this, waiting for someone to confirm this is not happening anymore with latest release or the issue still persists.
