### ISSUE TITLE
Careless documentation.

### ISSUE THREAD

**Issue by Salim9304** [sundowndev/PhoneInfoga#312]
There is no documentation for launching or installing soft.

I did the corner
```
1) git clone https://github.com/sundowndev/PhoneInfoga.git
2) cd PhoneInfoga/
3) python3 -m pip install requirements.txt #Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/requirements-txt/
4) python3 phoneinfoga.py
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/home/w/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'
5) python phoneinfoga.py
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/home/w/PhoneInfoga/lib/googlesearch.py", line 11, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse

```

A simple user will not start software without documentation.

When I applied my kung fu
I received this and again no documentation.
```
python3 phoneinfoga.py -n 38xxxxxxxx
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.12
 Coded by Sundowndev


[!] The config file does not exist. Please create it.

```
 **PhoneInfoga Ver. v1.10.12**
What???
(git checkout v1.11)

------------------------------------
Great, I found releases on the site.
An ordinary user will not find it on the site, a link is needed

There is not a single example.
When I start, I also get an error
`$ phoneinfoga scan 79891458796`
[i] Scanning phone number 
[!] Number is not valid.

_I destroyed this software and will not return to it again.
Wish: learn how to write documentation._

**Comment by sundowndev** [comment]
Just read https://sundowndev.github.io/PhoneInfoga/install/
You followed an outdated tutorial then say there's no documentation or instructions. All you have to do is **reading**.

> An ordinary user will not find it on the site, a link is needed

A link to what ? To the release page which is on Github ?

> When I start, I also get an error
$ phoneinfoga scan 79891458796

Again, you did not read documentation.

>phoneinfoga scan -n "+1 (555) 444-1212"

<img width="863" alt="image" src="https://user-images.githubusercontent.com/16480203/79861398-4278c700-83cc-11ea-9259-f224664aaf95.png">

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/16480203/79861438-4e648900-83cc-11ea-8573-beabbae233d9.png">
