### ISSUE TITLE
ModuleNotFoundError: No module named 'httplib'

### ISSUE THREAD

**Issue by satyapriy** [sundowndev/PhoneInfoga#316]
UserAccount@linux~/trape$ python3 trape.py --url http://google.com --port 8080
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/octahack/trape/core/utils.py", line 23, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'

Need urgent solution on this please.

**Comment by sundowndev** [comment]
The program you're using is not related to this project.
