### ISSUE TITLE
Google chrome links doesn't give any results after opening them in broswer

### ISSUE THREAD

**Issue by Defaltx** [sundowndev/PhoneInfoga#318]
Tried to open them directly too,  the broswer doesn't open. After the scan in terminal, i copy+paste the link in the link bar, but it doesn't give any results.

**Comment by sundowndev** [comment]
Yes that's because links are generated not scanned. You need to manually open them in the browser and see if there's any result. The old version was scanning links but caused too much issues with Google captcha.

**Comment by FabxBs** [comment]
understood, so i have to try every single link until i get a good one?

**Comment by sundowndev** [comment]
>understood, so i have to try every single link until i get a good one?

Yes. Or write a script that does it for you. See [Go module usage](https://sundowndev.github.io/PhoneInfoga/go-module-usage/).

**Comment by sundowndev** [comment]
Here's a quick example of code to generate Google search links :

```go
package main

import (
	"fmt"
	"log"

	phoneinfoga "github.com/sundowndev/phoneinfoga/pkg/scanners"
)

func main() {
	number, err := phoneinfoga.LocalScan("<number>")

	if err != nil {
		log.Fatal(err)
	}

	links := phoneinfoga.GoogleSearchScan(number)

	for _, link := range links.Individuals {
		fmt.Println(link.URL) // Google search link to scan
	}
}

```
