### ISSUE TITLE
phoneinfoga "An error occured"

### ISSUE THREAD

**Issue by molfid** [sundowndev/PhoneInfoga#333]
**Describe the bug**
[i] Running Numverify.com scan...
[!] An error occured
[!] Get "http://numverify.com/": dial tcp: lookup numverify.com on xxx.xxx.xx.x;xx read udp 192.168.xx.xxx:xxxx->xxx.xxx.xx.x;xx : i/o timeout

**To Reproduce**
phoneinfoga scan -n +21264172****

**Expected behavior**
thank you very much for your efforts , ihope to find a solution to this error.

**Screenshots (optional)**
![oie_VruiK5gwEg4u](https://user-images.githubusercontent.com/40925161/81252424-99cc8900-8fc1-11ea-8144-b10e26ff2b4b.png)

**Desktop (please complete the following information):**
 - OS: [kali linux]
 - PhoneInfoga exact version ( v2.0.5)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**
thanks for you time .

**Comment by sundowndev** [comment]
Hi @molfid ,

- Are you using a proxy, VPN or any network gateway ?
- Are you using a virtual machine to run Kali Linux ?
  - Did you check for issues regarding the network of the VM ?
- Did you try accessing numverify.com website ? Does the scan work from your browser ?

Thanks
