### ISSUE TITLE
~/PhoneInfoga$ python3 -m pip install -r requirements.txt  when i type 

### ISSUE THREAD

**Issue by Abbddul** [sundowndev/PhoneInfoga#337]
check screen shoot below

$  git clone https://github.com/sundowndev/PhoneInfoga
fatal: destination path 'PhoneInfoga' already exists and is not an empty directory.

~
$ cd PhoneInfoga/                                                                                                       
~/PhoneInfoga (master)
$  python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable

~/PhoneInfoga (master)
$  cp config.example.py config.py
cp: cannot stat 'config.example.py': No such file or directory

 ~/PhoneInfoga (master)
$
trying to use phoneinfoga tool

**Comment by Abbddul** [comment]
what  are the python3 packages that I need to install to run phoneinfoga

**Comment by sundowndev** [comment]
Are you sure you're running the tool using the v1.11 tag ? You're trying to install the legacy version of this tool. If you want to install the new version, please read the documentation : https://sundowndev.github.io/PhoneInfoga/

**Comment by Abbddul** [comment]
v2.0.8  
PhoneInfoga_Linux_i386.tar.gz  PhoneInfoga_Linux_i386.tar.gz
6.35 MB
which software  I use to extract this file   i cant open it

**Comment by sundowndev** [comment]
You can use tar as mentioned in the docs : `tar xfv PhoneInfoga_Linux_i386.tar.gz`

**Comment by Abbddul** [comment]
Abdulhameed@LAPTOP-605DMFL2 MINGW64 ~/PhoneInfoga (master)
$  python -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
whats this error  im getting can you help me  with this

**Comment by Abbddul** [comment]
can you tell me with details   if any video   will be good ?

**Comment by sundowndev** [comment]
Closing since this is related to legacy version which is no longer maintained. Consider upgrading to v2.

**Comment by mrhacker-droid** [comment]
![Uploading Screenshot_2023-06-26-18-21-36-671_com.termux.jpg…]()

**Comment by Tooper02** [comment]
u0_a223@localhost ~/p/PhoneInfoga (master)> python3 -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
u0_a223@localhost ~/p/PhoneInfoga (master) [1]> cp config.example.py config.py
cp: cannot stat 'config.example.py': No such file or directory
cd: The directory 'phoneinfoga' does not exist
u0_a223@localhost ~/phoneinfoga (master) [1]> ls
CODEOWNERS          build     main.go
CODE_OF_CONDUCT.md  cmd       mkdocs.yml
Dockerfile          docs      mocks
LICENSE             examples  support
Makefile            go.mod    test
PhoneInfoga         go.sum    web
README.md           lib
bin                 logs
u0_a223@localhost ~/phoneinfoga (master)>

**Comment by Tooper02** [comment]
Phoneinfoga not installed

u0_a223@localhost ~/p/PhoneInfoga (master)> python3 -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
u0_a223@localhost ~/p/PhoneInfoga (master) [1]> cp config.example.py config.py
cp: cannot stat 'config.example.py': No such file or directory
