### ISSUE TITLE
Repeat info on different numbers 

### ISSUE THREAD

**Issue by hellokitty48** [sundowndev/PhoneInfoga#348]
Hi, 

When using any "./phoneinfoga scan -n" any number I enter the results are always the same? Each time I get the exact same information for Social media footprints, Individual footprints, Reputation footprints and Temporary number providers footprints - whichever number I put in?

The only different info is visable in Running local scan...results and Running Numverify.com scan... results?

Help please, what am I doing wrong?

Thanks

**Comment by hellokitty48** [comment]
Hi - Any ideas on this? Thanks

**Comment by sundowndev** [comment]
>any number I enter the results are always the same? Each time I get the exact same information for Social media footprints, Individual footprints, Reputation footprints and Temporary number providers footprints - whichever number I put in?

What do you mean by "same" ? Do you have at least one result ? Or maybe you mean having 0 result for all numbers ?

It would be easier if you could provide a screenshot with some context (hide personal information).

Thanks

**Comment by hellokitty48** [comment]
here u go - thanks 
![screen grab](https://user-images.githubusercontent.com/65345956/82227321-84d7ea00-991f-11ea-9ecd-825c2eb43a5e.jpg)

**Comment by hellokitty48** [comment]
every line there is identical each time i search using any UK mobile number

**Comment by Whitewhistel** [comment]
same problem here also

**Comment by sundowndev** [comment]
The links are auto generated, if you look closer, you can see it does not use the same phone number. Can you confirm that ? From a link to another, only the phone number should change.

**Comment by hellokitty48** [comment]
Not sure I understand. the phone number is different each time because I change it and search different no.s. However any phone number I use gives me identical generated results as per the screenshot. Are they just auto generated results? Shouldn't I be seeing different results!?

**Comment by hellokitty48** [comment]
"From a link to another, only the phone number should change." thats exactly whats happening. So I guess my question is what information am I getting from this?

**Comment by sundowndev** [comment]
If you're talking about Google results, could you provide a screenshot of these "identical generated results" please ? Of course I don't control what's showing up on Google, sometimes you will find irrelevant web pages with phone number footprints, white pages, ...

**Comment by hellokitty48** [comment]
What you see in the screen shot is what im getting - Maybe im missing something here.....

So far the only info im getting that I have seen is different per each number is the carrier

**Comment by sundowndev** [comment]
You have to click on links to see results

**Comment by hellokitty48** [comment]
Hmmm so it takes you to a page with no results and what do you do then?  Perhaps im just not understanding what the program does. So far all I can see is that any mobile number I enter (ones that have lots of reasons to pull up results in google, some none) all produce a line with the same link which then takes me to a blank google page with no results?

**Comment by sundowndev** [comment]
From the [documentation](https://sundowndev.github.io/PhoneInfoga/usage/#available-scanners)
>Google search uses Google search engine and Google Dorks to search phone number's footprints everywhere on the web. It allows you to search for scam reports, social media profiles, documents and more. This scanner does only one thing: generating several Google search links from a given phone number. You then have to manually open them in your browser to see results. You may therefore have links that do not return any results.

If you wish to open links automatically, consider scripting on the [phoneinfoga library](https://sundowndev.github.io/PhoneInfoga/go-module-usage/). Do you now understand better how it works?

**Comment by hellokitty48** [comment]
No, sorry I don't. Apologies. For example -  I have a mobile linked to many social media profiles other than the top 4, its also mentioned many times all over the web. i don't see any of these results when i use the prog. Can you do an example with screenshots using a UK mobile?

**Comment by hellokitty48** [comment]
Hi - Any further help on this much appreciated

**Comment by kaplan21** [comment]
MERHABA BENİM Bİ SORUM OLACAK SİZLERDEN BU TERMUX PROGRAMI NASIL KURABİLİRİM VE NASIL KESİN SONUÇ ALABİLİRİM
BİDE BU PROGRAMLAR VE KODLAR HAKINDA EĞİTİLMEK İSTİYORUM YARDIMCI OLURSANIZ ÇOK SEVİNİR EĞİTİLMEK İSTEMEMİN SEBEBİ İSE KÜÇÜK BİŞEY BİLE OLSA VATANIMA MİLETİME KATKIM OLMASINI İSTEMEMDİR YARDIMCI OLURSANIZ SEVİNİRİM

**Comment by sundowndev** [comment]
>I have a mobile linked to many social media profiles other than the top 4, its also mentioned many times all over the web

Which social media ?

**Comment by hellokitty48** [comment]
perhaps it doesnt work the same for UK mobile numbers?
