### ISSUE TITLE
issues with Links

### ISSUE THREAD

**Issue by Sh4d0wR00t85** [sundowndev/PhoneInfoga#350]
**Describe the bug**
when i attempt to open a link i get no information or the index doesnt work..
https://www.google.com/search?q=site%3Ahs3x.com+intext%3A%222335%22

**To Reproduce**
sudo ./PhoneInfoga scan -n 233***********

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: Parrot Os
 - PhoneInfoga exact versionv2.0.5

 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by sundowndev** [comment]
Hi, you get no result from Google right ? This is the normal behavior. PhoneInfoga does not scan these links to find results, it generates them. So links can lead to empty result.

**Comment by Sh4d0wR00t85** [comment]
Ok thank you


Sent from Yahoo Mail for iPhone


On Friday, May 15, 2020, 03:16, Raphaël <notifications@github.com> wrote:




Hi, you get no result from Google right ? This is the normal behavior. PhoneInfoga does not scan these links to find results, it generates them. So links can lead to empty result.
