### ISSUE TITLE
undefined: Assets

### ISSUE THREAD

**Issue by t4zz1r** [sundowndev/PhoneInfoga#356]
when I do ``go build`` or ``go run main.go`` I always get:

# gopkg.in/sundowndev/phoneinfoga.v2/api
api/server.go:35:26: undefined: Assets

**Comment by sundowndev** [comment]
You have to build static assets. See an example here https://github.com/sundowndev/PhoneInfoga/blob/master/.github/workflows/build.yml#L32

**Comment by Tahsi9AhmeD** [comment]
> You have to build static assets. See an example here https://github.com/sundowndev/PhoneInfoga/blob/master/.github/workflows/build.yml#L32

This is now a 404 page, lol. Please give a solution for this problem

# gopkg.in/sundowndev/phoneinfoga.v2/api
api/server.go:41:26: undefined: Assets
