### ISSUE TITLE
GOLang issue while building

### ISSUE THREAD

**Issue by lavish440** [sundowndev/PhoneInfoga#363]
Whenever I try to build or run main.go I get this issue. 

# gopkg.in/sundowndev/phoneinfoga.v2/api                                                                  api/server.go:34:26: undefined: Assets

**Comment by sundowndev** [comment]
You have to build static assets. See an example here https://github.com/sundowndev/PhoneInfoga/blob/master/.github/workflows/build.yml#L32

**Comment by lavish440** [comment]
> You have to build static assets. See an example here https://github.com/sundowndev/PhoneInfoga/blob/master/.github/workflows/build.yml#L32
> 
> ```
> (cd client && yarn && yarn build)
> go get -v github.com/jessevdk/go-assets-builder
> go generate ./...
> go build -v .
> ```

I can't use Yarn. I am using Termux for Android.

**Comment by sundowndev** [comment]
Why don't you choose binary installation?

**Comment by lavish440** [comment]
> Why don't you choose binary installation?

Okay I will use release version. 
Closing this issue.

**Comment by advaithpr1020** [comment]
Hi.
can you please elaborate on building the static assets?
I am also getting the same error

**Comment by sundowndev** [comment]
@advaithpr1020 Hi, you need Node v10, npm and yarn in order to build static assets. Building it will create a `dist` directory which is then needed by the Go application to compile the whole project.

But note binary installation is the easiest way to install the app. Build from source should only be performed by contributors.

**Comment by advaithpr1020** [comment]
Thanks 😊

**Comment by mrx0ip** [comment]
link of binary version please i can't find it

**Comment by lavish440** [comment]
> link of binary version please i can't find it

https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.3.1
You can select the release for your device from here.
