### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by jeaw2k** [sundowndev/PhoneInfoga#369]
How to install and use PhoneInfoga on Termux?

**Comment by snake3fang** [comment]
https://youtu.be/QzGb9SG5SL8 this might help but you will need to locate requirements file first

**Comment by sundowndev** [comment]
Don't follow these outdated tutorials and read the documentation. https://sundowndev.github.io/PhoneInfoga/

>If the installation fails, it probably means your OS/arch is not suppored.
>
>Please check the output of `echo "$(uname -s)_$(uname -m)"` in your terminal and see if it's available on the GitHub release page.
