### ISSUE TITLE
gopkg.in/sundowndev/phoneinfoga.v2/api api/server.go:34:26: undefined: Assets

### ISSUE THREAD

**Issue by advaithpr1020** [sundowndev/PhoneInfoga#374]
Can u pls elaborate on building the static assets? 
PS : I'm new here😄

**Comment by sundowndev** [comment]
Hi, please read the related page https://sundowndev.github.io/PhoneInfoga/contribute/

Note if you're not developing/contributing to the project, you should download the binary, not build from source.

**Comment by advaithpr1020** [comment]
Ok😄😄 Will try binary installation.
Thanks 😁
