### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION= In phoneInfoga

### ISSUE THREAD

**Issue by Abhijithm41851** [sundowndev/PhoneInfoga#391]
when we scanning a mobile number after ovh scan this problem will found

**Comment by Abhijithm41851** [comment]
Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=^

**Comment by Devil-vx** [comment]
What is this v1 label can u tell me because for me too it occurred same issue

**Comment by commandoskeepz** [comment]
please i am having the same issue and i don't know how to get past this GOOGLE_ABUSE_EXEMPTION. please help

**Comment by sundowndev** [comment]
Duplicate of #399

**Comment by Snake10q4** [comment]
I am having the same problem. Thanks for the help
