### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION=

### ISSUE THREAD

**Issue by cool6996** [sundowndev/PhoneInfoga#399]
this shows...and a link is given to verify captcha that i'm not a bot but it never works...it only shows till 'Line Type'....

**Comment by cool6996** [comment]
![IMG_20200619_180415](https://user-images.githubusercontent.com/67092213/85132889-55d2d200-b257-11ea-8953-49834d586d86.jpg)
see this img...

**Comment by sundowndev** [comment]
You are using the old version of PhoneInfoga, please update to v2.
