### ISSUE TITLE
Google links not working

### ISSUE THREAD

**Issue by r2d2V2** [sundowndev/PhoneInfoga#410]
The command shows useless links that cannot be opened in a browser. I hope my issue is not extremely stupid.

I ran:
phoneinfoga scan -n "+1 555-444-3333"

**Expected behavior**
I thought I could just copy & paste them into firefox.

**Desktop:**
Description:	Ubuntu 20.04 LTS

Those links shows up:

[i] Generating Google search dork requests...
[i] Social media footprints
[+] Link: https://www.google.com/search?q=site%3Afacebook.com+intext%3A%2215554443333%22+OR+intext%3A%22%2B15554443333%22+OR+intext%3A%225554443333%22
[+] Link: https://www.google.com/search?q=site%3Atwitter.com+intext%3A%2215554443333%22+OR+intext%3A%22%2B15554443333%22+OR+intext%3A%225554443333%22
[+] Link: https://www.google.com/search?q=site%3Alinkedin.com+intext%3A%2215554443333%22+OR+intext%3A%22%2B15554443333%22+OR+intext%3A%225554443333%22
[+] Link: https://www.google.com/search?q=site%3Ainstagram.com+intext%3A%2215554443333%22+OR+intext%3A%22%2B15554443333%22+OR+intext%3A%225554443333%22

**Comment by sundowndev** [comment]
Why do you mean by "cannot be opened in a browser" ? All those links work fine for me.

**Comment by r2d2V2** [comment]
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/49783685/86235935-855bd580-bb99-11ea-924b-18ad998c8331.png)

**Comment by sundowndev** [comment]
The link is working but there's no results. Those links are just generated.

**Comment by r2d2V2** [comment]
I just thought it's gonna show smth useful. I watched some yt vids about PhoneInfoga and people just copy-pasted links and saw results.

**Comment by Alex-kzn** [comment]
Как устранить ошибку ? 
[!] The config file does not exist. Please create it.

**Comment by r2d2V2** [comment]
So this PhoneInfoga does not rly give much information.

**Comment by sundowndev** [comment]
Obviously not all scans point to results. Some Google links may simply return no results, that's the normal behavior.

**Comment by r2d2V2** [comment]
To be honest i prefer the older version where PhoneInfoga shows "valid" links, that mean sth.

**Comment by r2d2V2** [comment]
Now it gives completely basic information, can be considered useless.

**Comment by sundowndev** [comment]
> To be honest i prefer the older version where PhoneInfoga shows "valid" links, that mean sth.

That version was causing users to have troubleshoots using Selenium web driver. I plan to introduce a way to use Chromium to have this feature again.

**Comment by KuraXu** [comment]
I'm having the same issue, every link shows up as a google dorks, im not getting any results.

**Comment by Namangarg110** [comment]
I am facing same problem,
but honestly great job man

**Comment by ITCMD** [comment]
I was confused by this too, thanks for clearing it up. Is there a way to detect the "no results" message and display it, or would that cause issues with google's captcha?

**Comment by sundowndev** [comment]
@ITCMD Currently there's no way to do that automatically, because Google captcha puts some hard technical limitations.

**Comment by AKFalcon01** [comment]
bro the libnks are not openening in google chrome and not in any of the browser !

**Comment by dearinheadlights1** [comment]
Yeah, i can't get any links to show results. Went down the list of my contacts and most i can find on Whitepages but out of 100 not 1 came back with a results just the generated links

**Comment by dearinheadlights1** [comment]
But in all honesty you guys do a good job. I couldn't come up with this stuff. Not yet anyway.

**Comment by Amrith07** [comment]
I have experimented this tool with my own phone number. But the links provided related to the social media accounts are not valid, I.e., the link doesn't give any results. Is there any way to get this corrected/known solution to get the valid links ?

**Comment by chiron-hckme** [comment]
why all links ive got till now for various numbers are not giving any results
