### ISSUE TITLE
It doesn't work in my nethunter it just keeps saying command not found

### ISSUE THREAD

**Issue by Tiny-rick2** [sundowndev/PhoneInfoga#417]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by TheRicky90** [comment]
In my case it work fine.. i flashed a costum rom the right nethunter zip a specific patch and after starting and update/upgrade my environment i follow the install guide as follow.. 

# Download the archive 
wget "https://github.com/sundowndev/phoneinfoga/releases/download/v2.3.0/phoneinfoga_Linux_arm64.tar.gz" 

# Extract the binary 
tar xfv "phoneinfoga_Linux_arm64.tar.gz" 

# Check the binary 
./phoneinfoga version 

# You can also install it globally 
mv ./phoneinfoga /usr/bin/phoneinfoga 

I installed it globally.. 

![Screenshot_20200722-110041_NetHunter Terminal](https://user-images.githubusercontent.com/65061006/88157431-0a6f6300-cc0b-11ea-89f5-b1286abeaec4.jpg)

**Comment by Tiny-rick2** [comment]
Thnks man it really helped

**Comment by sundowndev** [comment]
Closing since it seems resolved.
