### ISSUE TITLE
Install termux?

### ISSUE THREAD

**Issue by dotcom-a0n1** [sundowndev/PhoneInfoga#422]
hi, how could i install PhoneInfoga on termux?

**Comment by TheRicky90** [comment]
**In my case i used the Nethunter Terminal and a COSTUM ROM patched to use Nethunter.. im not a termux user.. 
But i asume its pretty similar..**

For Nethunter you need to change the changeme_changeme in our specific one for your device seems to look loke Linux_arm64 in my case..


# Download the archive 
wget "https://github.com/sundowndev/phoneinfoga/releases/download/v2.3.0/phoneinfoga_changeme_changeme.tar.gz" 

# Extract the binary 
tar xfv "phoneinfoga_changeme_changeme.tar.gz" 

# Check the binary 
./phoneinfoga version 

# You can also install it globally 
mv ./phoneinfoga /usr/bin/phoneinfoga 

Info from
https://sundowndev.github.io/PhoneInfoga/install/

**But if i tipe phoneinfoga termux on google i finde this check this out**

 Step 1: Open Google Play Store & Download 

    Termux
    Termux -API   


               

Step 2: Open Termux and Type following commands that given below.

    pkg update
    pkg upgrade
    pkg install python
    pkg install python2
    pkg install git
    git clone https://github.com/abhinavkavuri/PhoneInfoga
    ls
    cd PhoneInfoga
    ls
    mv config.example.py config.py
    ls
    python3 -m pip install -r requirments.txt
    ls
    chmod +x *
    ls
    python3 phoneinfoga.py -n +(phone number with country code)

Sojrce https://techrahman5.blogspot.com/2020/06/install-phoneinfoga-in-termux-phone.html?m=1

If i am a termux user i will look to combine tese guide whit the officiall source code.. 
But it is possible...

Have a nice day

**Comment by enigm4s** [comment]
...
> If i am a termux user i will look to combine tese guide whit the officiall source code..
> But it is possible...
> 
> Have a nice day

can confirm, I just intall it with the source code. the easiest install I've ever met.

for anyone who wonder how to, especially @dotcom-a0n1 : 
1. in termux, type :

`uname -s`
it will show something like `Linux`
`uname -m`
it will show your device like `aarch64`
in my case, `aarch64` is `arm64`

2. open [phoneinfoga release v2.3.1](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.3.1)  and download archive provided according to your device.

3. extract
`tar xvf phoneinfo_xxxxx_xxxxx.tar.gz`

4. check if this working
`./phoneinfoga` or `./phoneinfoga version`

5. if error and permission denied :
`chmod +x phoneinfoga` then run it again.

6. don't mind my screenshot, I made bash alias to phoneinfoga.

![Screenshot_20200810-071655](https://user-images.githubusercontent.com/68355570/89744678-8574bc80-dad9-11ea-9b32-c990952e4702.png)


you can make `alias`, `symlink` or move it to` $PREFIX/bin`.
thats all, now you can run it.

**Comment by dotcom-a0n1** [comment]
Thank u !

Il lun 10 ago 2020, 02:22 eNigma <notifications@github.com> ha scritto:
