### ISSUE TITLE
./phoneinfoga serve -p {port number}

### ISSUE THREAD

**Issue by Invectiz** [sundowndev/PhoneInfoga#428]
Hello, what does this command do and how do I stop the command from running? If I force close Kali Linux without turning off the terminal that was running because of ./phoneinfoga serve -p , what will happen?

**Comment by sundowndev** [comment]
This command launches a web server to use a graphical user interface from your browser. You must stop the process with CTRL+C in your terminal.

**Comment by Invectiz** [comment]
What happens if I just shut down Kali Linux without stopping the process?

**Comment by sundowndev** [comment]
It can prevent your OS from shutting down but the process will stop as soon as you shut down your computer.
