### ISSUE TITLE
Phoneinfoga not found in dictionary 

### ISSUE THREAD

**Issue by unis2512** [sundowndev/PhoneInfoga#432]
**Describe the bug**
So I was trying to install phoneinfoga thru kali Linux, and I installed it and everything was fine until I was in the last stage of launching ( the file was in `cd downloads` ) and when I typed `./Phoneinfoga ` a error popped up and sayed : 
Phoneinfoga is not in the dictionary 
Can you tell me stage by stage how to fix it please ?

**Comment by sundowndev** [comment]
I think you made a typo in the command : `./phoneinfoga`. If it's not the case, just list the files in the directory with `ls -lha` and check what's wrong.

**Comment by unis2512** [comment]
![image](https://user-images.githubusercontent.com/68770873/88453407-3db22c00-ce6f-11ea-9bb9-770ca35ea643.jpg)
So what to do now ?

**Comment by sundowndev** [comment]
You must extract the archive's content first, check the doc

**Comment by unis2512** [comment]
![image](https://user-images.githubusercontent.com/68770873/88453994-b7004d80-ce74-11ea-8537-829c25dfd3e4.jpg)
![image](https://user-images.githubusercontent.com/68770873/88454002-cbdce100-ce74-11ea-8d62-5197f787ec04.jpg)

**Comment by unis2512** [comment]
Like that ?

**Comment by sundowndev** [comment]
> Like that ?

Yes
