### ISSUE TITLE
Could not open requirements.txt file

### ISSUE THREAD

**Issue by Pavelpikola** [sundowndev/PhoneInfoga#434]
Hi, why I have this problem? ![20200728_142547.jpg](https://user-images.githubusercontent.com/66570176/88665028-42c8e280-d0de-11ea-8e08-fd5a5ad631fd.jpg)

**Comment by sundowndev** [comment]
Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/).

**Comment by Pavelpikola** [comment]
still nothing
