### ISSUE TITLE
A txt file is missing

### ISSUE THREAD

**Issue by Adi2106** [sundowndev/PhoneInfoga#449]
There is a file named requirements.txt which was available before but is missing now. It is required to start the process

**Comment by trashfishprophet** [comment]
I'm having trouble installing it through pip. I get this output.
`kali@kali:~/PhoneInfoga$ python3 -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
`

**Comment by sundowndev** [comment]
You're trying to follow v1.x install instructions. Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/).

**Comment by SiddTim** [comment]
Refer #492 , use [this](https://sundowndev.github.io/PhoneInfoga/install/) to install.

**Comment by gypsymn** [comment]
> There is a file named requirements.txt which was available before but is missing now. It is required to start the process

do you know how to get the requirement file
