### ISSUE TITLE
no cookies 

### ISSUE THREAD

**Issue by pretech86** [sundowndev/PhoneInfoga#46]
no cookies appear with me . i refresh the page but nothing happened

it working with me < i signe out and login again it working

**Comment by sundowndev** [comment]
The issue here is not clear to me. You signed out and logged again to Google and it worked ?

**Comment by federico33385** [comment]
This Issue should be re-open. I have QA this process over and over again and there is no way this cookie name is showing up anywhere in the DEV tools. Maybe you have another way to trigger a captha here?. Maybe I should google for that, or maybe any google captcha will just do the trick?
