### ISSUE TITLE
Some how, I stuck!

### ISSUE THREAD

**Issue by F250SC** [sundowndev/PhoneInfoga#461]
**Describe the bug**

_-bash: syntax error near unexpected token `-1'_

**To Reproduce**

_phoneinfoga scan -n <a phone number>_

**Comment by sundowndev** [comment]
Hi, I need the phone number to reproduce this. Please censor the last digits.

**Comment by CPT-Damian** [comment]
When I try to install it, I get this mv ./phoneinfoga /usr/bin/phoneinfoga
mv: cannot move './phoneinfoga' to '/usr/bin/phoneinfoga': Permission denied
![phoneinfoga issue](https://user-images.githubusercontent.com/71907201/94321399-57631300-ff87-11ea-81b7-3dab472f7d53.png)

**Comment by d4rkc0nd0r** [comment]
This error can be fixed by using `sudo mv ./phoneinfoga /usr/bin/phoneinfoga`.
