### ISSUE TITLE
can't clone the repo or wget 404 not found 

### ISSUE THREAD

**Issue by 14kaitou** [sundowndev/PhoneInfoga#466]
`wget "https://github.com/sundowndev/phoneinfoga/releases/download/v2.3.2/phoneinfoga_$(uname -s)_$(uname -m).tar.gz"                                                                   --2020-08-27 15:27:06--  https://github.com/sundowndev/phoneinfoga/releases/download/v2.3.2/phoneinfoga_Linux_aarch64.tar.gz                Resolving github.com (github.com)... 13.229.188.59                    Connecting to github.com (github.com)|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 404 Not Found                 2020-08-27 15:27:07 ERROR 404: Not Found.`

**Comment by sundowndev** [comment]
Command `wget "https://github.com/sundowndev/phoneinfoga/releases/download/v2.3.2/phoneinfoga_$(uname -s)_$(uname -m).tar.gz"` is working fine for me.

```
HTTP request sent, awaiting response... 200 OK
Length: 7218410 (6.9M) [application/octet-stream]
Saving to: ‘phoneinfoga_Darwin_x86_64.tar.gz’

infoga_Darwin_x86_6  25%[====>               ]   1.75M  26.3KB/s    eta 1m 54s
```

Please retry or check your connection.

**Comment by sundowndev** [comment]
According to the documentation:

> If you don't see your OS/arch on the release page on GitHub, it means it's not explicitly supported. You can build from source by yourself anyway.

> If the installation fails with a 404 error, it probably means your OS/arch is not suppored.

> Please check the output of echo "$(uname -s)_$(uname -m)" in your terminal and see if it's available on the GitHub release page.

**Comment by 14kaitou** [comment]
Sorry about that I've just read the documentation, and thank you
