### ISSUE TITLE
cant run phoneinfoga

### ISSUE THREAD

**Issue by idoamdu** [sundowndev/PhoneInfoga#468]
(using kali linux)tried using phoneinfoga downloaded the os things andd when i type ./phoneinfoga the terminal says 
bash: ./phoneinfoga: No such file or directory
what can i do?
![Screenshot_2020-08-31_13-01-31](https://user-images.githubusercontent.com/70534945/91746132-1e9f6c00-eb8a-11ea-86f8-a9fce207b76e.png)
![Screenshot_2020-08-31_13-02-26](https://user-images.githubusercontent.com/70534945/91746188-3bd43a80-eb8a-11ea-8e46-a1d281ee4c8e.png)
![Screenshot_2020-08-31_13-04-00](https://user-images.githubusercontent.com/70534945/91746356-78079b00-eb8a-11ea-8745-83e9907fdad7.png)

**Comment by sundowndev** [comment]
You don't need to clone the repository. In your last screenshot, there's a `PhoneInfoga` executable, that's what you need to execute.

**Comment by idoamdu** [comment]
after i ran what u said discovered i got the wrong release thanks
