### ISSUE TITLE
i didn't get usful information

### ISSUE THREAD

**Issue by pretech86** [sundowndev/PhoneInfoga#47]
thanks for your effort but i didn't recieved a useful information or i'am wrong ?  i mean all information is general i can get it from websites

**Comment by sundowndev** [comment]
First, what command did you run ?
Secondly, if the number you scanned does not have footprints, the tool can't create it.

OSINT is not about magic, if there's no relevant information, we can't do anything about it. The only thing the tool does not check for, is phone number footprints in data breaches.
