### ISSUE TITLE
PhoneInfoga not launching

### ISSUE THREAD

**Issue by SairajSR7** [sundowndev/PhoneInfoga#482]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by SairajSR7** [comment]
It is not launching and showing error in launching

**Comment by sundowndev** [comment]
What are the errors?

**Comment by razzat** [comment]
> What are the errors?
no requirements.txt is not shown in that directory

**Comment by Usman-khan826** [comment]
there is no requirement.txt file in the PhoneInfoga directiry.
if there is any other method plz tell me/us
![Screenshot_2020-12-23-17-34-44-686_com termux](https://user-images.githubusercontent.com/76521539/102996744-6e44e180-4545-11eb-89fe-7340d4ef3c9f.png)

**Comment by 0n1cOn3** [comment]
Install "go" and execute the main.go file.

**Comment by sundowndev** [comment]
Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/) and follow install instructions. You just need the binary. You can also build from source but you'll need several requirements (Go, git, yarn, nodejs).

**Comment by LutomHaging** [comment]
404 file not found in read documentation

**Comment by sundowndev** [comment]
@LutomHaging fixed, thanks
