### ISSUE TITLE
Invalid Phone Number

### ISSUE THREAD

**Issue by jatinchoudhary** [sundowndev/PhoneInfoga#485]
./phoneinfoga scan --number string +91882471xxxx

Hello Dude,

I used the above command to search phone number. But it says ' Invalid Phone Number'
Please tell me the correct command to search a number.

Thnx in Advnc

**Comment by sundowndev** [comment]
Your command seems invalid, try this instead: `./phoneinfoga scan -n +91882471xxxx`

**Comment by d4rkc0nd0r** [comment]
This command `./phoneinfoga scan -n +91882471xxx` works.

**Comment by Abhaysoft-inc** [comment]
Local scan: Parameter 'number' must be a valid integer.
Numverify scan: Parameter 'number' must be a valid integer.
Google search: Parameter 'number' must be a valid integer.
OVH Telecom scan: Parameter 'number' must be a valid integer.

**using number : +918948041xxx**

**Comment by sundowndev** [comment]
> on using ./phoneinfoga serve -p 8000 and filling the required field in browser
> 
> Local scan: Parameter 'number' must be a valid integer.
> Numverify scan: Parameter 'number' must be a valid integer.
> Google search: Parameter 'number' must be a valid integer.
> OVH Telecom scan: Parameter 'number' must be a valid integer.
> 
> **using number : +918948041xxx**

@Abhaysoft-inc Sorry I cannot reproduce. It's working for me using [demo](https://demo.phoneinfoga.crvx.fr/) version 2.3.5 :

![image](https://user-images.githubusercontent.com/16480203/97888926-008ded80-1d2c-11eb-9f91-1a4983dd9ae8.png)

You can verify the number is valid on https://numverify.com/. Can you provide a uncensored number to reproduce the issue ?

**Comment by julsvern** [comment]
Having the exact same issue with the latest version.

**Comment by julsvern** [comment]
I typed in the same exact number:
![image](https://user-images.githubusercontent.com/73228653/103583110-89a0dc80-4eb5-11eb-9deb-a8633788e712.png)

**Comment by sztuk5** [comment]
I'm having the same issue on armv6 version.

**Comment by Bigboy55e** [comment]
+ County code 601

6016224968
