### ISSUE TITLE
Could not open requirements.txt 

### ISSUE THREAD

**Issue by kDezirez** [sundowndev/PhoneInfoga#490]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by kDezirez** [comment]
no option to install the requirements

**Comment by ITCMD** [comment]
no longer uses requirements. Use https://sundowndev.github.io/PhoneInfoga/install/

**Comment by Vinay584** [comment]
You use bash script
