### ISSUE TITLE
mv: cannot move './phoneinfoga' to '/usr/bin/phoneinfoga': Permission denied

### ISSUE THREAD

**Issue by CPT-Damian** [sundowndev/PhoneInfoga#495]
I can't use this command for some reason. I'm new to linux and so far, it is as not user friendly as people say indeed. Though, I want to learn and understand it. 

This is my problem with it in the image shown.
![phoneinfoga issue](https://user-images.githubusercontent.com/71907201/94321685-4070f080-ff88-11ea-9fc9-4d22284cab36.png)

**Comment by sundowndev** [comment]
You need to use `sudo`.
