### ISSUE TITLE
Request failed. Please retry or open an issue 

### ISSUE THREAD

**Issue by rezoor** [sundowndev/PhoneInfoga#499]
ran the script and he wrote to me

[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'

`---- Fetching informations for 71111111111 ---- [!]
[-] Running local scan...
[+] International format: +7 111 111-11-11
[+] Local format: 001111111111
[+] Country found: Russia (+7)
[+] City/Area: Russia
[+] Carrier: Beeline
[+] Timezone: Asia/Almaty
[+] Timezone: Asia/Anadyr
[+] Timezone: Asia/Aqtobe
[+] Timezone: Asia/Irkutsk
[+] Timezone: Asia/Kamchatka
[+] Timezone: Asia/Krasnoyarsk
[+] Timezone: Asia/Magadan
[+] Timezone: Asia/Novosibirsk
[+] Timezone: Asia/Omsk
[+] Timezone: Asia/Sakhalin
[+] Timezone: Asia/Vladivostok
[+] Timezone: Asia/Yakutsk
[+] Timezone: Asia/Yekaterinburg
[+] Timezone: Europe/Bucharest
[+] Timezone: Europe/Moscow
[+] Timezone: Europe/Samara
[-] The number is valid and possible.
[-] Running Numverify.com scan...
[+] Number: (+7) 1111111111
[+] Country: Russian Federation (RU)
[+] Location: Moscow and Moscow Oblast
[+] Carrier: PJSC Vimpel-Communications (VimpelCom)
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[-] Running OVH scan...
[-] Running OSINT footprint reconnaissance...
[-] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/7-111-111-11-11
[-] Would you like to use an additional format for this number ? (y/N) y
[-] Custom format: 81111111111
[-] ---- Web pages footprints ----
[-] Searching for footprints on web pages... (limit=10)
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=71111111111+%7C+intext%3A%2111111111111%22+%7C+intext%3A%22%2B7+111+111-11-11%22+%7C+intext%3A%2281111111111%22&amp;gws_rd=ssl&amp;gl=us 

[-] Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=ID=b672831191e467be:TM=1601113460:C=r:IP=11.11.11.11-:S=APGng0sBStqZEuDjq0lnBMyWhZ4nuyBSmw
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for documents... (limit=10)
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] ---- Reputation footprints ----
[-] Searching for reputation report on whosenumber.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for phone fraud footprints...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for reputation report on findwhocallsme.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Generating URL on scamcallfighters.com...
[+] http://www.scamcallfighters.com/search-phone-71111111111.html
[-] Would you like to search for temporary number providers footprints ? (Y/n) y
[-] ---- Temporary number providers footprints ----
[-] Searching for phone number on tempophone.com...
[!] Unable to reach tempophone.com API. Skipping.
[-] Searching for footprints on hs3x.com...
[-] Searching for footprints on receive-sms-now.com...
[-] Searching for footprints on smslisten.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on smsnumbersonline.com...
[-] Searching for footprints on freesmscode.com...
[-] Searching for footprints on catchsms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on smstibo.com...
[-] Searching for footprints on smsreceiving.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on getfreesmsnumber.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on sellaite.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on receive-sms-online.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on receivesmsonline.com...
[-] Searching for footprints on receive-a-sms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on sms-receive.net...
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=site%3A%22sms-receive.net%22+intext%3A%22%2B71111111111%22&amp;gws_rd=ssl&amp;gl=us 

[-] Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=ID=f28d60f8d378cbc9:TM=1601113572:C=r:IP=11.11.11.11-:S=APGng0vZ1olHE7cD58DXlVmWogXiokSuVA
[-] Searching for footprints on receivefreesms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on receive-sms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on receivetxt.com...
[-] Searching for footprints on freephonenum.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on freesmsverification.com...
[-] Searching for footprints on receive-sms-online.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on smslive.co...
[-] ---- Social media footprints ----
[-] Searching for footprints on facebook.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on twitter.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on linkedin.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on instagram.com...
[-] ---- Phone books footprints ----
[-] Searching for footprints on numinfo.net...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on sync.me...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on whocallsyou.de...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on pastebin.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on whycall.me...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on locatefamily.com...
[-] Would you like to rerun OSINT scan ? (e.g to use a different format) (y/N) n
[-] Scan finished.
`

**Comment by sundowndev** [comment]
You're using version 1.x, which is deprecated. Please upgrade to version 2.x.
