### ISSUE TITLE
Custom search API key is not working

### ISSUE THREAD

**Issue by pretech86** [sundowndev/PhoneInfoga#50]
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for documents... (limit=10)
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] ---- Reputation footprints ----
[i] Searching for reputation report on whosenumber.info...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for phone fraud footprints...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for reputation report on findwhocallsme.com...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for reputation report on yellowpages.ca...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for reputation report on phonenumbers.ie...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for reputation report on who-calledme.com...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for reputation report on usphonesearch.net...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for reputation report on whocalled.us...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Searching for reputation report on quinumero.info...
[!] Error while fetching Google search API. Maybe usage limit ? Please verify your keys.
[i] Generating URL on scamcallfighters.com...

can you help please

**Comment by sundowndev** [comment]
Hi, what command did you run ? (don't forget to hide the number)
Also did you put a Google API key in `config.py` ?
Is it the first time you're running the tool ?

**Comment by pretech86** [comment]
I put google api in config file 
 I use python3 phoneinfoga.py -n

**Comment by sundowndev** [comment]
@pretech86 Sorry for late response, did you try without using a google search key ?
It seems like you reached the request limit of your key.

**Comment by Huxly42** [comment]
Hey new to github but thought this was such a cool project I had to join! 

I am also experiencing an issue with the google blacklist but every time I follow the link it just takes me to a search. Possibly it is satanizing the URL to not allow users to get the cookie? When I follow the url it spits out this: (x's being the phone number)
xxxxxxxxxxx OR "xxxxxxxxxxx" OR "+1 xxxxxxxxxx"

Hope this helps!

**Comment by sundowndev** [comment]
@pretech86 Feel free to reopen if you have further details.

@Huxly42 see #6

**Comment by rodneymullen2** [comment]
same problem here

**Comment by OmarDTech** [comment]
I'm having the same issue.  "Error while fetching Google search API. Maybe usage limit? Please verify your keys."   I've obtained 2 different keys and verified the DNS to a personally owned domain.

**Comment by sundowndev** [comment]
I'll look into this for the next release. In meantime, I added a [tutorial](https://github.com/sundowndev/PhoneInfoga/wiki/Dealing-with-Google-captcha#how-to-create-a-google-custom-search-engine-api-key-and-cx-id) in the wiki to create a CSE API key.

**Comment by sundowndev** [comment]
From https://developers.google.com/custom-search/v1/overview#pricing : 
>Custom Search JSON API provides 100 search queries per day for free. If you need more, you may sign up for billing in the API Console. Additional requests cost $5 per 1000 queries, up to 10k queries per day.

Also the [ToS](https://developers.google.com/custom-search/terms) says : 
>The Custom Search API may be provided to you without any free usage quota at all. You may be charged for each successful request you make through the Custom Search API.

So I added an exception to know exactly what's the problem when using an API key, but the main problem seems to come from Google itself, and cannot be solved.

**Comment by sundowndev** [comment]
Closing since it doesn't seem to be a bug. Feel free to reopen to give further details.

Note that if you don't pay, having a free CSE key is mostly useless due to the poor free quota.

**Comment by darknodi** [comment]
You have not makest an tutorial for getting GOOGLE API KEY and CX ID fromSettings APP

**Comment by sundowndev** [comment]
@darknodi I did : https://sundowndev.github.io/PhoneInfoga/googlesearch/

**Comment by rodneymullen3** [comment]
anyone who found a solution?
config filled up.. 
"Error while fetching Google search API. Maybe usage limit ? Please verify your keys."
