### ISSUE TITLE
Links given do not work

### ISSUE THREAD

**Issue by Tufferz** [sundowndev/PhoneInfoga#502]
All the google links that that program gives to not work. They all take you to the google search that search "Didi you mean to say blah blah blah"

I think google blocks the use of some dorks like site:

**Comment by sundowndev** [comment]
Hi, Google links are auto generated. That means they do not necessarily return results.

**Comment by jepunband** [comment]
i don't get it, so what is the purpose of those links when no info can be obtained ?

**Comment by sundowndev** [comment]
Version 1 of PhoneInfoga was automatically scanning Google links to find results, but this feature had a technical limitation I wanted to remove on version 2.

As said in the readme:
> Usage of scanners was improved in order to drop usage of Selenium/Geckodriver which has cause many users to have troubleshoots using the tool. [...] Version 2 does not scan Google results anymore, [read more](https://sundowndev.github.io/PhoneInfoga/usage/#available-scanners).

In the docs:

> Google search uses Google search engine and Google Dorks to search phone number's footprints everywhere on the web. It allows you to search for scam reports, social media profiles, documents and more. **This scanner does only one thing**: generating several Google search links from a given phone number. You then have to manually open them in your browser to see results. You may therefore have links that do not return any results.

**Comment by aoandres** [comment]
would other search engine work like www.yandex.com or duckduckgo.com

**Comment by aoandres** [comment]
it`s an amazing tool "stale bot" it needs to be resolved and maintained considering scam calls(they drop the line and when you call back you get a huge phonebill) also to fish out suspissios calls to your phone...
