### ISSUE TITLE
Omacp

### ISSUE THREAD

**Issue by dank11** [sundowndev/PhoneInfoga#520]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by dank11** [comment]
Will you please send me a link to download

**Comment by sundowndev** [comment]
Please [read the docs](https://sundowndev.github.io/PhoneInfoga/install/#binary-installation-recommanded) if you want to download the tool.
