### ISSUE TITLE
Need to add Indian Mobile number database

### ISSUE THREAD

**Issue by tellmenot** [sundowndev/PhoneInfoga#521]
when i tried to perfrom an OSINT for a Indian number i can't able to gather any details listed form the tool. When i tried to open any url provided during the scanning process it turns out to be an empty google search result. Look over the issue if you have any free time, otherwise the tool works pretty fine. Thanks to  the developer for creating an awesome tool.

**Comment by sundowndev** [comment]
Hi, thanks for the kind words.

As said in previous issues : 
> Google links are auto generated. That means they do not necessarily return results.

...

> Version 1 of PhoneInfoga was automatically scanning Google links to find results, but this feature had a technical limitation I wanted to remove on version 2.
>
> As said in the readme:
>
>> Usage of scanners was improved in order to drop usage of Selenium/Geckodriver which has cause many users to have troubleshoots using the tool. [...] Version 2 does not scan Google results anymore, [read more](https://sundowndev.github.io/PhoneInfoga/usage/#available-scanners).
>
> In the docs:
>
>> Google search uses Google search engine and Google Dorks to search phone number's footprints everywhere on the web. It allows you to search for scam reports, social media profiles, documents and more. **This scanner does only one thing**: generating several Google search links from a given phone number. You then have to manually open them in your browser to see results. You may therefore have links that do not return any results.

**Comment by sundowndev** [comment]
I'm actually thinking about an option to enable Google scraping (which would be disabled by default) but this is not yet on the roadmap.
