### ISSUE TITLE
google CAPTCHA cookie

### ISSUE THREAD

**Issue by Manoj-hacker** [sundowndev/PhoneInfoga#53]
i have followed your step no error in project. this is only project i used without an error. Hats off..  to programmer, but i had issue from google. I'm not receiving the google abuse extension. how to get that cookie?

**Comment by sundowndev** [comment]
Thank you @Manoj-hacker.

Use [this topic](https://github.com/sundowndev/PhoneInfoga/issues/6) as reference for the google issue.
