### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION issue 

### ISSUE THREAD

**Issue by AlanShiah** [sundowndev/PhoneInfoga#533]
**Describe the bug**

Every time I paste in the value of the cookie into the terminal while the program is running, another blacklist comes up. I noticed that the blacklist keeps coming from the same website. I keep using the same google abuse exempt value but it never works. Ive refreshed the page, refreshed the storage in google, I've restarted my computer, downloaded your latest version, and tried everything I could think of.

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)
python3 phoneinfoga.py -n (phonenumber) --recon

**Expected behavior**

It worked the first few times. I expected it to do what it normally did, which is search through websites for matching phone numbers. I sometimes encountered the blacklist, but before I could get rid of it.

**Screenshots (optional)**
I don't think its necessary

**Desktop (please complete the following information):**
 Kali Linux 2020.2
V 2. (something) not sure

**Additional context**
The website it gets blocked on is the same. Everytime I open the link provided, the cookie is also always the same.

**Comment by sundowndev** [comment]
You're using v1.x which is deprecated. Please upgrade to v2.x.
