### ISSUE TITLE
Requirements file directory not found please HELP!!!

### ISSUE THREAD

**Issue by lucifer-des** [sundowndev/PhoneInfoga#541]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by DanielHNCT** [comment]
moi aussi je ne trouve pas

**Comment by Cupruminvictus** [comment]
I Lost my l9ve have only Phone number 🙏🙏🙏help

**Comment by sundowndev** [comment]
duplicate of #464 

>You're trying to install version 1.x of this program, please [read v2.x documentation](https://sundowndev.github.io/PhoneInfoga/).
>
>If you still want to use v1.x, read [this statement](https://github.com/sundowndev/PhoneInfoga#current-status). TL;DR: checkout on v1.11 tag.
