### ISSUE TITLE
Add support for changed carrier

### ISSUE THREAD

**Issue by d4rkc0nd0r** [sundowndev/PhoneInfoga#556]
I've scanned an Indian number, the results are correct except the carrier. I've changed that number's carrier last year from Tata Teleservices Ltd (TTSL) to Airtel but still its giving Tata Teleservices Ltd (TTSL).

**Comment by sundowndev** [comment]
Hi, carrier is found from public datasets and API scraping, it's nearly impossible to find the actual carrier with 100% accuracy.

A reminder from [the readme](https://github.com/sundowndev/PhoneInfoga#anti-features) :

> ## Anti-features
>
> - Does not claim to provide relevant or verified data, it's just a tool !
