### ISSUE TITLE
Not really an issue but request

### ISSUE THREAD

**Issue by Norseman2018** [sundowndev/PhoneInfoga#56]
So after running the tool and it gets all its results could it in a way collect all the positive results and spit them out as a different colour at the end??

**Comment by sundowndev** [comment]
What do you mean by "positive results" ?

**Comment by Norseman2018** [comment]
Okay so I mean when the scan has done it's thing after the whole captcha things it then runs through and checks the number against all these sites. If there's any matches then the site has a [+] next to it. 

Is there a way that all the [+] could be collected and grouped at the end and maybe like in a lighter green for instance. Maybe under a "RESULTS:" title? 

I hope that makes sense! Amazing tool by the way I love it!

**Comment by sundowndev** [comment]
I get your point, but you can already do that manually :

```shell
python phoneinfoga.py -n "+33 0620xxxxx" -s footprints --output scan.txt
```
then filtering results :
```shell
grep '^\[+\]' scan.txt
```
