### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by shin880** [sundowndev/PhoneInfoga#561]
**Describe the bug**
Not uninstalling when i use apt uninstall
**To Reproduce**
What command did you run ? sudo apt uninstall
**Expected behavior**
uninstall program

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04.1
 - PhoneInfoga exact version 2.3.5
 - Go exact version (if running it with Go) (run `go version`)(didnt show anything)
**Additional context**
I installed it with these instructions:  
# Download latest release in the current directory
curl -sSL https://raw.githubusercontent.com/sundowndev/PhoneInfoga/master/support/scripts/install | bash

# Check the binary
./phoneinfoga version

# You can also install it globally
sudo mv ./phoneinfoga /usr/bin/phoneinfoga 

and now i cant seem to uninstall it plz help googleing didnt help at all

**Comment by sundowndev** [comment]
Just remove the binary file to uninstall : 

```
rm -f ./phoneinfoga
```

**Comment by geet0107** [comment]
> Just remove the binary file to uninstall :
> 
> ```
> rm -f ./phoneinfoga
> ```

Can you kindly mention the full command...the above too doesnt seem to work...
