### ISSUE TITLE
Invalid format error on US number

### ISSUE THREAD

**Issue by mmarks9156** [sundowndev/PhoneInfoga#568]
**Describe the bug**
Unable to scan number using GUI

**To Reproduce**
Enter the following number both formats +18055551212 or 805551212 for US based number

**Expected behavior**
Scan to run for particular number

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/24350128/99578912-57cdc800-2992-11eb-94a0-f333c70a0b39.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux on Raspberry Pi 3
 - PhoneInfoga exact version 2.3.5 (cc79c08)

 - Go exact version (if running it with Go) (run `go version`)

**Additional context**
That is it for now.
![phoneinfoga](https://user-images.githubusercontent.com/24350128/99579250-c743b780-2992-11eb-9bf5-657920edfea7.PNG)

**Comment by sundowndev** [comment]
The input "+1805555xxxx" is working on my side with v2.3.5

![image](https://user-images.githubusercontent.com/16480203/99589670-a0b26a80-29ec-11eb-8ab5-39870cc0edb9.png)

**Comment by mmarks9156** [comment]
I downloaded the tar file for my platform. Is there something I need to do to check if demo or tool?

**Comment by sundowndev** [comment]
If it's the exact same version then it should work, please check your input and try again.

**Comment by mmarks9156** [comment]
I did a direct copy and paste from demo to tool and get same results. Very
strange?

**Comment by sundowndev** [comment]
Do you also get an error with the scan command?

**Comment by brentmaxwell** [comment]
I too got this same error.

I cloned the repo to a Raspberry Pi 4, and build the docker image using the included Dockerfile, and ran it with a simple basic Docker Compose based on the docs.
