### ISSUE TITLE
[INFO] This is how you make phoneinfoga work in termux android.

### ISSUE THREAD

**Issue by kcubeterm** [sundowndev/PhoneInfoga#573]
Here, I'm assuming.you have already installed phoneinfoga  in termux. Phoneinfoga is't a part of official repo yet so you have to install it via compiling from source or visit [Release page](https://github.com/sundowndev/PhoneInfoga/releases)

Basically You just need to run phoneinfoga under chroot/proot  or if you have already any Linux distro install  then phoneinfoga should work there. If you don't have any then don't worry I don't gonna tell you to install a proot-distro for just running a utility.

Here basically need to install `proot` and `resolv-conf`

```
pkg install proot resolv-conf
```
and execute phoneinfoga but here you just keep `termux-chroot` at beggining`
Eg.
```
termux-chroot ./phoneinfoga serve
```
and visit localhost:5000 
Alternatively you can run `termux-chroot` and perform task as usual. 

#### Video preview (asciicast)
https://asciinema.org/a/374616

**Comment by skylord0001** [comment]
Love you bro

But I haven't install the phoneinfoga

**Comment by eltontaah** [comment]
Tanxs bro

**Comment by Deadpool608** [comment]
How can I Install phoneinfoga for termux ??

**Comment by egge69** [comment]
How it work on android?

**Comment by kcubeterm** [comment]
@Deadpool608 Pre-compiled binary available [here ](https://github.com/sundowndev/phoneinfoga/releases)

@egge69 You can use phoneinfoga in Termux application. Install it from fdroid.

**Comment by ErvinWish** [comment]
Please help me to solve this error 
Permission denied 
![Screenshot_20210722-112717_Termux](https://user-images.githubusercontent.com/87798278/126596335-9630551f-731c-405e-ae99-719af1aed5a0.jpg)

**Comment by kcubeterm** [comment]
Try again after 
`chmod +x ~/phoneinfoga`

**Comment by ErvinWish** [comment]
> Try again after
> `chmod +x ~/phoneinfoga`

Not working 😕

![Screenshot_20210722-131556_Termux](https://user-images.githubusercontent.com/87798278/126605855-dc71c088-f389-4c25-b445-e48d68723bcb.jpg)

**Comment by kcubeterm** [comment]
Most probably you are executing directory instead of phoneinfoga binary.

**Comment by egge69** [comment]
Not work is skrip

**Comment by Ragithub93** [comment]
How can i fix this problem?? 
GOOGLE_ABUSE_EXEMPTION=

**Comment by CreeperCraftXD** [comment]
I need help how to run and install phoneinfoga

**Comment by Ligotzz** [comment]
I need help Ive downloaded infoga but it says it's not found 
![Screenshot_20240122-012802](https://github.com/sundowndev/phoneinfoga/assets/157304162/05b6760f-0168-47ac-9b69-47ff3aee0aa8)
![Uploading Screenshot_20240122-012828.jpg…]()

**Comment by mxprogrammer** [comment]
With the phoneinfoga not found, maybe it is in another file or maybe zip. Im not an expert but I am just trying to help.

**Comment by Natkirput95** [comment]
I can't find 'requirement.txt' in phoneinfoga.thats why I can't use it.i am a beginner.please help me to solve this kind of problems.

**Comment by skylord0001** [comment]
> I can't find 'requirement.txt' in phoneinfoga.thats why I can't use it.i am a beginner.please help me to solve this kind of problems.

create a requirements.txt file and add below

```
requests==2.21.0
bs4==0.0.1
html5lib==1.0.1
phonenumbers==8.10.2
argparse==1.2.1
urllib3==1.24.2
colorama==0.4.1
```

**Comment by kunal1234k** [comment]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirments 




please solve this issue

**Comment by arman55-coder** [comment]
File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
Can't understand the problem

**Comment by arman55-coder** [comment]
Dockerfile          examples
LICENSE             geckodriver.log
README.md           lib
__pycache__         mkdocs.yml
black.config.toml   osint
config.py           phoneinfoga.py
docker-compose.yml  requirements.txt
docker_push.sh      scanners
docs                tests
What to do here???

**Comment by shorts7spinz-arch** [comment]
> > Try again after
> > `chmod +x ~/phoneinfoga`
> 
> Not working 😕
> 
> ![Screenshot_20210722-131556_Termux](https://user-images.githubusercontent.com/87798278/126605855-dc71c088-f389-4c25-b445-e48d68723bcb.jpg)

**Comment by shorts7spinz-arch** [comment]
i want to format
@Deadpool608

**Comment by 1974jcllanas-coder** [comment]
$ termux-chroot ./phoneinfoga serve
sh: 1: ./phoneinfoga: Permission denied
~ $

**Comment by rsgod666** [comment]
~/PhoneInfoga $ python3 phoneinfoga.py -n +918329861830
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 14, in <module>
    from lib.request import send
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/request.py", line 8, in <module>
    import requests
  File "/data/data/com.termux/files/usr/lib/python3.13/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/data/data/com.termux/files/usr/lib/python3.13/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
    ...<3 lines>...
    )
  File "/data/data/com.termux/files/usr/lib/python3.13/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
    ...<13 lines>...
    )
  File "/data/data/com.termux/files/usr/lib/python3.13/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
        IncompleteRead as httplib_IncompleteRead
    )
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'


I am facing this problem please help me out
