### ISSUE TITLE
python3 -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by hrithikpopat** [sundowndev/PhoneInfoga#59]
whenever I type python3 -m pip install -r requirements.txt it says 
'python3' is not recognized as an internal or external command,
operable program or batch file. 
I don't know if I'm stupid or what.
(Thank you if any1 responds)

**Comment by sundowndev** [comment]
You simply don't have a "python3" executable. Try with `python` or just install python3.
If you are on linux you can also list python versions installed with `ls -la /usr/bin/python*`

**Comment by TharukaDananjaya** [comment]
You need to install python3

**Comment by hrithikpopat** [comment]
yea but I already have python 3.7.1 installed

**Comment by hrithikpopat** [comment]
![python](https://user-images.githubusercontent.com/51276945/58768864-fa537a80-8555-11e9-964f-e70130825385.PNG)

**Comment by TharukaDananjaya** [comment]
On windows os not support python3 command. and what is your python
version.? and show me list in you'r Phoneinfoga file.?

**Comment by sundowndev** [comment]
Does `python --version` output "Python 3.7.1" ?
If yes, run `python -m pip install --upgrade-pip` as described in your screenshot.
Then retry install via pip `python pip install -r requirements.txt`

**Comment by hrithikpopat** [comment]
It's still saying that there is no such thing as requirements.txt

**Comment by sundowndev** [comment]
Typo in my previous comment: `python -m pip install -r requirements.txt` *

Also what is the output of `ls -la .` in the folder ?

**Comment by hrithikpopat** [comment]
![python2](https://user-images.githubusercontent.com/51276945/58909995-4e32a080-86c9-11e9-8a99-52d9a3cc8a48.PNG)

**Comment by sundowndev** [comment]
You typed `python pip -m pip` instead of `python -m pip`

**Comment by hrithikpopat** [comment]
![python3](https://user-images.githubusercontent.com/51276945/58914768-34e32180-86d4-11e9-9eb4-fbdec1aebf29.PNG)

**Comment by hrithikpopat** [comment]
shoot i didn't realize

**Comment by sundowndev** [comment]
You are not in the repository's folder. Please read the doc properly.

**Comment by An-web** [comment]
I am facing the following issue while installing the requirements.txt in phoneinfoga.
![phoneinfoga_error](https://user-images.githubusercontent.com/62478377/77232054-c3258700-6bc4-11ea-8bb0-fb1c6872eb99.PNG)

**Comment by An-web** [comment]
I am using kali linux as windows subsystem btw.
