### ISSUE TITLE
Requirements.txt problem

### ISSUE THREAD

**Issue by LionEval** [sundowndev/PhoneInfoga#592]
Hello, I am new and still learning. I am using Linux as a sub-system to Windows 10.  I am trying to install the requirements.txt and I am getting the error message ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'.
I am not sure what I am doing wrong?

**Comment by sundowndev** [comment]
You're probably following an outdated tutorial. Please follow the official documentation which is always up to date : https://sundowndev.github.io/PhoneInfoga/install/

Feel free to reopen if you still need help.

**Comment by LionEval** [comment]
Im trying to see if I have phoneinfoga installed correctly and I am
getting these messages when trying to see the version I am running.


─(root💀LAPTOP-8K4FDDMO)-[/PhoneInfoga]
└─# python3 phoneinfoga.py -v
python3: can't open file 'phoneinfoga.py': [Errno 2] No such file or
directory
┌──(root💀LAPTOP-8K4FDDMO)-[/PhoneInfoga]
└─# python3 phoneinfoga -v
python3: can't open file 'phoneinfoga': [Errno 2] No such file or directory
┌──(root💀LAPTOP-8K4FDDMO)-[/PhoneInfoga]
└─#
