### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION

### ISSUE THREAD

**Issue by karthikamaravadi** [sundowndev/PhoneInfoga#60]
I tried searching for GOOGLE_ABUSE_EXEMPTION cookie in browser for mutilple test numbers. However, getting the same issue and also not able to find the cookie in the browser based on https://github.com/sundowndev/PhoneInfoga/wiki/Dealing-with-Google-captcha

PLease let me know if someone found a workaround.

**Comment by whitehatdev11** [comment]
I am having the exact same issue.

**Comment by ebubekirtrkr** [comment]
I have this issue as well,

**Comment by hunterxxx** [comment]
I am not able to find the captcha.

**Comment by AlexSSD7** [comment]
no GOOGLE_ABUSE_EXEMPTION cookie at all. same issue.

**Comment by ctZN27328** [comment]
i have the same issue, small workaround was opening the link in a browser where i am logged in with google account, searched/refreshed it 5 times, logged out, repeated search 3-5 times then logged in at which point google asked me if i'm a robot, confirmed it and loaded page with cookies

**Comment by Funeoz** [comment]
Same here in Firefox

**Comment by sundowndev** [comment]
Duplicate of #6
