### ISSUE TITLE
Mac OS NOT SUPPORTED

### ISSUE THREAD

**Issue by prajeshy** [sundowndev/PhoneInfoga#608]
prajeshyeotikar@PRAJESHs-MacBook-Pro ~ % curl -sSL https://raw.githubusercontent.com/sundowndev/PhoneInfoga/master/support/scripts/install | bash
Installing PhoneInfoga
Found version v2.3.7
Downloading version v2.3.7...
bash: line 14: wget: command not found
Verifying checksum...
bash: line 17: sha256sum: command not found
(23) Failed writing body
prajeshyeotikar@PRAJESHs-MacBook-Pro ~ % curl -sSL https://raw.githubusercontent.com/sundowndev/PhoneInfoga/master/support/scripts/install
#!/bin/bash

# Bash installation script for UNIX systems only
# Use it : curl -sSL https://raw.githubusercontent.com/sundowndev/PhoneInfoga/master/support/scripts/install | bash

os="$(uname -s)_$(uname -m)"

if [ $os == "Linux_x86_64" ] || [ $os == "Linux_armv6" ] || [ $os == "Darwin_x86_64" ] || [ $os == "Linux_arm64" ] || [ $os == "Linux_i386" ]; then
  echo "Installing PhoneInfoga"
  phoneinfoga_version=$(curl -s https://api.github.com/repos/sundowndev/PhoneInfoga/releases/latest | grep tag_name | cut -d '"' -f 4)
  echo "Found version $phoneinfoga_version"

  echo "Downloading version $phoneinfoga_version..."
  wget "https://github.com/sundowndev/phoneinfoga/releases/download/$phoneinfoga_version/PhoneInfoga_$os.tar.gz"

  echo "Verifying checksum..."
  curl -sSL https://github.com/sundowndev/PhoneInfoga/releases/download/$phoneinfoga_version/PhoneInfoga_checksums.txt | sha256sum -c --strict --ignore-missing
  [ $? -eq 0 ] || exit 1

  tar xfv "PhoneInfoga_$os.tar.gz"
  rm PhoneInfoga_$os.tar.gz

  echo "Installation completed successfully."
  echo "Verify installation : ./phoneinfoga version"
  echo "You can now install the program globally : sudo mv ./phoneinfoga /usr/bin/phoneinfoga"
else
  echo "Your OS/Arch is not supported."
  echo "Read more at https://sundowndev.github.io/PhoneInfoga/install/"
  exit 1
fi

exit 0
prajeshyeotikar@PRAJESHs-MacBook-Pro ~ % cd phoneinfoga/
cd: no such file or directory: phoneinfoga/
prajeshyeotikar@PRAJESHs-MacBook-Pro ~ % 
<img width="573" alt="Screenshot 2020-12-15 at 11 04 59 AM" src="https://user-images.githubusercontent.com/71869555/102175441-97220280-3ec5-11eb-97ee-5ca280c81b0b.png">

*******PLEASE HELP ME WITH THE INSTALLATION *******

**Comment by prajeshy** [comment]
My OS/Arch is : Darwin_x86_64

**Comment by sundowndev** [comment]
Hi, are you sure you have curl, wget, tar and sha256sum installed?

You can tell by using this command: `which curl`

**Comment by 0n1cOn3** [comment]
If those packages aren't installed, install brew (brew.sh) and install them with brew.

**Comment by prajeshy** [comment]
Oook
