### ISSUE TITLE
Docker image no longer available

### ISSUE THREAD

**Issue by Jamesking56** [sundowndev/PhoneInfoga#62]
**Describe the bug**
The docker install instructions in the wiki do not appear to work anymore due to the image being missing.

**To Reproduce**
`docker run --rm -it phoneinfoga/latest`

**Expected behavior**
Docker image is downloaded and a new container spawned.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python exact version (run `python --version`): N/A, Docker should handle this.

**Additional context**
Current output:

```
Unable to find image 'phoneinfoga/latest:latest' locally
docker: Error response from daemon: pull access denied for phoneinfoga/latest, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

I have tried `docker login` for `hub.docker.com`

**Comment by sundowndev** [comment]
You need to get the source code then build the image before running the tool.

```
# git clone ...
docker build --rm=true -t phoneinfoga/latest .
```
