### ISSUE TITLE
request failed object has no attribute 

### ISSUE THREAD

**Issue by amrazb** [sundowndev/PhoneInfoga#632]
<img width="775" alt="Screen Shot 2021-01-04 at 1 27 52 PM" src="https://user-images.githubusercontent.com/76973048/103579522-6d497380-4ea6-11eb-8938-312955a7cda0.png">

[!] ---- Fetching informations for 1xxxxxxxxxx ---- [!]
[-] Running local scan...
[+] International format: +1 xxxxxxxx
[+] Local format: 004xxxxxxxxxx
[+] Country found: United States (+1)
[+] City/Area: Pennsylvania
[+] Carrier: 
[+] Timezone: America/New_York
[-] The number is valid and possible.
[-] Running Numverify.com scan...
[+] Number: (+1) 4xxxxxxxx
[+] Country: United States of America (US)
[+] Location: Pttsbgzon1
[+] Carrier: T-Mobile USA Inc.
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[-] Running OVH scan...
[-] Running OSINT footprint reconnaissance...
[-] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/1-xxxxxxxxx
[-] Would you like to use an additional format for this number ? (y/N) n
[-] ---- Web pages footprints ----
[-] Searching for footprints on web pages... (limit=10)
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=1xxxxxxxxx1+%7C+intext%3A%221xxxxxxx1%22+%7C+intext%3A%22%2B1+xxxxxxx-xxx1%22&amp;gws_rd=ssl&amp;gl=us 

[-] Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=ID=458bce8c4019ecab:TM=16xxxxxx6:C=r:IP=xxxxxxxx-:S=APGng0vMcGzZVnPxP4OONqZ2MoZjaR7wMg
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for documents... (limit=10)
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] ---- Reputation footprints ----
[-] Searching for reputation report on whosenumber.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for phone fraud footprints...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for reputation report on findwhocallsme.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Generating URL on scamcallfighters.com...
[+] http://www.scamcallfighters.com/search-phone-1xxxxxxxxx1.html
[-] Would you like to search for temporary number providers footprints ? (Y/n) n
[-] ---- Social media footprints ----
[-] Searching for footprints on facebook.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on twitter.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on linkedin.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on instagram.com...
[-] ---- Phone books footprints ----
[-] Generating URL on True People... 
[+] https://www.truepeoplesearch.com/results?phoneno=+1xxxxxxxx1
[-] Searching for footprints on numinfo.net...
[-] Searching for footprints on sync.me...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on whocallsyou.de...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on pastebin.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on whycall.me...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Searching for footprints on locatefamily.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[-] Would you like to rerun OSINT scan ? (e.g to use a different format) (y/N) n
[-] Scan finished.

**Comment by sundowndev** [comment]
You're not using v2.x which is the only supported version. Please read docs at https://sundowndev.github.io/PhoneInfoga/
