### ISSUE TITLE
undefined: Assets - macOS Big Sure (macOS 11)

### ISSUE THREAD

**Issue by 0n1cOn3** [sundowndev/PhoneInfoga#633]
**Describe the bug**
gopkg.in/sundowndev/phoneinfoga.v2/api
api/server.go:41:26: undefined: Assets

**To Reproduce**
go run main.go

**Expected behavior**
Clean install and run of PhoneInfoga

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: macOS 11 - Big Sur
 - PhoneInfoga exact version: Latest (Git Clone 8. Jan. 2021 - 03.23 AM GMT +1)
 - Go exact version: go1.15.6 darwin/amd64

**Additional context**
I'll guess more infos aren't currently available.

**Comment by DwifteJB** [comment]
Same error on iOS 13.5 Jailbroken

**Comment by sundowndev** [comment]
You're trying to build the project from source, this is not recommended for users but [you can follow documentation here](https://sundowndev.github.io/PhoneInfoga/contribute/#building-from-source).

**Comment by C4l1b3r** [comment]
![Screenshot_20210302-090021_Termux](https://user-images.githubusercontent.com/17440115/109667440-bed44e80-7b35-11eb-90e0-abaaabce3058.jpg)

**Comment by sundowndev** [comment]
Did you build static assets then run go generate as stated in the doc ? https://sundowndev.github.io/PhoneInfoga/contribute/#building-from-source

**Comment by Zwiqler94** [comment]
I'm having the same issue. I tried running through the steps you mentioned here:

> Did you build static assets then run go generate as stated in the doc ? https://sundowndev.github.io/PhoneInfoga/contribute/#building-from-source

But when I try the `go generate ./...` I get this error `cannot find package "." in:
	/Users/jacobzwickler/PhoneInfoga/vendor/github.com/jessevdk/go-assets-builder
api/server.go:2: running "go": exit status 1`

**Comment by sundowndev** [comment]
> I'm having the same issue. I tried running through the steps you mentioned here:
> 
> > Did you build static assets then run go generate as stated in the doc ? https://sundowndev.github.io/PhoneInfoga/contribute/#building-from-source
> 
> But when I try the `go generate ./...` step, I get this error `cannot find package "." in: /Users/<username>/PhoneInfoga/vendor/github.com/jessevdk/go-assets-builder api/server.go:2: running "go": exit status 1`

@Zwiqler94 Did you make sure `client/dist` directory exists ?

**Comment by Zwiqler94** [comment]
> > I'm having the same issue. I tried running through the steps you mentioned here:
> > > Did you build static assets then run go generate as stated in the doc ? https://sundowndev.github.io/PhoneInfoga/contribute/#building-from-source
> > 
> > 
> > But when I try the `go generate ./...` step, I get this error `cannot find package "." in: /Users/<username>/PhoneInfoga/vendor/github.com/jessevdk/go-assets-builder api/server.go:2: running "go": exit status 1`
> 
> @Zwiqler94 Did you make sure `client/dist` directory exists ?

Yes, it exists.

**Comment by 0n1cOn3** [comment]
> Did you build static assets then run go generate as stated in the doc ? https://sundowndev.github.io/PhoneInfoga/contribute/#building-from-source

Mhm, no.... But would make sense °cringe°. I don't know where my eyes wen't.

**Comment by tammyharrell** [comment]
I didnt but someone is doing this using my info

**Comment by tammyharrell** [comment]
My camera wont work right someone changed my setting how can i fix it
