### ISSUE TITLE
No output for "footprint"

### ISSUE THREAD

**Issue by Th3-Think3r** [sundowndev/PhoneInfoga#65]
I have made it through the CAPTCHA issues, now I have two others. When attempting to do an output file (-o or >) it stops the scan at 411 and will not allow you to continue the script. Additionally, I am unsure what the output is for the "scanning for footprint". Is there an output for this at all? It looks like it is scanning for footprint and then just completes then stops with no output of results.

**Comment by sundowndev** [comment]
This is a known issue when using `-o` and `-s footprint` together.

From the [documentation](https://github.com/sundowndev/PhoneInfoga/wiki/Basic-usage#output-file)
>Note: --output is compatible with footprints scanner and recon option but you may have some issues. As input() function does not print before asking the user input, you may encounter empty input. I'm working on it.
