### ISSUE TITLE
PhoneInfoga V.2 on Pi4b_aarch64 Kali

### ISSUE THREAD

**Issue by chemist100** [sundowndev/phoneinfoga#651]
Has anyone successfully installed phoneinfoga V2 (latest) on Pi 4b using Kali Linux RaspberryPi 2, 3, 4 and 400 (img.xz), aarch64 kali linux image. I've downloaded the arm64 version of phoneInfogo and left in the downloads folder, I was able to open and see the files using the terminal but I can't access the program via ./phoneinfoga.. 

When I run the through the documentation installation procedures:
curl -sSL https://raw.githubusercontent.com/sundowndev/PhoneInfoga/master/support/scripts/install | bash

..I keeping getting an error message that aarch64 is not supported. What am I doing wrong?

I've been searching the interwebs like mad and I can't seem to find anything  as far as capability issue or a step by  install procedure.

If someone could get me going that would be great!

**Comment by Luvic95** [comment]
cd into the /support/scripts directory, then run the commands:
1) chmod +x install
2) ./install

worked on my kali distribution

**Comment by sundowndev** [comment]
The Docker image is now compatible with linux/arm64. Please ensure to use the `stable` or `v2` tag, not `latest`.
