### ISSUE TITLE
Support for termux ?

### ISSUE THREAD

**Issue by skullcrusher779** [sundowndev/PhoneInfoga#652]
I can't seem to get PhoneinfoGa working on termux as it is not supported by it. Im using someones else's git page copied from you from back when it contained the phoninfoga.py file.

How soon can we expect support for Termux in Android ?

**Comment by sundowndev** [comment]
See #573

**Comment by skullcrusher779** [comment]
Thanks a lot for the Information.. I'll close the issue.
👍👍👍❤️
