### ISSUE TITLE
can't search multible numbers at once

### ISSUE THREAD

**Issue by drlizner** [sundowndev/phoneinfoga#658]
the command i is not shown anywhere

**Comment by sundowndev** [comment]
Hi, this is a v1 feature that is has changed with v2. You can use the [REST API](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/sundowndev/PhoneInfoga/master/api/docs/swagger.yaml) to do that programmatically. But the `-i` option is not yet on the roadmap.

**Comment by drlizner** [comment]
Hello dear i installed the v1 and even so (i) command search in the first number of the list
