### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by martinfidjeland** [sundowndev/PhoneInfoga#682]
Hi.
My machine doesn't allow me to: "sudo mv ./phoneinfoga /usr/bin/phoneinfoga"
Error message: "mv: /usr/bin/phoneinfoga: Operation not permitted"

Machine running on:
macOS Big Sur V11.1

**Comment by sundowndev** [comment]
Hi, what's the value of your `$PATH` ?

**Comment by 758gianni** [comment]
look at this 
https://stackoverflow.com/a/38435256/14722616
