### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by Apolycious** [sundowndev/PhoneInfoga#695]
Hey, can you help me fixing the git clone issues? and can you make a tutorial on how to use it on windows?

Best Regards,
Apolycious

**Comment by sundowndev** [comment]
> Hey, can you help me fixing the git clone issues?

What are the "git clone issues" you're refering to ?

> and can you make a tutorial on how to use it on windows?

Simply download the binary and run it from the command line.

**Comment by Apolycious** [comment]
I mean, can you make a tutorial so it's **Easier** for me

**Comment by Apolycious** [comment]
Okay, It's working. Thank you
