### ISSUE TITLE
I have an error when installing. help 

### ISSUE THREAD

**Issue by VZLOMSHIKSAN4EK** [sundowndev/PhoneInfoga#696]
I am using terminal termux on android
 Here is the setup
git clone https://github.com/sundowndev/PhoneInfoga
Cloning into 'PhoneInfoga'...                         remote: Enumerating objects: 7792, done.

Everything went well
Further...

cd PhoneInfoga/
$ ls
CODEOWNERS  api     docs     mkdocs.yml     utils
Dockerfile  client  go.mod   renovate.json
LICENSE     cmd     go.sum   scanners
README.md   config  main.go  support

I enter the command ...

python3 -m pip install -r requirements.txt

And after this command it gives this

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

help here is a screen
![IMG_20210221_115117](https://user-images.githubusercontent.com/75779087/108621531-d75cae80-743b-11eb-8126-fdd989a178e5.jpg)

**Comment by sundowndev** [comment]
You're trying to install an old version of PhoneInfoga, which does not requires Python anymore. Please [read the documentation](https://sundowndev.github.io/PhoneInfoga/install/).
