### ISSUE TITLE
 ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by LoZio** [sundowndev/PhoneInfoga#70]
**Describe the bug**
After installing rquirements and starting I get:
ModuleNotFoundError: No module named 'config'

**To Reproduce**
Just run pip3 -r requirements.txt on a machine that does not have all the python stuff a dev uses

**Additional context**
To make it short just add "config" to the requirements. Once added manually it works.

**Comment by sundowndev** [comment]
>To make it short just add "config" to the requirements. Once added manually it works.

No, config is the config.py file. You have to create it manually, just read the wiki.

>Create the config file :
cp config.example.py config.py

**Comment by LoZio** [comment]
I read the docs. If you do not create the config file you get this:
```
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "./phoneinfoga.py", line 89, in <module>
    main()
  File "./phoneinfoga.py", line 70, in main
    scanNumber(args.number)
  File "./phoneinfoga.py", line 37, in scanNumber
    osintScan(number)
  File "/opt/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/opt/PhoneInfoga/lib/googlesearch.py", line 22, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

```

The error I reported is clearly about the module. 
`ModuleNotFoundError: No module named 'config'`
If you do not install the config module you don't even reach the point where the file config.py is read. Actually if you install the module the program runs.

**Comment by sundowndev** [comment]
You shouldn't have to add config to the requirements since the module is the file `config.py` and not the package config.

What is your OS, python and pip version ?

**Comment by LoZio** [comment]
pip 19.0.3 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
Linux xyz 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux (it is a raspbian on a raspberry)

Again: if you remove the *config.py FILE*, you have the error above about the **google_api_key** variable, and this makes sense since it is defined in that file.
The first error I reported is about a **module**, and if I add the module (forget about config.py file) the program runs. If I do a
`pip3 install config`
then the module is installed and the program runs.
You simply have the module already installed, but not all people have so the request to add it to the requirements.
In any case no problem for me adding it manually, I opened the issue to simplify the life to other people, we wrote a full page of comments while a simple line added to requirements.txt would have solved the issue.

**Comment by sundowndev** [comment]
But **the tool doesn't use any module named config**. The only call to config module actually makes reference to that file. That's why you shouldn't have to add config to the requirements, it's not a module.

https://github.com/sundowndev/PhoneInfoga/blob/c945b31267a396577649170ec248720fc0008d92/lib/googlesearch.py#L14

Maybe python just need a `_init_.py` ?

**Comment by Sathishkantamsetti** [comment]
I got the following errors after getting limited details of the number..
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/root/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


using Debian 9
Thank you

**Comment by sumsh** [comment]
@Sathishkantamsetti You are getting this error because gecko driver is not in path. Fix this by doing the following steps

- Goto [](https://github.com/mozilla/geckodriver/releases) and download the latest version of gecko driver for your platform

- Extract it using `tar -xvzf geckodriver*`

- Make it executable `chmod +x geckodriver`

- Move the driver to PATH by running `sudo mv geckodriver /usr/local/bin/`

Hope this might fix your problem

**Comment by Krishnao1** [comment]
this not working


> @Sathishkantamsetti You are getting this error because gecko driver is not in path. Fix this by doing the following steps
> 
>     * Goto [Gecko driver release page](https://github.com/mozilla/geckodriver/releases) and download the latest version of gecko driver for your platform
> 
>     * Extract it using `tar -xvzf geckodriver*`
> 
>     * Make it executable `chmod +x geckodriver`
> 
>     * Move the driver to PATH by running `sudo mv geckodriver /usr/local/bin/`
> 
> 
> Hope this might fix your problem

this is not working

**Comment by sundowndev** [comment]
https://github.com/sundowndev/PhoneInfoga/issues/74#issuecomment-500719025

>Running pip3 install config made it work

**Comment by LOKESHG1234** [comment]
![Screenshot from 2020-04-07 14-43-27](https://user-images.githubusercontent.com/63283533/78651635-3970fb80-78de-11ea-9700-4e931e3fa2e1.png)
After installing all the required modules it gave me the location of phone numbers but after that it ask for some formar Y or N whether i press yes or no it gives same error as shown in image
