### ISSUE TITLE
An error occured parsing phone number

### ISSUE THREAD

**Issue by NishanthGowda07** [sundowndev/PhoneInfoga#71]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - Python exact version (run `python --version`)

**Additional context**

**Comment by NishanthGowda07** [comment]
---- Fetching informations for 1837544833 ---- [!]
[*] Running local scan...
[!] Error: an error occured parsing 1837544833. Skipping.

**Comment by sundowndev** [comment]
The number is not valid. +18 or +183 does not belong to a valid country.

**Comment by tapeboxparts** [comment]
i am having the same issue. I am testing on my personal cell of witch i know is a valid ph#

**Comment by sundowndev** [comment]
@tapeboxparts @NishanthGowda07 What are the country codes ?

**Comment by NishanthGowda07** [comment]
+91

**Comment by sundowndev** [comment]
@NishanthGowda07 You wrote it wrong. Add the country code in the command : `python3 phoneinfoga.py -n "+xx xxxxxxxxxx"`

**Comment by kamesh413** [comment]
[!] ---- Fetching informations for xxxxxxxxx ---- [!]
[*] Running local scan...
[!] Error: an error occured parsing xxxxxxxx. Skipping but it is running number
