### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mikev1963** [sundowndev/PhoneInfoga#721]
**Describe the bug**
I get the following error when running docker run --rm -it sundowndev/phoneinfoga scan -n <number.

 An error occurred: Get "https://numverify.com/": x509: certificate has expired or is not yet valid: current time 2021-03-13T14:20:13Z is after 2021-03-13T12:00:00Z
[!] It may be Numverify not finding information about that number, or the number being invalid.

The number is valid.

**Comment by sundowndev** [comment]
This is an issue with Numverify website directly. The SSL certificate is not valid anymore. As numverify is an external service, the only thing we can do about that is to wait.

![image](https://user-images.githubusercontent.com/16480203/111039268-6d796880-842d-11eb-9c08-7b853926a236.png)

![image](https://user-images.githubusercontent.com/16480203/111039287-7a965780-842d-11eb-9d51-3aa14fd2e760.png)
