### ISSUE TITLE
Numverify: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by yung-dev** [sundowndev/PhoneInfoga#724]
when im running command docker run -it sundowndev/phoneinfoga scan -n 1 then the number and starts it it gives me a error code An error occurred: Get "https://numverify.com/": x509: certificate has expired or is not yet valid: current time 2021-03-14T01:12
:38Z is after 2021-03-13T12:00:00Z

**Comment by mikeysan** [comment]
Hi folks,

I would just like to add to this. When using the web interface all you get is "Numverify scan: An error occurred". There is no indication of what the error is. This is further compounded when you look at the logs (I am using docker). The logs simply state error 500.

Terminal:
![image](https://user-images.githubusercontent.com/13338176/111075286-32d00880-84df-11eb-8caa-acdede5e5867.png)

GUI:
![image](https://user-images.githubusercontent.com/13338176/111075310-55fab800-84df-11eb-94e0-53ced98ee8c3.png)

I hope this helps.

**Comment by BlasterV2** [comment]
Adjusting system time before 2021/03/13 allowed me to run command without errors temporary.

**Comment by yung-dev** [comment]
Okay thank. You

**Comment by sundowndev** [comment]
Read https://github.com/sundowndev/PhoneInfoga/issues/721#issuecomment-798700885

**Comment by sundowndev** [comment]
Numverify is back.
