### ISSUE TITLE
Checksum issue after using curl command for binary mode

### ISSUE THREAD

**Issue by nominomoses** [sundowndev/PhoneInfoga#729]
**Describe the bug**
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found

**To Reproduce**
curl -sSL https://raw.githubusercontent.com/sundowndev/PhoneInfoga/master/support/scripts/install | bash

**Expected behavior**
I was hoping to see the installation successful on my terminal on my kali linux terminal
![image](https://user-images.githubusercontent.com/28803815/111225221-e7d4f480-85b5-11eb-8c6c-322a82d5edc3.png)

**Comment by merianos** [comment]
I have the same problem.

**Comment by tanjilk** [comment]
Same 
```└──╼ $curl -sSL https://raw.githubusercontent.com/sundowndev/PhoneInfoga/master/support/scripts/install | bash
Installing PhoneInfoga
Found version v2.3.8
Downloading version v2.3.8...
--2021-03-16 08:58:16--  https://github.com/sundowndev/phoneinfoga/releases/download/v2.3.8/PhoneInfoga_Linux_x86_64.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-16 08:58:16 ERROR 404: Not Found.

Verifying checksum...
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
```

**Comment by sundowndev** [comment]
Looks like the latest release failed to deploy. I'll delete it for now, so you can use the v2.3.7 instead.

**Comment by sundowndev** [comment]
The release has been fixed, it should now work properly. Sorry for the inconvenience!

**Comment by Submarineu998** [comment]
I have similar problem 

"PhoneInfoga_Linux_x86_64.tar.gz.1’ saved [6188970/6188970]

Verifying checksum...
sha256sum: 'standard input': no file was verified
"

**Comment by pmburu** [comment]
Here is how I solved it. L17, L20, L21

```
#!/bin/bash

# Bash installation script for UNIX systems only
# Use it : curl -sSL https://raw.githubusercontent.com/sundowndev/phoneinfoga/master/support/scripts/install | bash

os="$(uname -s)_$(uname -m)"

if [ $os == "Linux_x86_64" ] || [ $os == "Linux_armv6" ] || [ $os == "Darwin_x86_64" ] || [ $os == "Darwin_arm64" ] || [ $os == "Linux_arm64" ] || [ $os == "Linux_i386" ]; then
  echo "Installing PhoneInfoga"
  phoneinfoga_version=$(curl -s https://api.github.com/repos/sundowndev/phoneinfoga/releases/latest | grep tag_name | cut -d '"' -f 4)
  echo "Found version $phoneinfoga_version"

  echo "Downloading version $phoneinfoga_version..."
  wget "https://github.com/sundowndev/phoneinfoga/releases/download/$phoneinfoga_version/phoneinfoga_$os.tar.gz"

  echo "Verifying checksum..."
  echo "$(curl -sSL https://github.com/sundowndev/phoneinfoga/releases/download/$phoneinfoga_version/PhoneInfoga_checksums.txt) phoneinfoga_$os.tar.gz" | sha256sum --strict --check --ignore-missing
  [ $? -eq 0 ] || exit 1

  tar xfv "phoneinfoga_$os.tar.gz"
  rm phoneinfoga_$os.tar.gz

  echo "Installation completed successfully."
  echo "Verify installation : ./phoneinfoga version"
  echo "You can now install the program globally : sudo mv ./phoneinfoga /usr/bin/phoneinfoga"
else
  echo "Your OS/Arch is not supported."
  echo "Read more at https://sundowndev.github.io/phoneinfoga/install/"
  exit 1
fi

exit 0

```

The checksums file has named the files in lowercase followed by underscore then, upper case. However, the script produces camel-case-named output. Therefore sha256sum -c wouldn’t find the same file. Also according to a solution I found on [Stackexchange](https://bit.ly/3sNdi6o),  when comparing between two files an echo comes in handy.

**Comment by sundowndev** [comment]
@pmburu Could you make a PR to fix this ? Thanks a lot 🙏🏻

**Comment by Vista6003** [comment]
@pmburu 
i did it and it worked. i didnt need to use the other commands. i just copied your codes, pasted them and then installed phoneinfoga again and this time checksum worked.

thanks
