### ISSUE TITLE
Documentation Page not found

### ISSUE THREAD

**Issue by LineOfCodeboi** [sundowndev/phoneinfoga#756]
**Describe the bug**
When clicked on the documentation page, the site gives a 404 Page not found. I don't know why it would do that or if it's on me, but it doesn't work!

**To Reproduce**
Click on Documentation in the README file.

**Comment by sundowndev** [comment]
I recently renamed the project from PhoneInfoga to phoneinfoga, I forgot about the doc URL https://sundowndev.github.io/phoneinfoga/

Thanks!
