### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION=

### ISSUE THREAD

**Issue by A2hari** [sundowndev/PhoneInfoga#76]
This usuall asks for a value to be given and It is not acceping the values i gave or the cookie .how to solve this GOOGLE_ABUSE_EXEMPTION= problem when occured

**Comment by sundowndev** [comment]
A fix has been deployed on the develop branch and will be deployed on the master branch very soon. See https://github.com/sundowndev/PhoneInfoga/issues/6#issuecomment-500507237
