### ISSUE TITLE
Indian phone numbers are not working 

### ISSUE THREAD

**Issue by gokuljs** [sundowndev/phoneinfoga#768]
No matter what format I try in the google dork or even the web interface of the cloud console Indian numbers will not work. It shows all the footprint correctly but the link is not accessible because the number format is not correct

**Comment by sundowndev** [comment]
> the link is not accessible because the number format is not correct

Can you elaborate on that? What makes the format incorrect?

**Comment by gokuljs** [comment]
![Screenshot (235)](https://user-images.githubusercontent.com/51263906/114381758-1d670080-9ba9-11eb-9269-acd0bbda16db.png)

**Comment by gokuljs** [comment]
So in the search field, the number format should be different right. it depends on how each domina has stored number in database right.

**Comment by sundowndev** [comment]
> So in the search field, the number format should be different right. it depends on how each domina has stored number in database right.

What should it be different ? Can you provide an example ? Not sure which format you're expecting there

**Comment by kanishkthamman** [comment]
hi,
the format for indian numbers would be "+91 xxxx-nnnnnn"
hope this helps

**Comment by sundowndev** [comment]
Addressed in #1312 

Please give feedback
