### ISSUE TITLE
zsh: permission denied: phoneinfoga

### ISSUE THREAD

**Issue by voldemort0711** [sundowndev/phoneinfoga#769]
i tried to run **_phoneinfoga scan -n_** 

and it appear a text appeared saying  **zsh: permission denied: phoneinfoga**

what can i do to fix that?

**Comment by sundowndev** [comment]
Did you ensure you have permission to launch the program?

```
$ chmod +x ./phoneinfoga
```

**Comment by MhanzalaMalik** [comment]
thanks it was downloaded

**Comment by voldemort0711** [comment]
> Did you ensure you have permission to launch the program?
> 
> ```
> $ chmod +x ./phoneinfoga
> ```
yes but " chmod: changing permissions of './phoneinfoga': Operation not permitted"

**Comment by sundowndev** [comment]
> > Did you ensure you have permission to launch the program?
> > ```
> > $ chmod +x ./phoneinfoga
> > ```
> 
> yes but " chmod: changing permissions of './phoneinfoga': Operation not permitted"

Where is the executable located at ? Can you retry with `sudo chmod u+x ./phoneinfoga` ?

**Comment by Popzindawood** [comment]
@sundowndev 

Hello sundowndev,

I got the same problem as voldemort.
I tried the chmod +x ./phoneinfoga but nothings happened. don't know why.
I ran it as administrator btw but still doesn't work..

**Comment by Drigozx** [comment]
same here

**Comment by reve23** [comment]
it's not working

**Comment by sam3012** [comment]
> it's not working I used chmod +x ./phoneinfoga while i'm the root user but nothing happend

same here

**Comment by sam3012** [comment]
please tell us something

**Comment by samiii4me** [comment]
you can use docker instead
here you can see https://www.youtube.com/watch?v=6CnDdXVTxhU

**Comment by Mateen-Web** [comment]
https://youtu.be/FVzNaMWJHWo reffer to this video was pretty easy to download

**Comment by GMZF** [comment]
Guys 
In the installation it says "sudo mv ./phoneinfoga /usr/bin/phoneinfoga" right? 
- sudo su 
- cd /usr/bin/phoneinfoga
- ./phoneinfoga

That's it.

**Comment by AlfaStalker** [comment]
zsh: permission denied: phoneinfoga

**Comment by sundowndev** [comment]
Closing since there was no response from the OP.

**Comment by asentroy** [comment]
phoneinfoga scan -n (number) 
if I run this command then show me { phoneinfoga: commend not found}
what should I do now?

**Comment by sundowndev** [comment]
Don't forget the `./` in `./phoneinfoga`
