### ISSUE TITLE
/ wiki-Documentation Page not found 

### ISSUE THREAD

**Issue by ShahriarShafin** [sundowndev/phoneinfoga#777]
**Describe the bug**
Change the doc URL of [wiki](https://github.com/sundowndev/phoneinfoga/wiki)
https://sundowndev.github.io/PhoneInfoga/ --> https://sundowndev.github.io/phoneinfoga/

**To Reproduce**
Click on "**Documentation has been moved here**" on Wiki page

**Comment by sundowndev** [comment]
Done, thank you 👍🏽
