### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory 'Requirements.txt'

### ISSUE THREAD

**Issue by ApexDex** [sundowndev/phoneinfoga#780]
After doing:

cd PhoneInfoga
ls

and attempting:

python 3 -m pip install -r requirements.txt

the error pops up in v2.3.8 in Git Bash where 'ls' does not work in cmd/python/git CMD
Where you are prompted with (after doing cd phoneinfoga):

"'ls' is not recognized as an internal or external command operable program or batch file."
Using both Ubuntu and Windows 10 64bit

**Comment by sundowndev** [comment]
You are trying to install version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/) to install version 2.

**Comment by ApexDex** [comment]
The documentation link has and error 404, or is that just me?

**Comment by sundowndev** [comment]
> The documentation link has an error 404, or is that just me?

Sorry, it's fixed now
