### ISSUE TITLE
error while installation 

### ISSUE THREAD

**Issue by manbeersingh1300** [sundowndev/phoneinfoga#795]
following error is coming while installation on Debian 10

root@cat:/opt# curl -sSL https://raw.githubusercontent.com/sundowndev/phoneinfoga/master/support/scripts/install | bash
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection timed out

**Comment by sundowndev** [comment]
Working fine on my hand, it might be a temporary issue with GitHub. Can you try again?
