### ISSUE TITLE
Numverify.com is not available

### ISSUE THREAD

**Issue by kiyani21** [sundowndev/phoneinfoga#799]
**Describe the bug**
Numverify.com is not available

**To Reproduce**
phoneinfoga.py -n

**Expected behavior**
I run the command but i can't get information if i run the generate link in the browser i tried many browsers for it but same problem 

**Screenshots (optional)**
![Screenshot_2021-05-01-17-27-35-525_com UCMobile intl](https://user-images.githubusercontent.com/72380212/116782500-e64a8780-aaa2-11eb-9d40-37d431f65a4a.jpg)
![Screenshot_2021-05-01-17-27-01-390_com termux](https://user-images.githubusercontent.com/72380212/116782508-f1051c80-aaa2-11eb-8cea-0727d76f26f8.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by sundowndev** [comment]
You are trying to use version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2. Also Numverify works fine with version 2.

**Comment by kiyani21** [comment]
So how to update it to v2 i don't understand send some commands ?

**Comment by MuhammadTaha2** [comment]
![phoneinfoga](https://user-images.githubusercontent.com/89296110/210522510-7f85981b-826a-4422-8632-50197eec80e9.png)
Dear Sundown Dev,

Its showing me the following error and this version doesn't even tell the carrier or other information as the pervious
