### ISSUE TITLE
Error geckodriver 

### ISSUE THREAD

**Issue by thesuhu** [sundowndev/PhoneInfoga#82]
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

I am using termux

**Comment by thesuhu** [comment]
Package is now available.
Run with these commands:

pkg install unstable-repo
pkg install geckodriver

**Comment by popduck07** [comment]
The commands don't do anything?

**Comment by popduck07** [comment]
I have the same issue but simply typing "pkg install geckodriver" comes up with E: Invalid operation pkg
