### ISSUE TITLE
demo instance is ok

### ISSUE THREAD

**Issue by tracey-s-hand** [sundowndev/phoneinfoga#822]
https://demo.phoneinfoga.crvx.fr/#/

Numverify scan.  Valid aways False . server is ok?

@sundowndev 

![image](https://user-images.githubusercontent.com/77158530/118353930-2b080100-b52e-11eb-8b19-6102593c12e8.png)

**Comment by sundowndev** [comment]
The readme says : 
> About demo instance: This is a test service. Kittens will die if you abuse it. Numverify scan is pointless because my server's IP got blocked due to spam.
