### ISSUE TITLE
Web client doesn't work. Terminal does.

### ISSUE THREAD

**Issue by seamasteruwu** [sundowndev/phoneinfoga#823]
**Describe the bug**
When I use the web client it always give the errror "Parameter 'number' must be a valid integer." however with the same number in the terminal it works and it gives me the info.

**To Reproduce**
phoneinfoga scan -n +58-412-4000-325
(not censoring it since it's false)
Scan the same number in web client

**Expected behavior**
Give me the info and say that it is false

**Screenshots (optional)**

**Desktop (please complete the following information):**
PhoneInfoga 2.3.8 (8403f33)

**Comment by sundowndev** [comment]
Hi, for some reason I'm unable to reproduce this. I made a patch for this but got unreleased yet (https://github.com/sundowndev/phoneinfoga/pull/757). Could you pull Docker image on the latest tag and try again? The error will still be there but it should be more explicit. Be sure to use linux/amd64 arch to run this image. Thanks!

**Comment by C4l1b3r** [comment]
I didn't know there was a web client version

**Comment by orojina** [comment]
Same issue here, running phoneinfoga on a raspberrypi 4 (using the docker **stable** tag   linux/arm/v7)
![image](https://user-images.githubusercontent.com/11845190/123369011-773d5c80-d542-11eb-8d99-03f69ba68b43.png)

**Comment by funkymonkey5150** [comment]
I'm having the same issue soon as I get home I will post the output in and cold so that you can give me some feedback￼

**Comment by cycool29** [comment]
Did the issue fixed? I am using RPI4 and face the same issue.
