### ISSUE TITLE
« Valid: false » on all scans

### ISSUE THREAD

**Issue by ghost** [sundowndev/phoneinfoga#826]
Hi,

So I've been using PhoneInfoga for the first time and I think I might have an issue. 
When I try to launch a scan, the local scan never finds the carrier. Plus, the other scans always return "Valid: false" and don't give me any information.
I've tried with my own phone number and always the same results (or non-results here). 

Thanks for your help.

**Comment by DemonKnight01** [comment]
I also got "Valid : false on all scan". I can't get any information from the number only country is given. Im using phoneinfoga on googlecloudplatform.

**Comment by GhostHardware-017** [comment]
> I also got "Valid : false on all scan". I can't get any information from the number only country is given. Im using phoneinfoga on googlecloudplatform.

I've tried with the Ubuntu Terminal and with the web UI, though : same results.

**Comment by sundowndev** [comment]
Phoneinfoga relies on external services, mostly using scraping. Those services can be unavailable at any time. If you think this is a false negative, then it's most likely an error from Numverify API. And there's nothing we can do about that.

**Comment by GhostHardware-017** [comment]
> Phoneinfoga relies on external services, mostly using scraping. Those services can be unavailable at any time. If you think this is a false negative, then it's most likely an error from Numverify API. And there's nothing we can do about that.

Thanks for your quick answer.
So I guess PhoneInfoga just can't be used right now? 
The only working scan of the 3 is the local one. Numverify returns **valid:false** and so does the OVH API scan (which could be understable as I've tried with personal numbers). Can you confirm that by trying to scan your own number for example?

**Comment by C4l1b3r** [comment]
![Screenshot_20210526-144618_Termux](https://user-images.githubusercontent.com/17440115/119721788-29451400-be31-11eb-9586-c6bddfe0eb94.jpg)

**Comment by Teslaian** [comment]
Yes! I am even facing the same issue. I am wondering when would this issue get resolved.

**Comment by funkymonkey5150** [comment]
I have the same issue it seems to be something that they have no control over I know that I've tried it many times throughout the day and even throughout the month and I still keep getting the same thing can somebody please help this can be a very helpful I'll fix￼

**Comment by TemplarPirate** [comment]
Me too!

**Comment by Avichiii** [comment]
me too. i hope they fix it soon, otherwise this tool is no use for me.

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).

**Comment by RanL85** [comment]
I am using Phoneinfoga on the OSINT VM I installed on VirtualBox. When I run scans I see the carrier information and city for example which changes with every scan so I know its valid but my issues are

changes but the good intel below such as personal identifiers and social media, well they all stay the same for every scan regardless of the number.

The links of information show up as nothing on google.

banging my head here.... Thank all cheers
