### ISSUE TITLE
hi bro ,

### ISSUE THREAD

**Issue by frogtasty** [sundowndev/phoneinfoga#830]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by frogtasty** [comment]
with lot of trouble i was able to get phoneinfoga up and running 
after running "   cd ./PhoneInfoga   "
i typed "     python3 phoneinfoga.py     "
but nothing happened and its showing " python3: can't open file '/home/frog/PhoneInfoga/PhoneInfoga.py': [Errno 2] No such file or directory "

**Comment by arman55-coder** [comment]
python: can't open file '/data/data/com.termux/files/home/PhoneInfoga/PhoneInfoga.py': [Errno 2] No such file or directory 
How to solve???

**Comment by arman55-coder** [comment]
![Image](https://github.com/user-attachments/assets/b03db919-1395-4a4e-9899-9b39de7d8959)

![Image](https://github.com/user-attachments/assets/eb5c98d1-7be0-4dfa-a892-fb75fe9d851e)

![Image](https://github.com/user-attachments/assets/5dbf6664-7f19-498d-99b7-cffa7494672e)
