### ISSUE TITLE
Temporary blocked by Google.... blacklisted

### ISSUE THREAD

**Issue by Mayor294** [sundowndev/phoneinfoga#843]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**
It Keeps telling me request failed retry [!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for documents... (limit=10)
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] ---- Reputation footprints ----
[i] Searching for reputation report on whosenumber.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for phone fraud footprints...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for reputation report on findwhocallsme.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for reputation report on yellowpages.ca...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for reputation report on phonenumbers.ie...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for reputation report on who-calledme.com...
[i] Searching for reputation report on usphonesearch.net...
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=site%3Ausphonesearch.net+for+903+859+6704+OR+%22903+859+6704%22&num=1&amp;gws_rd=ssl&amp;gl=us
[i] Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=https://www.google.com/search?tbs=li:1&q=site%3Ausphonesearch.net+for+903+859+6704+OR+%22903+859+6704%22&num=1&amp;gws_rd=ssl&amp;gl=us
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for reputation report on whocalled.us...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for reputation report on quinumero.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for reputation report on uk.popularphotolook.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Generating URL on scamcallfighters.com...
[+] http://www.scamcallfighters.com/search-phone-2349038596704.html
Would you like to search for temporary number providers footprints ? (Y/n) Y
[i] ---- Temporary number providers footprints ----
[i] Searching for phone number on tempophone.com...
[i] Searching for footprints on hs3x.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on receive-sms-now.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on smslisten.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on smsnumbersonline.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on freesmscode.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on catchsms.com...
[i] Searching for footprints on smstibo.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on smsreceiving.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on getfreesmsnumber.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on sellaite.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on receive-sms-online.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on receivesmsonline.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on receive-a-sms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on sms-receive.net...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on receivefreesms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on receive-sms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on receivetxt.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on freephonenum.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on freesmsverification.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on receive-sms-online.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on smslive.co...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] ---- Social media footprints ----
[i] Searching for footprints on facebook.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on twitter.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on linkedin.com...
[i] Searching for footprints on instagram.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] ---- Phone books footprints ----
[i] Searching for footprints on numinfo.net...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on sync.me...
[i] Searching for footprints on whocallsyou.de...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on pastebin.com...
[i] Searching for footprints on whycall.me...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
[i] Searching for footprints on locatefamily.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
'NoneType' object has no attribute 'find_all'
Would you like to rerun OSINT scan ? (e.g to use a different format) (y/N) y
[*] Running OSINT footprint reconnaissance...
[i] We recommand: +234 903 859 6704 or 903 859 6704
Custom format: +234 903 859 6704
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=2349038596704+OR+%222349038596704%22+OR+%22%2B234+903+859+6704%22+OR+%22%2B234+903+859+6704%22&num=10&amp;gws_rd=ssl&amp;gl=us
[i] Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=https://www.google.com/search?tbs=li:1&q=2349038596704+OR+%222349038596704%22+OR+%22%2B234+903+859+6704%22+OR+%22%2B234+903+859+6704%22&num=10&amp;gws_rd=ssl&amp;gl=us
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=2349038596704+OR+%222349038596704%22+OR+%22%2B234+903+859+6704%22+OR+%22%2B234+903+859+6704%22&num=10&amp;gws_rd=ssl&amp;gl=us
[i] Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=https://www.google.com/search?tbs=li:1&q=2349038596704+OR+%222349038596704%22+OR+%22%2B234+903+859+6704%22+OR+%22%2B234+903+859+6704%22&num=10&amp;gws_rd=ssl&amp;gl=us
(!) You are temporary blacklisted from Google search. Complete the captcha at the following URL and copy/paste the content of GOOGLE_ABUSE_EXEMPTION cookie : https://www.google.com/search?tbs=li:1&q=2349038596704+OR+%222349038596704%22+OR+%22%2B234+903+859+6704%22+OR+%22%2B234+903+859+6704%22&num=10&amp;gws_rd=ssl&amp;gl=us
[i] Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=

**Comment by sundowndev** [comment]
You are trying to use version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
