### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by Conqueriings** [sundowndev/phoneinfoga#844]
──(parallels㉿ParallelConqueriings)-[~]
└─$ docker pull sundowndev/phoneinfoga:latest                                                  1 ⨯
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=sundowndev%2Fphoneinfoga&tag=latest": dial unix /var/run/docker.sock: connect: permission denied

help please...

**Comment by sundowndev** [comment]
Works fine on my side, looks like an issue with your Docker installation.

```
docker pull sundowndev/phoneinfoga:latest
latest: Pulling from sundowndev/phoneinfoga
ca3cd42a7c95: Pull complete 
dbcca316e5c3: Pull complete 
b65b403d39c8: Pull complete 
0d70e27e35eb: Pull complete 
a8bdf7aa1b33: Pull complete 
85a91435787c: Pull complete 
b2ec530298d9: Pull complete 
Digest: sha256:1b2f2ef943f9109a1eb0198e7e1f0b1f705c3117280db8e31439fc14ae762b06
Status: Downloaded newer image for sundowndev/phoneinfoga:latest
docker.io/sundowndev/phoneinfoga:latest
```

Can retry with sudo ? If it works with sudo, you need to add the current user to the docker group ([there's plenty of tutorials to help you achieve this](https://linuxhandbook.com/docker-permission-denied/)).

**Comment by Conqueriings** [comment]
I have found another way of installing it, thank you!

**Comment by mario0101976** [comment]
суб, 26. јун 2021. 10:55 Raphaël ***@***.***> је написао/ла:
