### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by AidilHizwan** [sundowndev/phoneinfoga#846]
i had trying a lot of time and this happen to me.. someone help me to solve this i'm gonna stress about this

python3 phoneinfoga.py                    
python3: can't open file '/home/user/PhoneInfoga/phoneinfoga.py': [Errno 2] No such file or directory

**Comment by sundowndev** [comment]
You are trying to use version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
