### ISSUE TITLE
google api i was given but it was asking again and again

### ISSUE THREAD

**Issue by kyeswanthreddy** [sundowndev/PhoneInfoga#85]
![Screenshot from 2019-06-15 17-06-18](https://user-images.githubusercontent.com/34566338/59550978-fbae7b00-8f37-11e9-938d-bc5769898457.png)
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - Python exact version (run `python --version`)

**Additional context**

**Comment by sundowndev** [comment]
You didn't created the config file.

Also leaking your phone number and Google API keys, nice.

**Comment by kyeswanthreddy** [comment]
how to create config file
