### ISSUE TITLE
+19586322478

### ISSUE THREAD

**Issue by peyman13671368** [sundowndev/phoneinfoga#852]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - PhoneInfoga exact version (run `phoneinfoga version`)
 - Go exact version (if running it with Go) (run `go version`)

**Additional context**

**Comment by peyman13671368** [comment]
+989106250252

**Comment by Crilinkzxx** [comment]
The commands are running on kali linux.I was only confused because the
requirements.txt was not there and I have figured it out.
