### ISSUE TITLE
How to install on parrotOS ?

### ISSUE THREAD

**Issue by rigmod31** [sundowndev/phoneinfoga#856]
can anyone please help me install phoneinfoga on parrotOs. i have tried a couple of videos on youtube i just cant seem to find a way to install the tool on my parrotOs.thank you in advance

**Comment by sundowndev** [comment]
@rigmod31 ParrotOs is debien based so it should support PhoneInfoga. You can follow the install instructions like any other linux distro.

**Comment by rigmod31** [comment]
I ended up changing to kali it installed well there but then failed to use it I cant get anymore information other than country code

**Comment by sundowndev** [comment]
> I ended up changing to kali it installed well there but then failed to use it I cant get anymore information other than country code

OSINT is not about magic and can sometimes not be efficient at all. For this reason I've opened #967, so we can support more source of information.

I'm closing this issue since it's now solved.
