### ISSUE TITLE
?

### ISSUE THREAD

**Issue by NotAnAlienz** [sundowndev/phoneinfoga#858]
~ % curl -sSL https://raw.githubusercontent.com/sundowndev/phoneinfoga/master/support/scripts/install | bash

Installing PhoneInfoga
Found version v2.3.8
Downloading version v2.3.8...
bash: line 14: wget: command not found
Verifying checksum...
bash: line 17: sha256sum: command not found
(23) Failed writing body

**Comment by BladVlad** [comment]
Same problem, I have python 3 and it still won’t install phoneinfoga. I either get that message or a permission error.

**Comment by sundowndev** [comment]
You need wget, tar and sha256sum to run the install script. Be sure install them before.

**Comment by NotAnAlienz** [comment]
> You need wget, tar and sha256sum to run the install script. Be sure install them before running the script.


epalpa@Brons-MacBook-Pro ~ % ./phoneinfoga version
[i] PhoneInfoga 2.3.8 (8403f33)
[i] Maintained by sundowndev https://github.com/sundowndev/PhoneInfoga
epalpa@Brons-MacBook-Pro ~ % python3 phoneinfoga.py -v
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: can't open file '/Users/epalpa/phoneinfoga.py': [Errno 2] No such file or directory
epalpa@Brons-MacBook-Pro ~ % 


i installed those 3, it successfully installed phoneinfoga, but when u go to run it i get directory issues

**Comment by NotAnAlienz** [comment]
nvm, i got it to run successfully, thanks for the help!
