### ISSUE TITLE
valid:false for real numbers

### ISSUE THREAD

**Issue by shayide** [sundowndev/phoneinfoga#861]
I tried phoneinfoga with Google Cloud Shell and typed in my personal number, my friends', numbers of people living in US and UK and it still returned as valid:false. 

I signed up for **numverify.com** and tried those numbers once again, and they all returned as valid:true and provided carrier info and location and stuff. 

Example for a contact in US: docker run -it sundowndev/phoneinfoga scan -n 146924XXXXX

**Comment by Avichiii** [comment]
really? will it work?

**Comment by JohannesMogashoa** [comment]
I got the same issue. I ran my own personal number, South African International Code, and got invalid, but tried numverify.com and i got back the relevant details regarding the number

**Comment by wedataintelligence** [comment]
thank you

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).
