### ISSUE TITLE
Tool not working 

### ISSUE THREAD

**Issue by ryder-riding** [sundowndev/phoneinfoga#865]
**Describe the bug**
when i tried to scan my phone number it said false but it is a real phone number and the country code is india 

**To Reproduce**
./phoneinfoga scan -n 91**********

**Expected behavior**
give information about the number 

**Screenshots (optional)**
<img width="196" alt="Screenshot 2021-07-25 225235" src="https://user-images.githubusercontent.com/64404240/126907760-c242abeb-efaa-433b-9952-ad3c93730858.png">

**Desktop (please complete the following information):**
 - OS: kali linux 5.10.19
 - PhoneInfoga exact version: 2.3.8

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).
