### ISSUE TITLE
How to clone phoneinfoga in root mode in linux virtual environment?

### ISSUE THREAD

**Issue by nazam1142** [sundowndev/phoneinfoga#867]
I want to clone phoneinfoga in root mode but url is not accessing. please help me,

**Comment by sundowndev** [comment]
The Git URL has always been the same : `https://github.com/sundowndev/phoneinfoga.git`. What do you mean "url is not accessing" ?

**Comment by bigcheese218** [comment]
> The Git URL has always been the same : `https://github.com/sundowndev/phoneinfoga.git`. What do you mean "url is not accessing" ?

" remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/sundev/PhoneInfoga/' "

**Comment by sundowndev** [comment]
This seems to be an issue with your environment. Closing for invalidity.
