### ISSUE TITLE
French Phone number not working

### ISSUE THREAD

**Issue by HugoMskn** [sundowndev/phoneinfoga#902]
**Describe the bug**
Well every french number that i'm trying are "false" but on numverify it's valid and show me somes infos on it 

**To Reproduce**
phoneinfoga scan -n +3378******

**Expected behavior**
Informations of the phone number 

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: Kali Linux 2021.3
 - PhoneInfoga : 2.3.8
![ksnip_20210923-233613](https://user-images.githubusercontent.com/81116453/134587688-9c362398-8c90-4336-85a7-19bfeb3f59b5.png)
e
![ksnip_20210923-233432](https://user-images.githubusercontent.com/81116453/134587679-1a1843d0-f141-439f-9e37-b2caadebc495.png)

![ksnip_20210923-233650](https://user-images.githubusercontent.com/81116453/134587692-1ac97b31-1707-4d76-8fdd-c66144fe9649.png)

**Comment by sundowndev** [comment]
Hi @HugoMskn , thanks for your issue.

The valid field indicate whever the number is recognized by the Numverify API or not. In your last screenshot, the Numverify scan seems to work as expected, did you use the demo instance or a self hosted instance ?

From the readme:
> **About demo instance**: This is a test service. Kittens will die if you abuse it. Numverify scan is pointless because my server's IP got blocked due to spam.

**Comment by HugoMskn** [comment]
I used the self hosted instance with the port 8080

**Comment by terrala** [comment]
Can somebody help me with this?

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).
