### ISSUE TITLE
All phone numbers regardless of voip or cell carrier shows valid false.

### ISSUE THREAD

**Issue by Kashutu** [sundowndev/phoneinfoga#904]
**Describe the bug**
All phone numbers regardless of voip or cell carrier shows valid false.

**To Reproduce**
./phoneinfoga scan -n 1**********

**Expected behavior**
A true statement of valid phone number.

**Desktop (please complete the following information):**
 - OS: Kali Linux 2021.3
 - PhoneInfoga 2.3.8 (8403f33)
![VirtualBoxVM_2jDdQjyVuv](https://user-images.githubusercontent.com/91392289/134785295-4886c0f6-78fe-4adb-a4d4-c4fbf1c35bd0.png)

**Comment by HugoMskn** [comment]
same here sadly

**Comment by Kashutu** [comment]
> did it worked by chance for u ?

It changed from a failure to "reached max number of queries to the server" or something like that

**Comment by sundowndev** [comment]
See https://github.com/sundowndev/phoneinfoga/issues/947#issuecomment-989612449
