### ISSUE TITLE
"Blacklisted from google search"

### ISSUE THREAD

**Issue by Seyd3** [sundowndev/phoneinfoga#909]
**Describe the bug**
Everything is okay, but for searching for footprints, it says that im blacklisted from google search.

**To Reproduce**
python3 phoneinfoga.py -n +(Number)

**Expected behavior**
Show footprints

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: Kali Linux

**Additional context**
How to fix?
![Bildschirmfoto von 2021-10-03 09-07-30](https://user-images.githubusercontent.com/78030481/135743890-9aec7f96-8063-45d3-9c52-e78fc631a8bb.png)

**Comment by sundowndev** [comment]
Your issue is about version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
