### ISSUE TITLE
Digital Warrant for excessive searches

### ISSUE THREAD

**Issue by egberts** [sundowndev/phoneinfoga#911]
Wow!

Imagine my surprise that if you search for the same thing over 16 days/times for the same number within the last year, this government may be informed. 

This product just might push its users into that category.  

https://www.forbes.com/sites/forbes-personal-shopper/2021/10/01/best-body-lotions/?sh=1db5e452ffa4

**Comment by egberts** [comment]
Too bad that there was no explanation as to why this issue is invalid either.

**Comment by sundowndev** [comment]
> Too bad that there was no explanation as to why this issue is invalid either.

- Your issue does not contain any troubleshoot issue or question, I don't get the point of it
- Your link is irrelevant

I receive too many invalid issues a day to take time to explain myself.
