### ISSUE TITLE
reCAPTCHA problem /problem occurs when we are gathering footprint from google 

### ISSUE THREAD

**Issue by immortal19** [sundowndev/PhoneInfoga#92]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - Python exact version (run `python --version`)

**Additional context**

**Comment by sundowndev** [comment]
Please provide further details about this.

- Which command did you run ?
- What is the exact issue ? (screenshots ?)

Closing for now, since it's invalid.

**Comment by immortal19** [comment]
How Can I solve this issue
Please help....
