### ISSUE TITLE
Valid False on any number scanned

### ISSUE THREAD

**Issue by Ayman-Rayan** [sundowndev/phoneinfoga#926]
**Describe the bug**
so im running linux on vmware and installed the tool it was working perfectly a few days ago when i first set it up 
but now after a few days i got back to it to scan a number and i ran into the issue 

i tried updating and upgrading my linux distribution but still the same .
any help ?

**Comment by TheDapperTurkey** [comment]
That makes alot more sense now I've been messing with it today so do you have any updates or ideas ?

**Comment by sundowndev** [comment]
@TheDapperTurkey I'm currently focusing on other projects (driftctl), but here are a few ideas of improvement:

**Pain points**

1. PhoneInfoga heavily relies on scraping, which makes it unstable and produce inconsistent output
2. We lack of useful information gathering automation
3. A bit of maintenance is needed to improve the codebase

**Possible solutions**

1. Relies more on static data or self-hosted service
2. Add more scanners based on URL generation, documentation links matching number's country code/area, ...
3. Encourage people to contribute

May be we should create a dedicated API to centralize phone number data ? That'd be useful to work with leaked data, but would be closed source.

Let me know if you have ideas as well.

**Comment by looye29** [comment]
To be honest it didn't work for me fro. Github or linux install. Have tried a number of versions and end up where code was in python. Have modified  apikey and used mine and that works for me.

**Comment by projectintel-anon** [comment]
> @TheDapperTurkey I'm currently focusing on other projects (driftctl), but here are a few ideas of improvement:
> 
> **Pain points**
> 
> 1. PhoneInfoga heavily relies on scraping, which makes it unstable and produce inconsistent output
> 2. We lack of useful information gathering automation
> 3. A bit of maintenance is needed to improve the codebase
> 
> **Possible solutions**
> 
> 1. Relies more on static data or self-hosted service
> 2. Add more scanners based on URL generation, documentation links matching number's country code/area, ...
> 3. Encourage people to contribute, or wait for me to have more free time
> 
> May be we should create a dedicated API to centralize phone number data ? That'd be useful to work with leaked data, but would be closed source.
> 
> Let me know if you have ideas as well.

I think the idea of an API with centralised phone number data is a sweet idea, and I would love to help develop it. Adding more scanners means more scanners to maintain if they break or get updated at any point.

**Comment by sundowndev** [comment]
> I think the idea of an API with centralised phone number data is a sweet idea, and I would love to help develop it. Adding more scanners means more scanners to maintain if they break or get updated at any point.

Yeah but there are already tons of such services. I don't want to spend time building another clone of numverify, truepeoplesearch etc. But may be a great addition would be to build an open source alternative that work with contract-APIs to generate a report of a phone number. So maintaining scanners would not be painful anymore.

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).
