### ISSUE TITLE
Your monthly usage limit has been reached

### ISSUE THREAD

**Issue by jmf026** [sundowndev/phoneinfoga#928]
I get this error message when trying to run the mobile search. 

"Numverify scan: the Numverify API returned an error: Your monthly usage limit has been reached. Please upgrade your Subscription Plan." 

console says... "[!] An error occurred: the Numverify API returned an error: Your monthly usage limit has been reached. Please upgrade your Subscription Plan.
[!] It may be Numverify not finding information about that number, or the number being invalid." 

I know the number is not invalid... possibly there is no information of  the number?

**Comment by sundowndev** [comment]
> > Numverify recently stopped working as usual and they no longer allow PhoneInfoga to request info about a phone number.
> 
> are you working on finding another service to use?

I'm working on the design of Phoneinfoga v3, which might take time with my new full time job

**Comment by Acc3ssD3n13d** [comment]
> > > Numverify recently stopped working as usual and they no longer allow PhoneInfoga to request info about a phone number.
> 
> > 
> 
> > are you working on finding another service to use?
> 
> 
> 
> I'm working on the design of Phoneinfoga v3, which might take time with my new full time job

Awesome! If you'd like some help with that I'd be happy to help!

**Comment by sundowndev** [comment]
> > > > Numverify recently stopped working as usual and they no longer allow PhoneInfoga to request info about a phone number.
> > 
> > 
> > > 
> > 
> > 
> > > are you working on finding another service to use?
> > 
> > 
> > I'm working on the design of Phoneinfoga v3, which might take time with my new full time job
> 
> Awesome! If you'd like some help with that I'd be happy to help!

Sure, send me an [email](https://crvx.fr/contact) including your Signal or Discord so we can discuss about it.

**Comment by aqsa-droid** [comment]
i m also seeing the same issue i have somw numbers which are actually disturbing me and i need to know info about them

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).
