### ISSUE TITLE
couldn't get the osint option

### ISSUE THREAD

**Issue by somali-creation** [sundowndev/PhoneInfoga#93]
i could not find the osint option when i entered the python3 phoneinfoga.py -h, the output i got was;
usage: phoneinfoga.py -n <number> [options]

Advanced information gathering tool for phone numbers
(https://github.com/sundowndev/PhoneInfoga) version v1.10.9

optional arguments:
  -h, --help            show this help message and exit
  -n number, --number number
                        The phone number to scan (E164 or international
                        format)
  -i input_file, --input input_file
                        Phone number list to scan (one per line)
  -o output_file, --output output_file
                        Output to save scan results
  -s scanner, --scanner scanner
                        The scanner to use
  --recon               Launch custom format reconnaissance
  --no-ansi             Disable colored output
  -v, --version         Show tool version

**Comment by sundowndev** [comment]
Where did you read you have to use "osint" option ? Read the doc again because this is the old name of the footprints scanner (`-s footprints`)

**Comment by ManuPratap** [comment]
Traceback (most recent call last):
  File "phoneInfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "D:\Git\PhoneInfoga-master\lib\googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'
