### ISSUE TITLE
Error Executing PhoneInfoga 

### ISSUE THREAD

**Issue by Jawws19** [sundowndev/PhoneInfoga#94]
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/home/admin/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

**Comment by skyhook4** [comment]
1) open cmd line and navigate to PhoneInfoga folder
2) type in: 'sudo cp config.example.py config.py' and press enter.
3) type 'python3 phoneinfoga.py -v' and it should popup with the phone infoga symbol and the version number and then it should work for you.

**Comment by Jawws19** [comment]
Ya my dumbass didn’t type python3

**Comment by sundowndev** [comment]
Duplicate of #70
