### ISSUE TITLE
phoneifoga run contry code,location, other details not show plleas help

### ISSUE THREAD

**Issue by Hackerastra01** [sundowndev/phoneinfoga#940]
phoneinfoga run contry code,location, other details not show plleas help
i] Running Numverify.com scan...                                            
[+] Valid: false                                                             
[+] Number: 
[+] Local format:                                                            
[+] International format:                                                    
[+] Country code:  ()                                                        
[+] Country: 
[+] Location:                                                                
[+] Carrier:                                                                 
[+] Line type:

**Comment by AndrewMiranda21** [comment]
Me succede lo mismo hay datos que no se logran obtener mediante la recolección de información lo más importante como la locación o cosas así

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).
