### ISSUE TITLE
Numverify showing results false when used my number

### ISSUE THREAD

**Issue by AnchorAJK** [sundowndev/phoneinfoga#943]
I have One issue that came As i used **_phoneinfoga_**. I am not sure if It is with me only And i am Newbie in **_Kali And Osint tools_**. I'd Like some Help to fix This **Issue**.
![image](https://user-images.githubusercontent.com/88499055/142720815-0445dd19-570d-4614-a842-59dda42122b3.png)

I'd Like to have a solution for my problem. _A Small request from a newbie to the world of techys.!!_

**Comment by mg56274** [comment]
I am getting the same errors and I have tried entering several formats to search the number. Can you please help with this????

**Comment by looye29** [comment]
I am also getting same error. Either using github installation or via python install.

**Comment by sundowndev** [comment]
See https://github.com/sundowndev/phoneinfoga/issues/947#issuecomment-989612449
