### ISSUE TITLE
Filter out empty google queries

### ISSUE THREAD

**Issue by ErAz7** [sundowndev/phoneinfoga#946]
Hey
I'm not really using this tool, but I got some question after tried it by curiousity,

why don't you filter out empty google queries? yeah this would take a little longer to check all links and then log the output, but I think it's better than opening bunch of empty google result pages. Maybe it's a good idea to make it opt-in with a flag

**Comment by sundowndev** [comment]
Google links are statically generated. The reason behind this is opening a headless browser to scrape the links would require to bypass the Google's anti-captcha which is not the goal of PhoneInfoga. Read more here https://sundowndev.github.io/phoneinfoga/usage/#available-scanners

We were doing that in v1 and it wasn't working well.
> Usage of scanners was improved in order to drop usage of Selenium/Geckodriver which has cause many users to have troubleshoots using the tool.

**Comment by ErAz7** [comment]
didn't notice it might result in captcha, makes sense now
Thanks
