### ISSUE TITLE
Numverify scan: the Numverify API returned an error: Your monthly usage limit has been reached. Please upgrade your Subscription Plan.

### ISSUE THREAD

**Issue by ManuelQ59** [sundowndev/phoneinfoga#947]
When executing and using the tool, the data of the telephone number entered is obtained, but a warning appears at the top which indicates the following: 
"Numverify scan: the Numverify API returned an error: Your monthly usage limit has been reached . Please upgrade your Subscription Plan."

how can this be corrected?

**Comment by ABO896** [comment]
Same issue

**Comment by Jelle2003** [comment]
I have also the same issue

**Comment by Noxinal** [comment]
It would be great to be able to put in our own numverify API information.  Each user gets 100 free API pulls a month signing up.

**Comment by sundowndev** [comment]
> It would be great to be able to put in our own numverify API information. Each user gets 100 free API pulls a month signing up.

Anonymous API usage has been disabled by numverify. API key will become mandatory in the future.

**Comment by ManuelQ59** [comment]
> > Sería genial poder poner nuestra propia información de API numverify. Cada usuario obtiene 100 API pull gratuitas al mes registrándose.
> 
> El uso de API anónimo ha sido inhabilitado por numverify. La clave API será obligatoria en el futuro.

is there any way to manually enter numverify scan api code in phoneinfoga tool?

**Comment by sundowndev** [comment]
> > > Sería genial poder poner nuestra propia información de API numverify. Cada usuario obtiene 100 API pull gratuitas al mes registrándose.
> > 
> > 
> > El uso de API anónimo ha sido inhabilitado por numverify. La clave API será obligatoria en el futuro.
> 
> is there any way to manually enter numverify scan api code in phoneinfoga tool?

Not for now but this is planned.

**Comment by ManuelQ59** [comment]
> > > > Sería genial poder poner nuestra propia información de API numverify. Cada usuario obtiene 100 API pull gratuitas al mes registrándose.
> > > 
> > > 
> > > El uso de API anónimo ha sido inhabilitado por numverify. La clave API será obligatoria en el futuro.
> > 
> > 
> > ¿Hay alguna forma de ingresar manualmente el código api de escaneo numverify en la herramienta phoneinfoga?
> 
> No por ahora, pero esto está planeado.

Ohh. Okay, but I'll be waiting for your v.3 of this tool. Thank you

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).
