### ISSUE TITLE
all numbers doesn't work (Running Numverify.com scan... [!] An error occurred: the Numverify API returned an error: Your monthly usage limit has been reached. Please upgrade your Subscription Plan. [!] It may be Numverify not finding information about that number, or the number being invalid.)

### ISSUE THREAD

**Issue by JosephFrankFir** [sundowndev/phoneinfoga#955]
Image:
![image](https://user-images.githubusercontent.com/74981187/145672916-9b3f02dc-bc6e-432e-8198-993e56309562.png)

**Comment by Acc3ssD3n13d** [comment]
This is because numverify has an api usage limit

**Comment by sundowndev** [comment]
Numverify scanner now support authentication in v2.4.0. Please use the latest version and specify an API key (see documentation for details on how to configure a scanner).
