### ISSUE TITLE
Receiving missing code in PhoneInFoga

### ISSUE THREAD

**Issue by tbusman** [sundowndev/PhoneInfoga#96]
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - Python exact version (run `python --version`)

**Additional context**

**Comment by tbusman** [comment]
I'm getting this code when I try to run the program

root@tbusman:~/PhoneInfoga# python3 phoneinfoga.py
Traceback (most recent call last):
  File "phoneinfoga.py", line 14, in <module>
    from lib.output import *
  File "/root/PhoneInfoga/lib/output.py", line 10, in <module>
    from lib.colors import *
  File "/root/PhoneInfoga/lib/colors.py", line 9, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

**Comment by sundowndev** [comment]
Are you sure you've installed requirements ?

```
python3 -m pip install -r requirements.txt --user
```

**Comment by tbusman** [comment]
that command did not work

**Comment by sundowndev** [comment]
What is the output of that command ? Be sure to be in the project's directory.

**Comment by ManuPratap** [comment]
config import* issue

**Comment by Hunkkhan** [comment]
Same error, Although the requirements commands were satisfied.

Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/home/sheryar/Downloads/softwares/PhoneInfoga-master/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

**Comment by despy49** [comment]
Same error

`Traceback (most recent call last):
  File "phoneinfoga.py", line 14, in <module>
    from lib.output import *
  File "/home/buglordie/PhoneInfoga/lib/output.py", line 10, in <module>
    from lib.colors import *
  File "/home/buglordie/PhoneInfoga/lib/colors.py", line 9, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'`

`Requirement already satisfied: phonenumbers==8.10.2 in /home/buglordie/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (8.10.2)
Requirement already satisfied: colorama==0.4.1 in /home/buglordie/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: requests==2.20.0 in /home/buglordie/.local/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (2.20.0)
Requirement already satisfied: selenium==3.141.0 in /home/buglordie/.local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (3.141.0)
Requirement already satisfied: beautifulsoup4==4.7.1 in /home/buglordie/.local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (4.7.1)
Requirement already satisfied: html5lib==1.0.1 in /home/buglordie/.local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (1.0.1)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 3)) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 3)) (2018.1.18)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 3)) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: soupsieve>=1.2 in /home/buglordie/.local/lib/python3.6/site-packages (from beautifulsoup4==4.7.1->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: webencodings in /usr/lib/python3/dist-packages (from html5lib==1.0.1->-r requirements.txt (line 6)) (0.5)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from html5lib==1.0.1->-r requirements.txt (line 6)) (1.11.0)
`

**Comment by sundowndev** [comment]
@despy49 Are you sure you ran the tool using Python 3 ?

**Comment by despy49** [comment]
@sundowndev sorry, my mistake

**Comment by 2AAly** [comment]
I need help please! 

Traceback (most recent call last):
  File "phoneinfoga.py", line 14, in <module>
    from lib.output import *
  File "/data/data/com.termux/files/home/Phoneinfoga/lib/output.py", line 10, in <module>
    from lib.colors import *
ModuleNotFoundError: No module named 'lib.colors'
