### ISSUE TITLE
Usage 

### ISSUE THREAD

**Issue by An0nomUs** [sundowndev/phoneinfoga#973]
Hi there,

I downloaded the zip file for phoneinfoga in my kali vm, and extracted it, but the problem is that I have no idea how to run this program... Can someone please help me out here!

**Comment by JustinH71** [comment]
./phoneinfoga scan -n "+1 (10digitnum)"
./phoneinfoga serve -p 8080 
localhost:8080

**Comment by JustinH71** [comment]
./phoneinfoga scan -n "+1 (10digitnum)"
Or use this command and use the web interface. ./phoneinfoga serve -p 8080 
Type this in your browser's url: localhost:8080

**Comment by yntkts555** [comment]
how to install on my linux bro?

**Comment by sundowndev** [comment]
Please [read documentation](https://sundowndev.github.io/phoneinfoga/getting-started/install/).
