### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by An0nomUs** [sundowndev/phoneinfoga#974]
**Describe the bug**
Can't run phoneinfoga

**To Reproduce**
1. git clone https://github.com/sundowndev/phoneinfoga.git

2. -m python3 pip install -r requirements.txt.

**Expected behavior**
I expected it to clone phoneinfoga, satisfy the requirements, and then run the program.

**Desktop (please complete the following information):**
 - OS: [Kali Linux VM]
 - PhoneInfoga exact version (it's replying with "command not found')
 - Go exact version (go version go1.17.3 linux/amd64)

**Additional context**
Well it did clone phoneinfoga, but when I tried to satisfy the requirements using the 2nd command, it replied saying "no such file or directory" for requirements.txt... I also have noticed that phoneinfoga has changed and now comes with soo many files and directories, unlike before...Can someone please help me out here!

**Comment by sundowndev** [comment]
This project does not use python anymore, please read the documentation.

**Comment by An0nomUs** [comment]
I did, but it didn't include any information for how to install the program using git.

**Comment by An0nomUs** [comment]
Ok... Thanks for the information.
