### ISSUE TITLE
Error When using the tool phoneinfoga

### ISSUE THREAD

**Issue by Manuelq059** [sundowndev/phoneinfoga#983]
I have already run it in a web interface mode, when I search for a phone number I get the following:

Numverify scan: You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]
OVH Telecom scan: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber

How do I provide an api key of num_verify?

How do I solve this 2nd error? ----> OVH Telecom scan

**Comment by sundowndev** [comment]
> How do I provide an api key of num_verify?

https://sundowndev.github.io/phoneinfoga/scanners/#numverify

> How do I solve this 2nd error? ----> OVH Telecom scan

I'm currently investigating this bug, tracking it in #981.

**Comment by jepunband** [comment]
Where do i add the API key? it is not in the docs.

**Comment by sundowndev** [comment]
> Where do i add the API key? it is not in the docs.

Just pass it as an environment variable as per the example 

```shell
$ NUMVERIFY_API_KEY=<key> phoneinfoga scan -n +4176418xxxx
```

**Comment by ManuelQ59** [comment]
> 

And if I mount in a server environment 8080, how would I apply the use of API KEY of NUM VERIFY?

**Comment by sundowndev** [comment]
The exact same way, with the serve command : 

```
$ NUMVERIFY_API_KEY=<key> phoneinfoga serve
```

**Comment by ManuelQ59** [comment]
go run main.go NUMVERIFY_API_KEY=6e9c1be010325c443af4c50175f90efa serve -p 8080
error.

**Comment by ManuelQ59** [comment]
└─# ./phoneinfoga NUMVERIFY_API_KEY=6e9c1be010325c443af4c50175f90efa serve -p 8080
Error: unknown command "NUMVERIFY_API_KEY=6e9c1be010325c443af4c50175f90efa" for "phoneinfoga"
Run 'phoneinfoga --help' for usage.
unknown command "NUMVERIFY_API_KEY=6e9c1be010325c443af4c50175f90efa" for "phoneinfoga"

error!

**Comment by sundowndev** [comment]
An environment variable **must** be defined at the beginning of the command.

```
$ NUMVERIFY_API_KEY=<key> go run main.go serve -p 8080
```

**Comment by sdlgado** [comment]
Hi, I'm using Google Cloud Shell Terminal. 

When I try:

docker run -it -p 8080:8080 sundowndev/phoneinfoga serve -p 8080

I get: Numverify scan: You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]

Where exactly can I set: NUMVERIFY_API_KEY=<xxxxx>?

I tried the following command but didn't work:

docker run -it -p 8080:8080 sundowndev/phoneinfoga NUMVERIFY_API_KEY=<d8c1fee0c0a0b3d86432e08784c9ed95> go run main.go serve -p 8080
-bash: d8c1fee0c0a0b3d86432e08784c9ed95: No such file or directory

**Comment by sundowndev** [comment]
@sdlgado Docker [has a special flag](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) for passing env vars : 
`docker run -it -p 8080:8080 -e NUMVERIFY_API_KEY=secret sundowndev/phoneinfoga serve -p 8080`

**Comment by sdlgado** [comment]
Awesome thanks @sundowndev

**Comment by blackdonie2** [comment]
a question, how to have the api key to be able to scan?

**Comment by sundowndev** [comment]
@blackdonie2 You must create an account on [Numverify](https://numverify.com/product).

**Comment by Zhetikal** [comment]
Once we have the API key how or where do I  put it, please

**Comment by juanmachuca95** [comment]
I hope to usefull for anyone
I tried for linux on ubuntu 20.04 the next ways

`$ NUMVERIFY_API_KEY=xxxxxxxxxxxxxx ./phoneinfoga serve --port 9000`
or 
`$ NUMVERIFY_API_KEY=xxxxxxxxxxxxx ./phoneinfoga scan -n xxxxxxxxxx`

**Comment by BIGBEASTISHANK** [comment]
how to get api key

**Comment by liaQuanco** [comment]
Hi, I'm using Google Cloud Shell Terminal.

I try everything from docker -run ....Numverify_API_KEY=?
And also  docker run -it -p 8080:8080 -e NUMVERIFY_API_KEY=secret sundowndev/phoneinfoga serve -p 8080. 
 can you help me to track local phone number ?i just want to trace the unknown scammer caller Thank you.

**Comment by Manuelq059** [comment]
docker run -it -p 8080:8080 -e NUMVERIFY_API_KEY=secret sundowndev/phoneinfoga serve -p 8080

**Comment by ehosinski** [comment]
This isn't working for me either. Here is my docker run:
docker run -d --name='PhoneInfoga' --net='bridge' --privileged=true -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'NUMVERIFY_API_KEY'='redacted' -p '5080:80/tcp' -p '5500:5000/tcp' 'sundowndev/phoneinfoga' serve -p 80

**Comment by sundowndev** [comment]
Please refer to #1056

**Comment by giantkiller90** [comment]
when i search a valid number then it,s showing this error

OVH Telecom scan: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber

what is the solution?
