### ISSUE TITLE
docker + apikey env

### ISSUE THREAD

**Issue by mmalto** [sundowndev/phoneinfoga#987]
running this command generates the api key error even setting the API key variable in a file (i've tried doing it on the cmd line too see below):

sudo docker run --rm -it --env-file ./phoneinfoga.env sundowndev/phoneinfoga scan -n "<number>"

in the env-file i have the line:
NUMVERIFY_API_KEY="<my key>"

i've tried with ', " and nothing.  they all throw the api key error (still gives me everything back but that piece).

from the cmd line:
 sudo docker run --rm -it -e NUMVERIFY_API_KEY=<my api key> sundowndev/phoneinfoga scan -n "<number>"

any idea what i'm doing wrong?

thanks!

**Comment by sundowndev** [comment]
Hi @mmalto, we currently have issues with our Docker setup making the latest image outdated. As a workaround for now, I suggest to use the next tag. Example : 

```shell
docker run --rm -it -e "NUMVERIFY_API_KEY=secret" sundowndev/phoneinfoga:next scan -n "+33xxxxxxx"
```

**Comment by mmalto** [comment]
that fixed it, thanks!
