### ISSUE TITLE
Unable to unzip

### ISSUE THREAD

**Issue by Learning-moree** [sundowndev/phoneinfoga#990]
$ unzip phoneinfoga_Linux_armv6.tar.gz
Archive:  phoneinfoga_Linux_armv6.tar.gz
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of phoneinfoga_Linux_armv6.tar.gz or
        phoneinfoga_Linux_armv6.tar.gz.zip, and cannot find phoneinfoga_Linux_armv6.tar.gz.ZIP, period.
~ $ unzip tar xvf phoneinfoga_Linux_armv6.tar.gz
unzip:  cannot find or open tar, tar.zip or tar.ZIP.
~ $
![Screenshot_20220124_025221](https://user-images.githubusercontent.com/98286408/150698487-3e200d94-87dd-4847-a45e-b92a428f5d26.jpg)

Pls help

**Comment by ManuelQ59** [comment]
> $ descomprimir phoneinfoga_Linux_armv6.tar.gz Archivo: phoneinfoga_Linux_armv6.tar.gz No se encontró la firma del final del directorio central. Este archivo no es un archivo zip o constituye un disco de un archivo de varias partes. En el último caso, el directorio central y el comentario del archivo comprimido se encontrarán en el último disco(s) de este archivo. descomprimir: no se puede encontrar el directorio de archivos zip en uno de phoneinfoga_Linux_armv6.tar.gz o phoneinfoga_Linux_armv6.tar.gz.zip, y no se puede encontrar phoneinfoga_Linux_armv6.tar.gz.ZIP, punto. ~ $ descomprimir tar xvf phoneinfoga_Linux_armv6.tar.gz descomprimir: no se puede encontrar o abrir tar, tar.zip o tar.ZIP. ~ $ ![Captura de pantalla_20220124_025221](https://user-images.githubusercontent.com/98286408/150698487-3e200d94-87dd-4847-a45e-b92a428f5d26.jpg)
> 
> por favor ayuda

Why unzip the compressed file tar.gz? To unzip the files .gz use the command: tar -xf archive.tar.gz

**Comment by sundowndev** [comment]
Hi @Learning-moree, as said earlier, you should use the tar command : `tar xvf phoneinfoga_Linux_armv6.tar.gz`.

**Comment by Learning-moree** [comment]
@ManuelQ59 it's seems you and me there's no difference, what I know the same things you don't know more than that, @sundowndev thank you man

**Comment by cyberspace-max** [comment]
Thank you


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
